// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Dilate (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_src_rows_V,
        p_src_cols_V,
        p_src_data_stream_0_V_dout,
        p_src_data_stream_0_V_empty_n,
        p_src_data_stream_0_V_read,
        p_src_data_stream_1_V_dout,
        p_src_data_stream_1_V_empty_n,
        p_src_data_stream_1_V_read,
        p_src_data_stream_2_V_dout,
        p_src_data_stream_2_V_empty_n,
        p_src_data_stream_2_V_read,
        p_dst_data_stream_0_V_din,
        p_dst_data_stream_0_V_full_n,
        p_dst_data_stream_0_V_write,
        p_dst_data_stream_1_V_din,
        p_dst_data_stream_1_V_full_n,
        p_dst_data_stream_1_V_write,
        p_dst_data_stream_2_V_din,
        p_dst_data_stream_2_V_full_n,
        p_dst_data_stream_2_V_write
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_pp0_stage0 = 5'd8;
parameter    ap_ST_fsm_state10 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] p_src_rows_V;
input  [31:0] p_src_cols_V;
input  [7:0] p_src_data_stream_0_V_dout;
input   p_src_data_stream_0_V_empty_n;
output   p_src_data_stream_0_V_read;
input  [7:0] p_src_data_stream_1_V_dout;
input   p_src_data_stream_1_V_empty_n;
output   p_src_data_stream_1_V_read;
input  [7:0] p_src_data_stream_2_V_dout;
input   p_src_data_stream_2_V_empty_n;
output   p_src_data_stream_2_V_read;
output  [7:0] p_dst_data_stream_0_V_din;
input   p_dst_data_stream_0_V_full_n;
output   p_dst_data_stream_0_V_write;
output  [7:0] p_dst_data_stream_1_V_din;
input   p_dst_data_stream_1_V_full_n;
output   p_dst_data_stream_1_V_write;
output  [7:0] p_dst_data_stream_2_V_din;
input   p_dst_data_stream_2_V_full_n;
output   p_dst_data_stream_2_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_src_data_stream_0_V_read;
reg p_src_data_stream_1_V_read;
reg p_src_data_stream_2_V_read;
reg p_dst_data_stream_0_V_write;
reg p_dst_data_stream_1_V_write;
reg p_dst_data_stream_2_V_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    p_src_data_stream_0_V_blk_n;
reg    ap_enable_reg_pp0_iter2;
wire    ap_block_pp0_stage0;
reg   [0:0] or_cond_i426_i_i_reg_2136;
reg   [0:0] or_cond_i426_i_i_reg_2136_pp0_iter1_reg;
reg   [0:0] icmp_reg_2080;
reg   [0:0] tmp_48_reg_2071;
reg    p_src_data_stream_1_V_blk_n;
reg    p_src_data_stream_2_V_blk_n;
reg    p_dst_data_stream_0_V_blk_n;
reg    ap_enable_reg_pp0_iter5;
reg   [0:0] or_cond_i_i_reg_2171;
reg   [0:0] or_cond_i_i_reg_2171_pp0_iter4_reg;
reg    p_dst_data_stream_1_V_blk_n;
reg    p_dst_data_stream_2_V_blk_n;
reg   [31:0] t_V_6_reg_570;
reg    ap_block_state1;
wire   [1:0] tmp_37_fu_581_p2;
wire    ap_CS_fsm_state2;
wire   [31:0] tmp_45_fu_593_p2;
wire   [0:0] tmp_38_fu_587_p2;
wire   [31:0] tmp_46_fu_598_p2;
wire   [31:0] tmp_47_fu_603_p2;
wire   [31:0] p_neg394_i_i_fu_608_p2;
wire   [0:0] exitcond390_i_i_fu_613_p2;
wire    ap_CS_fsm_state3;
wire   [31:0] i_V_fu_618_p2;
reg   [31:0] i_V_reg_2066;
wire   [0:0] tmp_48_fu_624_p2;
wire   [0:0] tmp_309_not_fu_629_p2;
reg   [0:0] tmp_309_not_reg_2075;
wire   [0:0] icmp_fu_645_p2;
wire   [0:0] tmp_51_fu_651_p2;
reg   [0:0] tmp_51_reg_2085;
wire   [0:0] tmp_340_0_2_fu_657_p2;
reg   [0:0] tmp_340_0_2_reg_2089;
wire   [0:0] tmp_52_fu_663_p2;
reg   [0:0] tmp_52_reg_2093;
wire   [1:0] tmp_114_fu_819_p1;
reg   [1:0] tmp_114_reg_2106;
wire   [1:0] tmp_115_fu_836_p1;
reg   [1:0] tmp_115_reg_2113;
wire   [1:0] tmp_116_fu_853_p1;
reg   [1:0] tmp_116_reg_2120;
wire   [0:0] exitcond389_i_i_fu_857_p2;
reg   [0:0] exitcond389_i_i_reg_2127;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state4_pp0_stage0_iter0;
wire    ap_block_state5_pp0_stage0_iter1;
reg    ap_predicate_op192_read_state6;
reg    ap_predicate_op200_read_state6;
reg    ap_predicate_op229_read_state6;
reg    ap_predicate_op237_read_state6;
reg    ap_predicate_op266_read_state6;
reg    ap_predicate_op274_read_state6;
reg    ap_block_state6_pp0_stage0_iter2;
wire    ap_block_state7_pp0_stage0_iter3;
wire    ap_block_state8_pp0_stage0_iter4;
reg    ap_block_state9_pp0_stage0_iter5;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] exitcond389_i_i_reg_2127_pp0_iter1_reg;
reg   [0:0] exitcond389_i_i_reg_2127_pp0_iter2_reg;
reg   [0:0] exitcond389_i_i_reg_2127_pp0_iter3_reg;
wire   [31:0] j_V_fu_862_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] or_cond_i426_i_i_fu_909_p2;
wire   [31:0] x_fu_930_p3;
reg   [31:0] x_reg_2140;
wire   [0:0] brmerge_fu_943_p2;
reg   [0:0] brmerge_reg_2145;
reg   [0:0] brmerge_reg_2145_pp0_iter1_reg;
wire   [1:0] tmp_120_fu_948_p1;
reg   [1:0] tmp_120_reg_2158;
reg   [1:0] tmp_120_reg_2158_pp0_iter1_reg;
wire   [0:0] or_cond_i_i_fu_952_p2;
reg   [0:0] or_cond_i_i_reg_2171_pp0_iter1_reg;
reg   [0:0] or_cond_i_i_reg_2171_pp0_iter2_reg;
reg   [0:0] or_cond_i_i_reg_2171_pp0_iter3_reg;
reg   [10:0] k_buf_0_val_3_addr_reg_2175;
reg   [10:0] k_buf_0_val_4_addr_reg_2181;
reg   [10:0] k_buf_0_val_5_addr_reg_2187;
reg   [10:0] k_buf_1_val_3_addr_reg_2193;
reg   [10:0] k_buf_1_val_4_addr_reg_2199;
reg   [10:0] k_buf_1_val_5_addr_reg_2205;
reg   [10:0] k_buf_2_val_3_addr_reg_2211;
reg   [10:0] k_buf_2_val_4_addr_reg_2217;
reg   [10:0] k_buf_2_val_5_addr_reg_2223;
wire   [7:0] src_kernel_win_0_va_37_fu_1058_p3;
reg   [7:0] src_kernel_win_0_va_37_reg_2229;
reg   [7:0] src_kernel_win_0_va_37_reg_2229_pp0_iter3_reg;
wire   [7:0] src_kernel_win_0_va_38_fu_1076_p3;
reg   [7:0] src_kernel_win_0_va_38_reg_2236;
wire   [7:0] src_kernel_win_0_va_39_fu_1094_p3;
reg   [7:0] src_kernel_win_0_va_39_reg_2243;
wire   [7:0] temp_0_i_i_i_059_i_s_fu_1113_p3;
reg   [7:0] temp_0_i_i_i_059_i_s_reg_2248;
wire   [0:0] tmp_386_0_0_2_fu_1121_p2;
reg   [0:0] tmp_386_0_0_2_reg_2253;
wire   [7:0] src_kernel_win_1_va_37_fu_1216_p3;
reg   [7:0] src_kernel_win_1_va_37_reg_2258;
reg   [7:0] src_kernel_win_1_va_37_reg_2258_pp0_iter3_reg;
wire   [7:0] src_kernel_win_1_va_38_fu_1234_p3;
reg   [7:0] src_kernel_win_1_va_38_reg_2265;
wire   [7:0] src_kernel_win_1_va_39_fu_1252_p3;
reg   [7:0] src_kernel_win_1_va_39_reg_2272;
wire   [7:0] temp_0_i_i_i_059_i_25_fu_1271_p3;
reg   [7:0] temp_0_i_i_i_059_i_25_reg_2277;
wire   [0:0] tmp_386_1_0_2_fu_1279_p2;
reg   [0:0] tmp_386_1_0_2_reg_2282;
wire   [7:0] src_kernel_win_2_va_40_fu_1374_p3;
reg   [7:0] src_kernel_win_2_va_40_reg_2287;
reg   [7:0] src_kernel_win_2_va_40_reg_2287_pp0_iter3_reg;
wire   [7:0] src_kernel_win_2_va_41_fu_1392_p3;
reg   [7:0] src_kernel_win_2_va_41_reg_2294;
wire   [7:0] src_kernel_win_2_va_42_fu_1410_p3;
reg   [7:0] src_kernel_win_2_va_42_reg_2301;
wire   [7:0] temp_0_i_i_i_059_i_32_fu_1429_p3;
reg   [7:0] temp_0_i_i_i_059_i_32_reg_2306;
wire   [0:0] tmp_386_2_0_2_fu_1437_p2;
reg   [0:0] tmp_386_2_0_2_reg_2311;
wire   [7:0] temp_0_i_i_i_059_i_22_fu_1526_p3;
reg   [7:0] temp_0_i_i_i_059_i_22_reg_2316;
wire   [7:0] temp_0_i_i_i_059_i_29_fu_1577_p3;
reg   [7:0] temp_0_i_i_i_059_i_29_reg_2322;
wire   [7:0] temp_0_i_i_i_059_i_36_fu_1628_p3;
reg   [7:0] temp_0_i_i_i_059_i_36_reg_2328;
wire   [7:0] tmp_fu_1708_p3;
reg   [7:0] tmp_reg_2334;
wire   [7:0] tmp_61_fu_1752_p3;
reg   [7:0] tmp_61_reg_2339;
wire   [7:0] tmp_62_fu_1796_p3;
reg   [7:0] tmp_62_reg_2344;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state4;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
wire   [10:0] k_buf_0_val_3_address0;
reg    k_buf_0_val_3_ce0;
wire   [7:0] k_buf_0_val_3_q0;
reg    k_buf_0_val_3_ce1;
reg    k_buf_0_val_3_we1;
wire   [10:0] k_buf_0_val_4_address0;
reg    k_buf_0_val_4_ce0;
wire   [7:0] k_buf_0_val_4_q0;
reg    k_buf_0_val_4_ce1;
reg    k_buf_0_val_4_we1;
reg   [7:0] k_buf_0_val_4_d1;
wire   [10:0] k_buf_0_val_5_address0;
reg    k_buf_0_val_5_ce0;
wire   [7:0] k_buf_0_val_5_q0;
reg    k_buf_0_val_5_ce1;
reg    k_buf_0_val_5_we1;
reg   [7:0] k_buf_0_val_5_d1;
wire   [10:0] k_buf_1_val_3_address0;
reg    k_buf_1_val_3_ce0;
wire   [7:0] k_buf_1_val_3_q0;
reg    k_buf_1_val_3_ce1;
reg    k_buf_1_val_3_we1;
wire   [10:0] k_buf_1_val_4_address0;
reg    k_buf_1_val_4_ce0;
wire   [7:0] k_buf_1_val_4_q0;
reg    k_buf_1_val_4_ce1;
reg    k_buf_1_val_4_we1;
reg   [7:0] k_buf_1_val_4_d1;
wire   [10:0] k_buf_1_val_5_address0;
reg    k_buf_1_val_5_ce0;
wire   [7:0] k_buf_1_val_5_q0;
reg    k_buf_1_val_5_ce1;
reg    k_buf_1_val_5_we1;
reg   [7:0] k_buf_1_val_5_d1;
wire   [10:0] k_buf_2_val_3_address0;
reg    k_buf_2_val_3_ce0;
wire   [7:0] k_buf_2_val_3_q0;
reg    k_buf_2_val_3_ce1;
reg    k_buf_2_val_3_we1;
wire   [10:0] k_buf_2_val_4_address0;
reg    k_buf_2_val_4_ce0;
wire   [7:0] k_buf_2_val_4_q0;
reg    k_buf_2_val_4_ce1;
reg    k_buf_2_val_4_we1;
reg   [7:0] k_buf_2_val_4_d1;
wire   [10:0] k_buf_2_val_5_address0;
reg    k_buf_2_val_5_ce0;
wire   [7:0] k_buf_2_val_5_q0;
reg    k_buf_2_val_5_ce1;
reg    k_buf_2_val_5_we1;
reg   [7:0] k_buf_2_val_5_d1;
reg   [1:0] tmp_36_reg_548;
reg   [31:0] t_V_reg_559;
wire    ap_CS_fsm_state10;
wire   [63:0] tmp_63_fu_957_p1;
reg    ap_block_pp0_stage0_01001;
reg   [7:0] src_kernel_win_0_va_fu_230;
reg   [7:0] src_kernel_win_0_va_32_fu_234;
reg   [7:0] src_kernel_win_0_va_33_fu_238;
reg   [7:0] src_kernel_win_0_va_34_fu_242;
reg   [7:0] src_kernel_win_0_va_35_fu_246;
reg   [7:0] src_kernel_win_0_va_36_fu_250;
reg   [7:0] src_kernel_win_1_va_fu_254;
reg   [7:0] src_kernel_win_1_va_32_fu_258;
reg   [7:0] src_kernel_win_1_va_33_fu_262;
reg   [7:0] src_kernel_win_1_va_34_fu_266;
reg   [7:0] src_kernel_win_1_va_35_fu_270;
reg   [7:0] src_kernel_win_1_va_36_fu_274;
reg   [7:0] src_kernel_win_2_va_fu_278;
reg   [7:0] src_kernel_win_2_va_32_fu_282;
reg   [7:0] src_kernel_win_2_va_33_fu_286;
reg   [7:0] src_kernel_win_2_va_34_fu_290;
reg   [7:0] src_kernel_win_2_va_35_fu_294;
reg   [7:0] src_kernel_win_2_va_36_fu_298;
reg   [7:0] right_border_buf_0_s_fu_302;
wire   [7:0] col_buf_0_val_0_0_fu_989_p3;
reg   [7:0] right_border_buf_2_s_fu_306;
wire   [7:0] col_buf_2_val_2_0_fu_1341_p3;
reg   [7:0] right_border_buf_2_17_fu_310;
wire   [7:0] col_buf_2_val_1_0_fu_1323_p3;
reg   [7:0] right_border_buf_0_20_fu_314;
wire   [7:0] col_buf_0_val_1_0_fu_1007_p3;
reg   [7:0] right_border_buf_2_18_fu_318;
wire   [7:0] col_buf_2_val_0_0_fu_1305_p3;
reg   [7:0] right_border_buf_1_s_fu_322;
wire   [7:0] col_buf_1_val_2_0_fu_1183_p3;
reg   [7:0] right_border_buf_0_21_fu_326;
wire   [7:0] col_buf_0_val_2_0_fu_1025_p3;
reg   [7:0] right_border_buf_1_20_fu_330;
wire   [7:0] col_buf_1_val_1_0_fu_1165_p3;
reg   [7:0] right_border_buf_1_21_fu_334;
wire   [7:0] col_buf_1_val_0_0_fu_1147_p3;
wire   [30:0] tmp_107_fu_635_p4;
wire   [31:0] tmp_53_fu_668_p2;
wire   [0:0] tmp_108_fu_674_p3;
wire   [0:0] tmp_55_fu_688_p2;
wire   [0:0] rev_fu_682_p2;
wire   [0:0] tmp_109_fu_699_p3;
wire   [31:0] p_assign_17_0_1_fu_714_p2;
wire   [0:0] tmp_110_fu_720_p3;
wire   [0:0] tmp_367_0_1_fu_734_p2;
wire   [0:0] rev7_fu_728_p2;
wire   [0:0] tmp_111_fu_745_p3;
wire   [31:0] p_assign_17_0_2_fu_760_p2;
wire   [0:0] tmp_112_fu_766_p3;
wire   [0:0] tmp_367_0_2_fu_780_p2;
wire   [0:0] rev8_fu_774_p2;
wire   [0:0] tmp_113_fu_791_p3;
wire   [0:0] or_cond_i_i_i_fu_693_p2;
wire   [31:0] p_assign_1_fu_707_p3;
wire   [31:0] y_3_fu_806_p3;
wire   [31:0] row_assign_s_fu_814_p2;
wire   [0:0] or_cond_i_i_i_0_1_fu_739_p2;
wire   [31:0] p_assign_18_0_1_fu_753_p3;
wire   [31:0] y_3_0_1_fu_823_p3;
wire   [31:0] row_assign_19_0_1_fu_831_p2;
wire   [0:0] or_cond_i_i_i_0_2_fu_785_p2;
wire   [31:0] p_assign_18_0_2_fu_799_p3;
wire   [31:0] y_3_0_2_fu_840_p3;
wire   [31:0] row_assign_19_0_2_fu_848_p2;
wire   [30:0] tmp_117_fu_868_p4;
wire   [31:0] ImagLoc_x_fu_884_p2;
wire   [0:0] tmp_118_fu_890_p3;
wire   [0:0] tmp_59_fu_904_p2;
wire   [0:0] rev9_fu_898_p2;
wire   [0:0] tmp_119_fu_915_p3;
wire   [31:0] p_assign_s_fu_923_p3;
wire   [31:0] col_assign_6_fu_938_p2;
wire   [0:0] icmp3_fu_878_p2;
wire   [7:0] tmp_64_fu_978_p5;
wire   [7:0] tmp_65_fu_996_p5;
wire   [7:0] tmp_66_fu_1014_p5;
wire   [7:0] tmp_67_fu_1047_p5;
wire   [7:0] tmp_68_fu_1065_p5;
wire   [7:0] tmp_69_fu_1083_p5;
wire   [0:0] tmp_386_0_0_1_fu_1107_p2;
wire   [7:0] tmp_70_fu_1136_p5;
wire   [7:0] tmp_71_fu_1154_p5;
wire   [7:0] tmp_72_fu_1172_p5;
wire   [7:0] tmp_73_fu_1205_p5;
wire   [7:0] tmp_74_fu_1223_p5;
wire   [7:0] tmp_75_fu_1241_p5;
wire   [0:0] tmp_386_1_0_1_fu_1265_p2;
wire   [7:0] tmp_76_fu_1294_p5;
wire   [7:0] tmp_77_fu_1312_p5;
wire   [7:0] tmp_78_fu_1330_p5;
wire   [7:0] tmp_79_fu_1363_p5;
wire   [7:0] tmp_80_fu_1381_p5;
wire   [7:0] tmp_81_fu_1399_p5;
wire   [0:0] tmp_386_2_0_1_fu_1423_p2;
wire   [7:0] temp_0_i_i_i_059_i_39_fu_1488_p3;
wire   [0:0] tmp_386_0_1_fu_1493_p2;
wire   [7:0] temp_0_i_i_i_059_i_20_fu_1499_p3;
wire   [0:0] tmp_386_0_1_1_fu_1507_p2;
wire   [7:0] temp_0_i_i_i_059_i_21_fu_1513_p3;
wire   [0:0] tmp_386_0_1_2_fu_1521_p2;
wire   [7:0] temp_0_i_i_i_059_i_26_fu_1539_p3;
wire   [0:0] tmp_386_1_1_fu_1544_p2;
wire   [7:0] temp_0_i_i_i_059_i_27_fu_1550_p3;
wire   [0:0] tmp_386_1_1_1_fu_1558_p2;
wire   [7:0] temp_0_i_i_i_059_i_28_fu_1564_p3;
wire   [0:0] tmp_386_1_1_2_fu_1572_p2;
wire   [7:0] temp_0_i_i_i_059_i_33_fu_1590_p3;
wire   [0:0] tmp_386_2_1_fu_1595_p2;
wire   [7:0] temp_0_i_i_i_059_i_34_fu_1601_p3;
wire   [0:0] tmp_386_2_1_1_fu_1609_p2;
wire   [7:0] temp_0_i_i_i_059_i_35_fu_1615_p3;
wire   [0:0] tmp_386_2_1_2_fu_1623_p2;
wire   [0:0] tmp_386_0_2_fu_1677_p2;
wire   [7:0] temp_0_i_i_i_059_i_23_fu_1682_p3;
wire   [0:0] tmp_386_0_2_1_fu_1689_p2;
wire   [7:0] temp_0_i_i_i_059_i_24_fu_1695_p3;
wire   [0:0] tmp_386_0_2_2_fu_1703_p2;
wire   [0:0] tmp_386_1_2_fu_1721_p2;
wire   [7:0] temp_0_i_i_i_059_i_30_fu_1726_p3;
wire   [0:0] tmp_386_1_2_1_fu_1733_p2;
wire   [7:0] temp_0_i_i_i_059_i_31_fu_1739_p3;
wire   [0:0] tmp_386_1_2_2_fu_1747_p2;
wire   [0:0] tmp_386_2_2_fu_1765_p2;
wire   [7:0] temp_0_i_i_i_059_i_37_fu_1770_p3;
wire   [0:0] tmp_386_2_2_1_fu_1777_p2;
wire   [7:0] temp_0_i_i_i_059_i_38_fu_1783_p3;
wire   [0:0] tmp_386_2_2_2_fu_1791_p2;
reg   [4:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_589;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 5'd1;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
end

Filter2D_k_buf_0_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_0_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_3_address0),
    .ce0(k_buf_0_val_3_ce0),
    .q0(k_buf_0_val_3_q0),
    .address1(k_buf_0_val_3_addr_reg_2175),
    .ce1(k_buf_0_val_3_ce1),
    .we1(k_buf_0_val_3_we1),
    .d1(p_src_data_stream_0_V_dout)
);

Filter2D_k_buf_0_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_0_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_4_address0),
    .ce0(k_buf_0_val_4_ce0),
    .q0(k_buf_0_val_4_q0),
    .address1(k_buf_0_val_4_addr_reg_2181),
    .ce1(k_buf_0_val_4_ce1),
    .we1(k_buf_0_val_4_we1),
    .d1(k_buf_0_val_4_d1)
);

Filter2D_k_buf_0_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_0_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_5_address0),
    .ce0(k_buf_0_val_5_ce0),
    .q0(k_buf_0_val_5_q0),
    .address1(k_buf_0_val_5_addr_reg_2187),
    .ce1(k_buf_0_val_5_ce1),
    .we1(k_buf_0_val_5_we1),
    .d1(k_buf_0_val_5_d1)
);

Filter2D_k_buf_0_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_1_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_1_val_3_address0),
    .ce0(k_buf_1_val_3_ce0),
    .q0(k_buf_1_val_3_q0),
    .address1(k_buf_1_val_3_addr_reg_2193),
    .ce1(k_buf_1_val_3_ce1),
    .we1(k_buf_1_val_3_we1),
    .d1(p_src_data_stream_1_V_dout)
);

Filter2D_k_buf_0_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_1_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_1_val_4_address0),
    .ce0(k_buf_1_val_4_ce0),
    .q0(k_buf_1_val_4_q0),
    .address1(k_buf_1_val_4_addr_reg_2199),
    .ce1(k_buf_1_val_4_ce1),
    .we1(k_buf_1_val_4_we1),
    .d1(k_buf_1_val_4_d1)
);

Filter2D_k_buf_0_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_1_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_1_val_5_address0),
    .ce0(k_buf_1_val_5_ce0),
    .q0(k_buf_1_val_5_q0),
    .address1(k_buf_1_val_5_addr_reg_2205),
    .ce1(k_buf_1_val_5_ce1),
    .we1(k_buf_1_val_5_we1),
    .d1(k_buf_1_val_5_d1)
);

Filter2D_k_buf_0_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_2_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_2_val_3_address0),
    .ce0(k_buf_2_val_3_ce0),
    .q0(k_buf_2_val_3_q0),
    .address1(k_buf_2_val_3_addr_reg_2211),
    .ce1(k_buf_2_val_3_ce1),
    .we1(k_buf_2_val_3_we1),
    .d1(p_src_data_stream_2_V_dout)
);

Filter2D_k_buf_0_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_2_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_2_val_4_address0),
    .ce0(k_buf_2_val_4_ce0),
    .q0(k_buf_2_val_4_q0),
    .address1(k_buf_2_val_4_addr_reg_2217),
    .ce1(k_buf_2_val_4_ce1),
    .we1(k_buf_2_val_4_we1),
    .d1(k_buf_2_val_4_d1)
);

Filter2D_k_buf_0_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_2_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_2_val_5_address0),
    .ce0(k_buf_2_val_5_ce0),
    .q0(k_buf_2_val_5_q0),
    .address1(k_buf_2_val_5_addr_reg_2223),
    .ce1(k_buf_2_val_5_ce1),
    .we1(k_buf_2_val_5_we1),
    .d1(k_buf_2_val_5_d1)
);

image_filter_mux_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_filter_mux_kbM_U99(
    .din0(right_border_buf_0_s_fu_302),
    .din1(8'd0),
    .din2(8'd0),
    .din3(tmp_120_reg_2158_pp0_iter1_reg),
    .dout(tmp_64_fu_978_p5)
);

image_filter_mux_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_filter_mux_kbM_U100(
    .din0(right_border_buf_0_20_fu_314),
    .din1(8'd0),
    .din2(8'd0),
    .din3(tmp_120_reg_2158_pp0_iter1_reg),
    .dout(tmp_65_fu_996_p5)
);

image_filter_mux_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_filter_mux_kbM_U101(
    .din0(right_border_buf_0_21_fu_326),
    .din1(8'd0),
    .din2(8'd0),
    .din3(tmp_120_reg_2158_pp0_iter1_reg),
    .dout(tmp_66_fu_1014_p5)
);

image_filter_mux_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_filter_mux_kbM_U102(
    .din0(col_buf_0_val_0_0_fu_989_p3),
    .din1(col_buf_0_val_1_0_fu_1007_p3),
    .din2(col_buf_0_val_2_0_fu_1025_p3),
    .din3(tmp_114_reg_2106),
    .dout(tmp_67_fu_1047_p5)
);

image_filter_mux_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_filter_mux_kbM_U103(
    .din0(col_buf_0_val_0_0_fu_989_p3),
    .din1(col_buf_0_val_1_0_fu_1007_p3),
    .din2(col_buf_0_val_2_0_fu_1025_p3),
    .din3(tmp_115_reg_2113),
    .dout(tmp_68_fu_1065_p5)
);

image_filter_mux_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_filter_mux_kbM_U104(
    .din0(col_buf_0_val_0_0_fu_989_p3),
    .din1(col_buf_0_val_1_0_fu_1007_p3),
    .din2(col_buf_0_val_2_0_fu_1025_p3),
    .din3(tmp_116_reg_2120),
    .dout(tmp_69_fu_1083_p5)
);

image_filter_mux_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_filter_mux_kbM_U105(
    .din0(right_border_buf_1_21_fu_334),
    .din1(8'd0),
    .din2(8'd0),
    .din3(tmp_120_reg_2158_pp0_iter1_reg),
    .dout(tmp_70_fu_1136_p5)
);

image_filter_mux_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_filter_mux_kbM_U106(
    .din0(right_border_buf_1_20_fu_330),
    .din1(8'd0),
    .din2(8'd0),
    .din3(tmp_120_reg_2158_pp0_iter1_reg),
    .dout(tmp_71_fu_1154_p5)
);

image_filter_mux_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_filter_mux_kbM_U107(
    .din0(right_border_buf_1_s_fu_322),
    .din1(8'd0),
    .din2(8'd0),
    .din3(tmp_120_reg_2158_pp0_iter1_reg),
    .dout(tmp_72_fu_1172_p5)
);

image_filter_mux_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_filter_mux_kbM_U108(
    .din0(col_buf_1_val_0_0_fu_1147_p3),
    .din1(col_buf_1_val_1_0_fu_1165_p3),
    .din2(col_buf_1_val_2_0_fu_1183_p3),
    .din3(tmp_114_reg_2106),
    .dout(tmp_73_fu_1205_p5)
);

image_filter_mux_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_filter_mux_kbM_U109(
    .din0(col_buf_1_val_0_0_fu_1147_p3),
    .din1(col_buf_1_val_1_0_fu_1165_p3),
    .din2(col_buf_1_val_2_0_fu_1183_p3),
    .din3(tmp_115_reg_2113),
    .dout(tmp_74_fu_1223_p5)
);

image_filter_mux_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_filter_mux_kbM_U110(
    .din0(col_buf_1_val_0_0_fu_1147_p3),
    .din1(col_buf_1_val_1_0_fu_1165_p3),
    .din2(col_buf_1_val_2_0_fu_1183_p3),
    .din3(tmp_116_reg_2120),
    .dout(tmp_75_fu_1241_p5)
);

image_filter_mux_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_filter_mux_kbM_U111(
    .din0(right_border_buf_2_18_fu_318),
    .din1(8'd0),
    .din2(8'd0),
    .din3(tmp_120_reg_2158_pp0_iter1_reg),
    .dout(tmp_76_fu_1294_p5)
);

image_filter_mux_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_filter_mux_kbM_U112(
    .din0(right_border_buf_2_17_fu_310),
    .din1(8'd0),
    .din2(8'd0),
    .din3(tmp_120_reg_2158_pp0_iter1_reg),
    .dout(tmp_77_fu_1312_p5)
);

image_filter_mux_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_filter_mux_kbM_U113(
    .din0(right_border_buf_2_s_fu_306),
    .din1(8'd0),
    .din2(8'd0),
    .din3(tmp_120_reg_2158_pp0_iter1_reg),
    .dout(tmp_78_fu_1330_p5)
);

image_filter_mux_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_filter_mux_kbM_U114(
    .din0(col_buf_2_val_0_0_fu_1305_p3),
    .din1(col_buf_2_val_1_0_fu_1323_p3),
    .din2(col_buf_2_val_2_0_fu_1341_p3),
    .din3(tmp_114_reg_2106),
    .dout(tmp_79_fu_1363_p5)
);

image_filter_mux_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_filter_mux_kbM_U115(
    .din0(col_buf_2_val_0_0_fu_1305_p3),
    .din1(col_buf_2_val_1_0_fu_1323_p3),
    .din2(col_buf_2_val_2_0_fu_1341_p3),
    .din3(tmp_115_reg_2113),
    .dout(tmp_80_fu_1381_p5)
);

image_filter_mux_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_filter_mux_kbM_U116(
    .din0(col_buf_2_val_0_0_fu_1305_p3),
    .din1(col_buf_2_val_1_0_fu_1323_p3),
    .din2(col_buf_2_val_2_0_fu_1341_p3),
    .din3(tmp_116_reg_2120),
    .dout(tmp_81_fu_1399_p5)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((exitcond390_i_i_fu_613_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state4) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((exitcond390_i_i_fu_613_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state4)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state4);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end else if (((exitcond390_i_i_fu_613_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_enable_reg_pp0_iter5 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond389_i_i_fu_857_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        t_V_6_reg_570 <= j_V_fu_862_p2;
    end else if (((exitcond390_i_i_fu_613_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        t_V_6_reg_570 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        t_V_reg_559 <= i_V_reg_2066;
    end else if (((tmp_38_fu_587_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        t_V_reg_559 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        tmp_36_reg_548 <= 2'd0;
    end else if (((tmp_38_fu_587_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        tmp_36_reg_548 <= tmp_37_fu_581_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond389_i_i_fu_857_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        brmerge_reg_2145 <= brmerge_fu_943_p2;
        or_cond_i426_i_i_reg_2136 <= or_cond_i426_i_i_fu_909_p2;
        or_cond_i_i_reg_2171 <= or_cond_i_i_fu_952_p2;
        tmp_120_reg_2158 <= tmp_120_fu_948_p1;
        x_reg_2140 <= x_fu_930_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        brmerge_reg_2145_pp0_iter1_reg <= brmerge_reg_2145;
        exitcond389_i_i_reg_2127 <= exitcond389_i_i_fu_857_p2;
        exitcond389_i_i_reg_2127_pp0_iter1_reg <= exitcond389_i_i_reg_2127;
        k_buf_0_val_3_addr_reg_2175 <= tmp_63_fu_957_p1;
        k_buf_0_val_4_addr_reg_2181 <= tmp_63_fu_957_p1;
        k_buf_0_val_5_addr_reg_2187 <= tmp_63_fu_957_p1;
        k_buf_1_val_3_addr_reg_2193 <= tmp_63_fu_957_p1;
        k_buf_1_val_4_addr_reg_2199 <= tmp_63_fu_957_p1;
        k_buf_1_val_5_addr_reg_2205 <= tmp_63_fu_957_p1;
        k_buf_2_val_3_addr_reg_2211 <= tmp_63_fu_957_p1;
        k_buf_2_val_4_addr_reg_2217 <= tmp_63_fu_957_p1;
        k_buf_2_val_5_addr_reg_2223 <= tmp_63_fu_957_p1;
        or_cond_i426_i_i_reg_2136_pp0_iter1_reg <= or_cond_i426_i_i_reg_2136;
        or_cond_i_i_reg_2171_pp0_iter1_reg <= or_cond_i_i_reg_2171;
        tmp_120_reg_2158_pp0_iter1_reg <= tmp_120_reg_2158;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        exitcond389_i_i_reg_2127_pp0_iter2_reg <= exitcond389_i_i_reg_2127_pp0_iter1_reg;
        exitcond389_i_i_reg_2127_pp0_iter3_reg <= exitcond389_i_i_reg_2127_pp0_iter2_reg;
        or_cond_i_i_reg_2171_pp0_iter2_reg <= or_cond_i_i_reg_2171_pp0_iter1_reg;
        or_cond_i_i_reg_2171_pp0_iter3_reg <= or_cond_i_i_reg_2171_pp0_iter2_reg;
        or_cond_i_i_reg_2171_pp0_iter4_reg <= or_cond_i_i_reg_2171_pp0_iter3_reg;
        src_kernel_win_0_va_37_reg_2229 <= src_kernel_win_0_va_37_fu_1058_p3;
        src_kernel_win_0_va_37_reg_2229_pp0_iter3_reg <= src_kernel_win_0_va_37_reg_2229;
        src_kernel_win_0_va_38_reg_2236 <= src_kernel_win_0_va_38_fu_1076_p3;
        src_kernel_win_0_va_39_reg_2243 <= src_kernel_win_0_va_39_fu_1094_p3;
        src_kernel_win_1_va_37_reg_2258 <= src_kernel_win_1_va_37_fu_1216_p3;
        src_kernel_win_1_va_37_reg_2258_pp0_iter3_reg <= src_kernel_win_1_va_37_reg_2258;
        src_kernel_win_1_va_38_reg_2265 <= src_kernel_win_1_va_38_fu_1234_p3;
        src_kernel_win_1_va_39_reg_2272 <= src_kernel_win_1_va_39_fu_1252_p3;
        src_kernel_win_2_va_40_reg_2287 <= src_kernel_win_2_va_40_fu_1374_p3;
        src_kernel_win_2_va_40_reg_2287_pp0_iter3_reg <= src_kernel_win_2_va_40_reg_2287;
        src_kernel_win_2_va_41_reg_2294 <= src_kernel_win_2_va_41_fu_1392_p3;
        src_kernel_win_2_va_42_reg_2301 <= src_kernel_win_2_va_42_fu_1410_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        i_V_reg_2066 <= i_V_fu_618_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond390_i_i_fu_613_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        icmp_reg_2080 <= icmp_fu_645_p2;
        tmp_114_reg_2106 <= tmp_114_fu_819_p1;
        tmp_115_reg_2113 <= tmp_115_fu_836_p1;
        tmp_116_reg_2120 <= tmp_116_fu_853_p1;
        tmp_309_not_reg_2075 <= tmp_309_not_fu_629_p2;
        tmp_340_0_2_reg_2089 <= tmp_340_0_2_fu_657_p2;
        tmp_48_reg_2071 <= tmp_48_fu_624_p2;
        tmp_51_reg_2085 <= tmp_51_fu_651_p2;
        tmp_52_reg_2093 <= tmp_52_fu_663_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_op200_read_state6 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        right_border_buf_0_20_fu_314 <= col_buf_0_val_1_0_fu_1007_p3;
        right_border_buf_0_21_fu_326 <= col_buf_0_val_2_0_fu_1025_p3;
        right_border_buf_0_s_fu_302 <= col_buf_0_val_0_0_fu_989_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_op237_read_state6 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        right_border_buf_1_20_fu_330 <= col_buf_1_val_1_0_fu_1165_p3;
        right_border_buf_1_21_fu_334 <= col_buf_1_val_0_0_fu_1147_p3;
        right_border_buf_1_s_fu_322 <= col_buf_1_val_2_0_fu_1183_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_op274_read_state6 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        right_border_buf_2_17_fu_310 <= col_buf_2_val_1_0_fu_1323_p3;
        right_border_buf_2_18_fu_318 <= col_buf_2_val_0_0_fu_1305_p3;
        right_border_buf_2_s_fu_306 <= col_buf_2_val_2_0_fu_1341_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond389_i_i_reg_2127_pp0_iter3_reg == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_kernel_win_0_va_32_fu_234 <= src_kernel_win_0_va_fu_230;
        src_kernel_win_0_va_fu_230 <= src_kernel_win_0_va_37_reg_2229_pp0_iter3_reg;
        src_kernel_win_1_va_32_fu_258 <= src_kernel_win_1_va_fu_254;
        src_kernel_win_1_va_fu_254 <= src_kernel_win_1_va_37_reg_2258_pp0_iter3_reg;
        src_kernel_win_2_va_32_fu_282 <= src_kernel_win_2_va_fu_278;
        src_kernel_win_2_va_fu_278 <= src_kernel_win_2_va_40_reg_2287_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond389_i_i_reg_2127_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_kernel_win_0_va_33_fu_238 <= src_kernel_win_0_va_38_reg_2236;
        src_kernel_win_0_va_34_fu_242 <= src_kernel_win_0_va_33_fu_238;
        src_kernel_win_1_va_33_fu_262 <= src_kernel_win_1_va_38_reg_2265;
        src_kernel_win_1_va_34_fu_266 <= src_kernel_win_1_va_33_fu_262;
        src_kernel_win_2_va_33_fu_286 <= src_kernel_win_2_va_41_reg_2294;
        src_kernel_win_2_va_34_fu_290 <= src_kernel_win_2_va_33_fu_286;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond389_i_i_reg_2127_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_kernel_win_0_va_35_fu_246 <= src_kernel_win_0_va_39_fu_1094_p3;
        src_kernel_win_0_va_36_fu_250 <= src_kernel_win_0_va_35_fu_246;
        src_kernel_win_1_va_35_fu_270 <= src_kernel_win_1_va_39_fu_1252_p3;
        src_kernel_win_1_va_36_fu_274 <= src_kernel_win_1_va_35_fu_270;
        src_kernel_win_2_va_35_fu_294 <= src_kernel_win_2_va_42_fu_1410_p3;
        src_kernel_win_2_va_36_fu_298 <= src_kernel_win_2_va_35_fu_294;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_i_reg_2171_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        temp_0_i_i_i_059_i_22_reg_2316 <= temp_0_i_i_i_059_i_22_fu_1526_p3;
        temp_0_i_i_i_059_i_29_reg_2322 <= temp_0_i_i_i_059_i_29_fu_1577_p3;
        temp_0_i_i_i_059_i_36_reg_2328 <= temp_0_i_i_i_059_i_36_fu_1628_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_i_reg_2171_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        temp_0_i_i_i_059_i_25_reg_2277 <= temp_0_i_i_i_059_i_25_fu_1271_p3;
        temp_0_i_i_i_059_i_32_reg_2306 <= temp_0_i_i_i_059_i_32_fu_1429_p3;
        temp_0_i_i_i_059_i_s_reg_2248 <= temp_0_i_i_i_059_i_s_fu_1113_p3;
        tmp_386_0_0_2_reg_2253 <= tmp_386_0_0_2_fu_1121_p2;
        tmp_386_1_0_2_reg_2282 <= tmp_386_1_0_2_fu_1279_p2;
        tmp_386_2_0_2_reg_2311 <= tmp_386_2_0_2_fu_1437_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_i_reg_2171_pp0_iter3_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_61_reg_2339 <= tmp_61_fu_1752_p3;
        tmp_62_reg_2344 <= tmp_62_fu_1796_p3;
        tmp_reg_2334 <= tmp_fu_1708_p3;
    end
end

always @ (*) begin
    if ((exitcond389_i_i_fu_857_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state4 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state4 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond390_i_i_fu_613_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond390_i_i_fu_613_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_3_ce0 = 1'b1;
    end else begin
        k_buf_0_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_reg_2080 == 1'd0) & (tmp_340_0_2_reg_2089 == 1'd1) & (or_cond_i426_i_i_reg_2136_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_predicate_op200_read_state6 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_3_ce1 = 1'b1;
    end else begin
        k_buf_0_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_reg_2080 == 1'd0) & (tmp_340_0_2_reg_2089 == 1'd1) & (or_cond_i426_i_i_reg_2136_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_predicate_op200_read_state6 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_3_we1 = 1'b1;
    end else begin
        k_buf_0_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_4_ce0 = 1'b1;
    end else begin
        k_buf_0_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_reg_2080 == 1'd0) & (tmp_51_reg_2085 == 1'd1) & (or_cond_i426_i_i_reg_2136_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_predicate_op200_read_state6 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_4_ce1 = 1'b1;
    end else begin
        k_buf_0_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((ap_predicate_op200_read_state6 == 1'b1)) begin
            k_buf_0_val_4_d1 = k_buf_0_val_3_q0;
        end else if ((1'b1 == ap_condition_589)) begin
            k_buf_0_val_4_d1 = p_src_data_stream_0_V_dout;
        end else begin
            k_buf_0_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_reg_2080 == 1'd0) & (tmp_51_reg_2085 == 1'd1) & (or_cond_i426_i_i_reg_2136_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_predicate_op200_read_state6 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_4_we1 = 1'b1;
    end else begin
        k_buf_0_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_5_ce0 = 1'b1;
    end else begin
        k_buf_0_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_reg_2080 == 1'd0) & (tmp_51_reg_2085 == 1'd1) & (or_cond_i426_i_i_reg_2136_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_predicate_op200_read_state6 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_5_ce1 = 1'b1;
    end else begin
        k_buf_0_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((ap_predicate_op200_read_state6 == 1'b1)) begin
            k_buf_0_val_5_d1 = k_buf_0_val_4_q0;
        end else if ((1'b1 == ap_condition_589)) begin
            k_buf_0_val_5_d1 = p_src_data_stream_0_V_dout;
        end else begin
            k_buf_0_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_reg_2080 == 1'd0) & (tmp_51_reg_2085 == 1'd1) & (or_cond_i426_i_i_reg_2136_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_predicate_op200_read_state6 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_5_we1 = 1'b1;
    end else begin
        k_buf_0_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_1_val_3_ce0 = 1'b1;
    end else begin
        k_buf_1_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_reg_2080 == 1'd0) & (tmp_340_0_2_reg_2089 == 1'd1) & (or_cond_i426_i_i_reg_2136_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_predicate_op237_read_state6 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_1_val_3_ce1 = 1'b1;
    end else begin
        k_buf_1_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_reg_2080 == 1'd0) & (tmp_340_0_2_reg_2089 == 1'd1) & (or_cond_i426_i_i_reg_2136_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_predicate_op237_read_state6 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_1_val_3_we1 = 1'b1;
    end else begin
        k_buf_1_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_1_val_4_ce0 = 1'b1;
    end else begin
        k_buf_1_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_reg_2080 == 1'd0) & (tmp_51_reg_2085 == 1'd1) & (or_cond_i426_i_i_reg_2136_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_predicate_op237_read_state6 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_1_val_4_ce1 = 1'b1;
    end else begin
        k_buf_1_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((ap_predicate_op237_read_state6 == 1'b1)) begin
            k_buf_1_val_4_d1 = k_buf_1_val_3_q0;
        end else if ((1'b1 == ap_condition_589)) begin
            k_buf_1_val_4_d1 = p_src_data_stream_1_V_dout;
        end else begin
            k_buf_1_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_1_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_reg_2080 == 1'd0) & (tmp_51_reg_2085 == 1'd1) & (or_cond_i426_i_i_reg_2136_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_predicate_op237_read_state6 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_1_val_4_we1 = 1'b1;
    end else begin
        k_buf_1_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_1_val_5_ce0 = 1'b1;
    end else begin
        k_buf_1_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_reg_2080 == 1'd0) & (tmp_51_reg_2085 == 1'd1) & (or_cond_i426_i_i_reg_2136_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_predicate_op237_read_state6 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_1_val_5_ce1 = 1'b1;
    end else begin
        k_buf_1_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((ap_predicate_op237_read_state6 == 1'b1)) begin
            k_buf_1_val_5_d1 = k_buf_1_val_4_q0;
        end else if ((1'b1 == ap_condition_589)) begin
            k_buf_1_val_5_d1 = p_src_data_stream_1_V_dout;
        end else begin
            k_buf_1_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_1_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_reg_2080 == 1'd0) & (tmp_51_reg_2085 == 1'd1) & (or_cond_i426_i_i_reg_2136_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_predicate_op237_read_state6 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_1_val_5_we1 = 1'b1;
    end else begin
        k_buf_1_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_2_val_3_ce0 = 1'b1;
    end else begin
        k_buf_2_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_reg_2080 == 1'd0) & (tmp_340_0_2_reg_2089 == 1'd1) & (or_cond_i426_i_i_reg_2136_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_predicate_op274_read_state6 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_2_val_3_ce1 = 1'b1;
    end else begin
        k_buf_2_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_reg_2080 == 1'd0) & (tmp_340_0_2_reg_2089 == 1'd1) & (or_cond_i426_i_i_reg_2136_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_predicate_op274_read_state6 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_2_val_3_we1 = 1'b1;
    end else begin
        k_buf_2_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_2_val_4_ce0 = 1'b1;
    end else begin
        k_buf_2_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_reg_2080 == 1'd0) & (tmp_51_reg_2085 == 1'd1) & (or_cond_i426_i_i_reg_2136_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_predicate_op274_read_state6 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_2_val_4_ce1 = 1'b1;
    end else begin
        k_buf_2_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((ap_predicate_op274_read_state6 == 1'b1)) begin
            k_buf_2_val_4_d1 = k_buf_2_val_3_q0;
        end else if ((1'b1 == ap_condition_589)) begin
            k_buf_2_val_4_d1 = p_src_data_stream_2_V_dout;
        end else begin
            k_buf_2_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_2_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_reg_2080 == 1'd0) & (tmp_51_reg_2085 == 1'd1) & (or_cond_i426_i_i_reg_2136_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_predicate_op274_read_state6 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_2_val_4_we1 = 1'b1;
    end else begin
        k_buf_2_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_2_val_5_ce0 = 1'b1;
    end else begin
        k_buf_2_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_reg_2080 == 1'd0) & (tmp_51_reg_2085 == 1'd1) & (or_cond_i426_i_i_reg_2136_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_predicate_op274_read_state6 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_2_val_5_ce1 = 1'b1;
    end else begin
        k_buf_2_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((ap_predicate_op274_read_state6 == 1'b1)) begin
            k_buf_2_val_5_d1 = k_buf_2_val_4_q0;
        end else if ((1'b1 == ap_condition_589)) begin
            k_buf_2_val_5_d1 = p_src_data_stream_2_V_dout;
        end else begin
            k_buf_2_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_2_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_reg_2080 == 1'd0) & (tmp_51_reg_2085 == 1'd1) & (or_cond_i426_i_i_reg_2136_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_predicate_op274_read_state6 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_2_val_5_we1 = 1'b1;
    end else begin
        k_buf_2_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((or_cond_i_i_reg_2171_pp0_iter4_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        p_dst_data_stream_0_V_blk_n = p_dst_data_stream_0_V_full_n;
    end else begin
        p_dst_data_stream_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_cond_i_i_reg_2171_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_dst_data_stream_0_V_write = 1'b1;
    end else begin
        p_dst_data_stream_0_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((or_cond_i_i_reg_2171_pp0_iter4_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        p_dst_data_stream_1_V_blk_n = p_dst_data_stream_1_V_full_n;
    end else begin
        p_dst_data_stream_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_cond_i_i_reg_2171_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_dst_data_stream_1_V_write = 1'b1;
    end else begin
        p_dst_data_stream_1_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((or_cond_i_i_reg_2171_pp0_iter4_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        p_dst_data_stream_2_V_blk_n = p_dst_data_stream_2_V_full_n;
    end else begin
        p_dst_data_stream_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_cond_i_i_reg_2171_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_dst_data_stream_2_V_write = 1'b1;
    end else begin
        p_dst_data_stream_2_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_reg_2080 == 1'd0) & (or_cond_i426_i_i_reg_2136_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((tmp_48_reg_2071 == 1'd1) & (icmp_reg_2080 == 1'd1) & (or_cond_i426_i_i_reg_2136_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        p_src_data_stream_0_V_blk_n = p_src_data_stream_0_V_empty_n;
    end else begin
        p_src_data_stream_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_predicate_op200_read_state6 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_predicate_op192_read_state6 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        p_src_data_stream_0_V_read = 1'b1;
    end else begin
        p_src_data_stream_0_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_reg_2080 == 1'd0) & (or_cond_i426_i_i_reg_2136_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((tmp_48_reg_2071 == 1'd1) & (icmp_reg_2080 == 1'd1) & (or_cond_i426_i_i_reg_2136_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        p_src_data_stream_1_V_blk_n = p_src_data_stream_1_V_empty_n;
    end else begin
        p_src_data_stream_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_predicate_op237_read_state6 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_predicate_op229_read_state6 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        p_src_data_stream_1_V_read = 1'b1;
    end else begin
        p_src_data_stream_1_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_reg_2080 == 1'd0) & (or_cond_i426_i_i_reg_2136_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((tmp_48_reg_2071 == 1'd1) & (icmp_reg_2080 == 1'd1) & (or_cond_i426_i_i_reg_2136_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        p_src_data_stream_2_V_blk_n = p_src_data_stream_2_V_empty_n;
    end else begin
        p_src_data_stream_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_predicate_op274_read_state6 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_predicate_op266_read_state6 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        p_src_data_stream_2_V_read = 1'b1;
    end else begin
        p_src_data_stream_2_V_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((tmp_38_fu_587_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((exitcond390_i_i_fu_613_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((exitcond389_i_i_fu_857_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1)) & ~((ap_enable_reg_pp0_iter4 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter5 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter4 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((exitcond389_i_i_fu_857_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ImagLoc_x_fu_884_p2 = ($signed(32'd4294967295) + $signed(t_V_6_reg_570));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter5 == 1'b1) & (((or_cond_i_i_reg_2171_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((or_cond_i_i_reg_2171_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((or_cond_i_i_reg_2171_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)))) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op274_read_state6 == 1'b1)) | ((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op266_read_state6 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op237_read_state6 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op229_read_state6 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op200_read_state6 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op192_read_state6 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter5 == 1'b1) & (((or_cond_i_i_reg_2171_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((or_cond_i_i_reg_2171_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((or_cond_i_i_reg_2171_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)))) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op274_read_state6 == 1'b1)) | ((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op266_read_state6 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op237_read_state6 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op229_read_state6 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op200_read_state6 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op192_read_state6 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter5 == 1'b1) & (((or_cond_i_i_reg_2171_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((or_cond_i_i_reg_2171_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((or_cond_i_i_reg_2171_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)))) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op274_read_state6 == 1'b1)) | ((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op266_read_state6 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op237_read_state6 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op229_read_state6 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op200_read_state6 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op192_read_state6 == 1'b1)))));
end

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state4_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state6_pp0_stage0_iter2 = (((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op274_read_state6 == 1'b1)) | ((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op266_read_state6 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op237_read_state6 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op229_read_state6 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op200_read_state6 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op192_read_state6 == 1'b1)));
end

assign ap_block_state7_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state9_pp0_stage0_iter5 = (((or_cond_i_i_reg_2171_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((or_cond_i_i_reg_2171_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((or_cond_i_i_reg_2171_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)));
end

always @ (*) begin
    ap_condition_589 = ((icmp_reg_2080 == 1'd0) & (tmp_51_reg_2085 == 1'd1) & (or_cond_i426_i_i_reg_2136_pp0_iter1_reg == 1'd1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_predicate_op192_read_state6 = ((icmp_reg_2080 == 1'd0) & (or_cond_i426_i_i_reg_2136_pp0_iter1_reg == 1'd1));
end

always @ (*) begin
    ap_predicate_op200_read_state6 = ((tmp_48_reg_2071 == 1'd1) & (icmp_reg_2080 == 1'd1) & (or_cond_i426_i_i_reg_2136_pp0_iter1_reg == 1'd1));
end

always @ (*) begin
    ap_predicate_op229_read_state6 = ((icmp_reg_2080 == 1'd0) & (or_cond_i426_i_i_reg_2136_pp0_iter1_reg == 1'd1));
end

always @ (*) begin
    ap_predicate_op237_read_state6 = ((tmp_48_reg_2071 == 1'd1) & (icmp_reg_2080 == 1'd1) & (or_cond_i426_i_i_reg_2136_pp0_iter1_reg == 1'd1));
end

always @ (*) begin
    ap_predicate_op266_read_state6 = ((icmp_reg_2080 == 1'd0) & (or_cond_i426_i_i_reg_2136_pp0_iter1_reg == 1'd1));
end

always @ (*) begin
    ap_predicate_op274_read_state6 = ((tmp_48_reg_2071 == 1'd1) & (icmp_reg_2080 == 1'd1) & (or_cond_i426_i_i_reg_2136_pp0_iter1_reg == 1'd1));
end

assign brmerge_fu_943_p2 = (tmp_59_fu_904_p2 | tmp_309_not_reg_2075);

assign col_assign_6_fu_938_p2 = (tmp_47_fu_603_p2 - x_fu_930_p3);

assign col_buf_0_val_0_0_fu_989_p3 = ((brmerge_reg_2145_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_0_val_3_q0 : tmp_64_fu_978_p5);

assign col_buf_0_val_1_0_fu_1007_p3 = ((brmerge_reg_2145_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_0_val_4_q0 : tmp_65_fu_996_p5);

assign col_buf_0_val_2_0_fu_1025_p3 = ((brmerge_reg_2145_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_0_val_5_q0 : tmp_66_fu_1014_p5);

assign col_buf_1_val_0_0_fu_1147_p3 = ((brmerge_reg_2145_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_1_val_3_q0 : tmp_70_fu_1136_p5);

assign col_buf_1_val_1_0_fu_1165_p3 = ((brmerge_reg_2145_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_1_val_4_q0 : tmp_71_fu_1154_p5);

assign col_buf_1_val_2_0_fu_1183_p3 = ((brmerge_reg_2145_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_1_val_5_q0 : tmp_72_fu_1172_p5);

assign col_buf_2_val_0_0_fu_1305_p3 = ((brmerge_reg_2145_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_2_val_3_q0 : tmp_76_fu_1294_p5);

assign col_buf_2_val_1_0_fu_1323_p3 = ((brmerge_reg_2145_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_2_val_4_q0 : tmp_77_fu_1312_p5);

assign col_buf_2_val_2_0_fu_1341_p3 = ((brmerge_reg_2145_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_2_val_5_q0 : tmp_78_fu_1330_p5);

assign exitcond389_i_i_fu_857_p2 = ((t_V_6_reg_570 == tmp_45_fu_593_p2) ? 1'b1 : 1'b0);

assign exitcond390_i_i_fu_613_p2 = ((t_V_reg_559 == tmp_46_fu_598_p2) ? 1'b1 : 1'b0);

assign i_V_fu_618_p2 = (t_V_reg_559 + 32'd1);

assign icmp3_fu_878_p2 = ((tmp_117_fu_868_p4 != 31'd0) ? 1'b1 : 1'b0);

assign icmp_fu_645_p2 = ((tmp_107_fu_635_p4 != 31'd0) ? 1'b1 : 1'b0);

assign j_V_fu_862_p2 = (t_V_6_reg_570 + 32'd1);

assign k_buf_0_val_3_address0 = tmp_63_fu_957_p1;

assign k_buf_0_val_4_address0 = tmp_63_fu_957_p1;

assign k_buf_0_val_5_address0 = tmp_63_fu_957_p1;

assign k_buf_1_val_3_address0 = tmp_63_fu_957_p1;

assign k_buf_1_val_4_address0 = tmp_63_fu_957_p1;

assign k_buf_1_val_5_address0 = tmp_63_fu_957_p1;

assign k_buf_2_val_3_address0 = tmp_63_fu_957_p1;

assign k_buf_2_val_4_address0 = tmp_63_fu_957_p1;

assign k_buf_2_val_5_address0 = tmp_63_fu_957_p1;

assign or_cond_i426_i_i_fu_909_p2 = (tmp_59_fu_904_p2 & rev9_fu_898_p2);

assign or_cond_i_i_fu_952_p2 = (icmp_reg_2080 & icmp3_fu_878_p2);

assign or_cond_i_i_i_0_1_fu_739_p2 = (tmp_367_0_1_fu_734_p2 & rev7_fu_728_p2);

assign or_cond_i_i_i_0_2_fu_785_p2 = (tmp_367_0_2_fu_780_p2 & rev8_fu_774_p2);

assign or_cond_i_i_i_fu_693_p2 = (tmp_55_fu_688_p2 & rev_fu_682_p2);

assign p_assign_17_0_1_fu_714_p2 = ($signed(32'd4294967294) + $signed(t_V_reg_559));

assign p_assign_17_0_2_fu_760_p2 = ($signed(32'd4294967293) + $signed(t_V_reg_559));

assign p_assign_18_0_1_fu_753_p3 = ((tmp_111_fu_745_p3[0:0] === 1'b1) ? 32'd0 : p_neg394_i_i_fu_608_p2);

assign p_assign_18_0_2_fu_799_p3 = ((tmp_113_fu_791_p3[0:0] === 1'b1) ? 32'd0 : p_neg394_i_i_fu_608_p2);

assign p_assign_1_fu_707_p3 = ((tmp_109_fu_699_p3[0:0] === 1'b1) ? 32'd0 : p_neg394_i_i_fu_608_p2);

assign p_assign_s_fu_923_p3 = ((tmp_119_fu_915_p3[0:0] === 1'b1) ? 32'd0 : tmp_47_fu_603_p2);

assign p_dst_data_stream_0_V_din = tmp_reg_2334;

assign p_dst_data_stream_1_V_din = tmp_61_reg_2339;

assign p_dst_data_stream_2_V_din = tmp_62_reg_2344;

assign p_neg394_i_i_fu_608_p2 = ($signed(p_src_rows_V) + $signed(32'd4294967295));

assign rev7_fu_728_p2 = (tmp_110_fu_720_p3 ^ 1'd1);

assign rev8_fu_774_p2 = (tmp_112_fu_766_p3 ^ 1'd1);

assign rev9_fu_898_p2 = (tmp_118_fu_890_p3 ^ 1'd1);

assign rev_fu_682_p2 = (tmp_108_fu_674_p3 ^ 1'd1);

assign row_assign_19_0_1_fu_831_p2 = (p_neg394_i_i_fu_608_p2 - y_3_0_1_fu_823_p3);

assign row_assign_19_0_2_fu_848_p2 = (p_neg394_i_i_fu_608_p2 - y_3_0_2_fu_840_p3);

assign row_assign_s_fu_814_p2 = (p_neg394_i_i_fu_608_p2 - y_3_fu_806_p3);

assign src_kernel_win_0_va_37_fu_1058_p3 = ((tmp_52_reg_2093[0:0] === 1'b1) ? tmp_67_fu_1047_p5 : col_buf_0_val_0_0_fu_989_p3);

assign src_kernel_win_0_va_38_fu_1076_p3 = ((tmp_52_reg_2093[0:0] === 1'b1) ? tmp_68_fu_1065_p5 : col_buf_0_val_1_0_fu_1007_p3);

assign src_kernel_win_0_va_39_fu_1094_p3 = ((tmp_52_reg_2093[0:0] === 1'b1) ? tmp_69_fu_1083_p5 : col_buf_0_val_2_0_fu_1025_p3);

assign src_kernel_win_1_va_37_fu_1216_p3 = ((tmp_52_reg_2093[0:0] === 1'b1) ? tmp_73_fu_1205_p5 : col_buf_1_val_0_0_fu_1147_p3);

assign src_kernel_win_1_va_38_fu_1234_p3 = ((tmp_52_reg_2093[0:0] === 1'b1) ? tmp_74_fu_1223_p5 : col_buf_1_val_1_0_fu_1165_p3);

assign src_kernel_win_1_va_39_fu_1252_p3 = ((tmp_52_reg_2093[0:0] === 1'b1) ? tmp_75_fu_1241_p5 : col_buf_1_val_2_0_fu_1183_p3);

assign src_kernel_win_2_va_40_fu_1374_p3 = ((tmp_52_reg_2093[0:0] === 1'b1) ? tmp_79_fu_1363_p5 : col_buf_2_val_0_0_fu_1305_p3);

assign src_kernel_win_2_va_41_fu_1392_p3 = ((tmp_52_reg_2093[0:0] === 1'b1) ? tmp_80_fu_1381_p5 : col_buf_2_val_1_0_fu_1323_p3);

assign src_kernel_win_2_va_42_fu_1410_p3 = ((tmp_52_reg_2093[0:0] === 1'b1) ? tmp_81_fu_1399_p5 : col_buf_2_val_2_0_fu_1341_p3);

assign temp_0_i_i_i_059_i_20_fu_1499_p3 = ((tmp_386_0_1_fu_1493_p2[0:0] === 1'b1) ? src_kernel_win_0_va_34_fu_242 : temp_0_i_i_i_059_i_39_fu_1488_p3);

assign temp_0_i_i_i_059_i_21_fu_1513_p3 = ((tmp_386_0_1_1_fu_1507_p2[0:0] === 1'b1) ? src_kernel_win_0_va_33_fu_238 : temp_0_i_i_i_059_i_20_fu_1499_p3);

assign temp_0_i_i_i_059_i_22_fu_1526_p3 = ((tmp_386_0_1_2_fu_1521_p2[0:0] === 1'b1) ? src_kernel_win_0_va_38_reg_2236 : temp_0_i_i_i_059_i_21_fu_1513_p3);

assign temp_0_i_i_i_059_i_23_fu_1682_p3 = ((tmp_386_0_2_fu_1677_p2[0:0] === 1'b1) ? src_kernel_win_0_va_32_fu_234 : temp_0_i_i_i_059_i_22_reg_2316);

assign temp_0_i_i_i_059_i_24_fu_1695_p3 = ((tmp_386_0_2_1_fu_1689_p2[0:0] === 1'b1) ? src_kernel_win_0_va_fu_230 : temp_0_i_i_i_059_i_23_fu_1682_p3);

assign temp_0_i_i_i_059_i_25_fu_1271_p3 = ((tmp_386_1_0_1_fu_1265_p2[0:0] === 1'b1) ? src_kernel_win_1_va_35_fu_270 : src_kernel_win_1_va_36_fu_274);

assign temp_0_i_i_i_059_i_26_fu_1539_p3 = ((tmp_386_1_0_2_reg_2282[0:0] === 1'b1) ? src_kernel_win_1_va_39_reg_2272 : temp_0_i_i_i_059_i_25_reg_2277);

assign temp_0_i_i_i_059_i_27_fu_1550_p3 = ((tmp_386_1_1_fu_1544_p2[0:0] === 1'b1) ? src_kernel_win_1_va_34_fu_266 : temp_0_i_i_i_059_i_26_fu_1539_p3);

assign temp_0_i_i_i_059_i_28_fu_1564_p3 = ((tmp_386_1_1_1_fu_1558_p2[0:0] === 1'b1) ? src_kernel_win_1_va_33_fu_262 : temp_0_i_i_i_059_i_27_fu_1550_p3);

assign temp_0_i_i_i_059_i_29_fu_1577_p3 = ((tmp_386_1_1_2_fu_1572_p2[0:0] === 1'b1) ? src_kernel_win_1_va_38_reg_2265 : temp_0_i_i_i_059_i_28_fu_1564_p3);

assign temp_0_i_i_i_059_i_30_fu_1726_p3 = ((tmp_386_1_2_fu_1721_p2[0:0] === 1'b1) ? src_kernel_win_1_va_32_fu_258 : temp_0_i_i_i_059_i_29_reg_2322);

assign temp_0_i_i_i_059_i_31_fu_1739_p3 = ((tmp_386_1_2_1_fu_1733_p2[0:0] === 1'b1) ? src_kernel_win_1_va_fu_254 : temp_0_i_i_i_059_i_30_fu_1726_p3);

assign temp_0_i_i_i_059_i_32_fu_1429_p3 = ((tmp_386_2_0_1_fu_1423_p2[0:0] === 1'b1) ? src_kernel_win_2_va_35_fu_294 : src_kernel_win_2_va_36_fu_298);

assign temp_0_i_i_i_059_i_33_fu_1590_p3 = ((tmp_386_2_0_2_reg_2311[0:0] === 1'b1) ? src_kernel_win_2_va_42_reg_2301 : temp_0_i_i_i_059_i_32_reg_2306);

assign temp_0_i_i_i_059_i_34_fu_1601_p3 = ((tmp_386_2_1_fu_1595_p2[0:0] === 1'b1) ? src_kernel_win_2_va_34_fu_290 : temp_0_i_i_i_059_i_33_fu_1590_p3);

assign temp_0_i_i_i_059_i_35_fu_1615_p3 = ((tmp_386_2_1_1_fu_1609_p2[0:0] === 1'b1) ? src_kernel_win_2_va_33_fu_286 : temp_0_i_i_i_059_i_34_fu_1601_p3);

assign temp_0_i_i_i_059_i_36_fu_1628_p3 = ((tmp_386_2_1_2_fu_1623_p2[0:0] === 1'b1) ? src_kernel_win_2_va_41_reg_2294 : temp_0_i_i_i_059_i_35_fu_1615_p3);

assign temp_0_i_i_i_059_i_37_fu_1770_p3 = ((tmp_386_2_2_fu_1765_p2[0:0] === 1'b1) ? src_kernel_win_2_va_32_fu_282 : temp_0_i_i_i_059_i_36_reg_2328);

assign temp_0_i_i_i_059_i_38_fu_1783_p3 = ((tmp_386_2_2_1_fu_1777_p2[0:0] === 1'b1) ? src_kernel_win_2_va_fu_278 : temp_0_i_i_i_059_i_37_fu_1770_p3);

assign temp_0_i_i_i_059_i_39_fu_1488_p3 = ((tmp_386_0_0_2_reg_2253[0:0] === 1'b1) ? src_kernel_win_0_va_39_reg_2243 : temp_0_i_i_i_059_i_s_reg_2248);

assign temp_0_i_i_i_059_i_s_fu_1113_p3 = ((tmp_386_0_0_1_fu_1107_p2[0:0] === 1'b1) ? src_kernel_win_0_va_35_fu_246 : src_kernel_win_0_va_36_fu_250);

assign tmp_107_fu_635_p4 = {{t_V_reg_559[31:1]}};

assign tmp_108_fu_674_p3 = tmp_53_fu_668_p2[32'd31];

assign tmp_109_fu_699_p3 = tmp_53_fu_668_p2[32'd31];

assign tmp_110_fu_720_p3 = p_assign_17_0_1_fu_714_p2[32'd31];

assign tmp_111_fu_745_p3 = p_assign_17_0_1_fu_714_p2[32'd31];

assign tmp_112_fu_766_p3 = p_assign_17_0_2_fu_760_p2[32'd31];

assign tmp_113_fu_791_p3 = p_assign_17_0_2_fu_760_p2[32'd31];

assign tmp_114_fu_819_p1 = row_assign_s_fu_814_p2[1:0];

assign tmp_115_fu_836_p1 = row_assign_19_0_1_fu_831_p2[1:0];

assign tmp_116_fu_853_p1 = row_assign_19_0_2_fu_848_p2[1:0];

assign tmp_117_fu_868_p4 = {{t_V_6_reg_570[31:1]}};

assign tmp_118_fu_890_p3 = ImagLoc_x_fu_884_p2[32'd31];

assign tmp_119_fu_915_p3 = ImagLoc_x_fu_884_p2[32'd31];

assign tmp_120_fu_948_p1 = col_assign_6_fu_938_p2[1:0];

assign tmp_309_not_fu_629_p2 = (tmp_48_fu_624_p2 ^ 1'd1);

assign tmp_340_0_2_fu_657_p2 = ((t_V_reg_559 == 32'd1) ? 1'b1 : 1'b0);

assign tmp_367_0_1_fu_734_p2 = (($signed(p_assign_17_0_1_fu_714_p2) < $signed(p_src_rows_V)) ? 1'b1 : 1'b0);

assign tmp_367_0_2_fu_780_p2 = (($signed(p_assign_17_0_2_fu_760_p2) < $signed(p_src_rows_V)) ? 1'b1 : 1'b0);

assign tmp_37_fu_581_p2 = (tmp_36_reg_548 + 2'd1);

assign tmp_386_0_0_1_fu_1107_p2 = ((src_kernel_win_0_va_35_fu_246 > src_kernel_win_0_va_36_fu_250) ? 1'b1 : 1'b0);

assign tmp_386_0_0_2_fu_1121_p2 = ((src_kernel_win_0_va_39_fu_1094_p3 > temp_0_i_i_i_059_i_s_fu_1113_p3) ? 1'b1 : 1'b0);

assign tmp_386_0_1_1_fu_1507_p2 = ((src_kernel_win_0_va_33_fu_238 > temp_0_i_i_i_059_i_20_fu_1499_p3) ? 1'b1 : 1'b0);

assign tmp_386_0_1_2_fu_1521_p2 = ((src_kernel_win_0_va_38_reg_2236 > temp_0_i_i_i_059_i_21_fu_1513_p3) ? 1'b1 : 1'b0);

assign tmp_386_0_1_fu_1493_p2 = ((src_kernel_win_0_va_34_fu_242 > temp_0_i_i_i_059_i_39_fu_1488_p3) ? 1'b1 : 1'b0);

assign tmp_386_0_2_1_fu_1689_p2 = ((src_kernel_win_0_va_fu_230 > temp_0_i_i_i_059_i_23_fu_1682_p3) ? 1'b1 : 1'b0);

assign tmp_386_0_2_2_fu_1703_p2 = ((src_kernel_win_0_va_37_reg_2229_pp0_iter3_reg > temp_0_i_i_i_059_i_24_fu_1695_p3) ? 1'b1 : 1'b0);

assign tmp_386_0_2_fu_1677_p2 = ((src_kernel_win_0_va_32_fu_234 > temp_0_i_i_i_059_i_22_reg_2316) ? 1'b1 : 1'b0);

assign tmp_386_1_0_1_fu_1265_p2 = ((src_kernel_win_1_va_35_fu_270 > src_kernel_win_1_va_36_fu_274) ? 1'b1 : 1'b0);

assign tmp_386_1_0_2_fu_1279_p2 = ((src_kernel_win_1_va_39_fu_1252_p3 > temp_0_i_i_i_059_i_25_fu_1271_p3) ? 1'b1 : 1'b0);

assign tmp_386_1_1_1_fu_1558_p2 = ((src_kernel_win_1_va_33_fu_262 > temp_0_i_i_i_059_i_27_fu_1550_p3) ? 1'b1 : 1'b0);

assign tmp_386_1_1_2_fu_1572_p2 = ((src_kernel_win_1_va_38_reg_2265 > temp_0_i_i_i_059_i_28_fu_1564_p3) ? 1'b1 : 1'b0);

assign tmp_386_1_1_fu_1544_p2 = ((src_kernel_win_1_va_34_fu_266 > temp_0_i_i_i_059_i_26_fu_1539_p3) ? 1'b1 : 1'b0);

assign tmp_386_1_2_1_fu_1733_p2 = ((src_kernel_win_1_va_fu_254 > temp_0_i_i_i_059_i_30_fu_1726_p3) ? 1'b1 : 1'b0);

assign tmp_386_1_2_2_fu_1747_p2 = ((src_kernel_win_1_va_37_reg_2258_pp0_iter3_reg > temp_0_i_i_i_059_i_31_fu_1739_p3) ? 1'b1 : 1'b0);

assign tmp_386_1_2_fu_1721_p2 = ((src_kernel_win_1_va_32_fu_258 > temp_0_i_i_i_059_i_29_reg_2322) ? 1'b1 : 1'b0);

assign tmp_386_2_0_1_fu_1423_p2 = ((src_kernel_win_2_va_35_fu_294 > src_kernel_win_2_va_36_fu_298) ? 1'b1 : 1'b0);

assign tmp_386_2_0_2_fu_1437_p2 = ((src_kernel_win_2_va_42_fu_1410_p3 > temp_0_i_i_i_059_i_32_fu_1429_p3) ? 1'b1 : 1'b0);

assign tmp_386_2_1_1_fu_1609_p2 = ((src_kernel_win_2_va_33_fu_286 > temp_0_i_i_i_059_i_34_fu_1601_p3) ? 1'b1 : 1'b0);

assign tmp_386_2_1_2_fu_1623_p2 = ((src_kernel_win_2_va_41_reg_2294 > temp_0_i_i_i_059_i_35_fu_1615_p3) ? 1'b1 : 1'b0);

assign tmp_386_2_1_fu_1595_p2 = ((src_kernel_win_2_va_34_fu_290 > temp_0_i_i_i_059_i_33_fu_1590_p3) ? 1'b1 : 1'b0);

assign tmp_386_2_2_1_fu_1777_p2 = ((src_kernel_win_2_va_fu_278 > temp_0_i_i_i_059_i_37_fu_1770_p3) ? 1'b1 : 1'b0);

assign tmp_386_2_2_2_fu_1791_p2 = ((src_kernel_win_2_va_40_reg_2287_pp0_iter3_reg > temp_0_i_i_i_059_i_38_fu_1783_p3) ? 1'b1 : 1'b0);

assign tmp_386_2_2_fu_1765_p2 = ((src_kernel_win_2_va_32_fu_282 > temp_0_i_i_i_059_i_36_reg_2328) ? 1'b1 : 1'b0);

assign tmp_38_fu_587_p2 = ((tmp_36_reg_548 == 2'd2) ? 1'b1 : 1'b0);

assign tmp_45_fu_593_p2 = (p_src_cols_V + 32'd2);

assign tmp_46_fu_598_p2 = (p_src_rows_V + 32'd2);

assign tmp_47_fu_603_p2 = ($signed(p_src_cols_V) + $signed(32'd4294967295));

assign tmp_48_fu_624_p2 = ((t_V_reg_559 < p_src_rows_V) ? 1'b1 : 1'b0);

assign tmp_51_fu_651_p2 = ((t_V_reg_559 == 32'd0) ? 1'b1 : 1'b0);

assign tmp_52_fu_663_p2 = ((t_V_reg_559 > p_src_rows_V) ? 1'b1 : 1'b0);

assign tmp_53_fu_668_p2 = ($signed(32'd4294967295) + $signed(t_V_reg_559));

assign tmp_55_fu_688_p2 = (($signed(tmp_53_fu_668_p2) < $signed(p_src_rows_V)) ? 1'b1 : 1'b0);

assign tmp_59_fu_904_p2 = (($signed(ImagLoc_x_fu_884_p2) < $signed(p_src_cols_V)) ? 1'b1 : 1'b0);

assign tmp_61_fu_1752_p3 = ((tmp_386_1_2_2_fu_1747_p2[0:0] === 1'b1) ? src_kernel_win_1_va_37_reg_2258_pp0_iter3_reg : temp_0_i_i_i_059_i_31_fu_1739_p3);

assign tmp_62_fu_1796_p3 = ((tmp_386_2_2_2_fu_1791_p2[0:0] === 1'b1) ? src_kernel_win_2_va_40_reg_2287_pp0_iter3_reg : temp_0_i_i_i_059_i_38_fu_1783_p3);

assign tmp_63_fu_957_p1 = x_reg_2140;

assign tmp_fu_1708_p3 = ((tmp_386_0_2_2_fu_1703_p2[0:0] === 1'b1) ? src_kernel_win_0_va_37_reg_2229_pp0_iter3_reg : temp_0_i_i_i_059_i_24_fu_1695_p3);

assign x_fu_930_p3 = ((or_cond_i426_i_i_fu_909_p2[0:0] === 1'b1) ? ImagLoc_x_fu_884_p2 : p_assign_s_fu_923_p3);

assign y_3_0_1_fu_823_p3 = ((or_cond_i_i_i_0_1_fu_739_p2[0:0] === 1'b1) ? p_assign_17_0_1_fu_714_p2 : p_assign_18_0_1_fu_753_p3);

assign y_3_0_2_fu_840_p3 = ((or_cond_i_i_i_0_2_fu_785_p2[0:0] === 1'b1) ? p_assign_17_0_2_fu_760_p2 : p_assign_18_0_2_fu_799_p3);

assign y_3_fu_806_p3 = ((or_cond_i_i_i_fu_693_p2[0:0] === 1'b1) ? tmp_53_fu_668_p2 : p_assign_1_fu_707_p3);

endmodule //Dilate
