// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Filter2D (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_src_rows_V_read,
        p_src_cols_V_read,
        p_src_data_stream_0_V_dout,
        p_src_data_stream_0_V_empty_n,
        p_src_data_stream_0_V_read,
        p_src_data_stream_1_V_dout,
        p_src_data_stream_1_V_empty_n,
        p_src_data_stream_1_V_read,
        p_src_data_stream_2_V_dout,
        p_src_data_stream_2_V_empty_n,
        p_src_data_stream_2_V_read,
        p_dst_data_stream_0_V_din,
        p_dst_data_stream_0_V_full_n,
        p_dst_data_stream_0_V_write,
        p_dst_data_stream_1_V_din,
        p_dst_data_stream_1_V_full_n,
        p_dst_data_stream_1_V_write,
        p_dst_data_stream_2_V_din,
        p_dst_data_stream_2_V_full_n,
        p_dst_data_stream_2_V_write
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_pp0_stage0 = 6'd16;
parameter    ap_ST_fsm_state10 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] p_src_rows_V_read;
input  [31:0] p_src_cols_V_read;
input  [7:0] p_src_data_stream_0_V_dout;
input   p_src_data_stream_0_V_empty_n;
output   p_src_data_stream_0_V_read;
input  [7:0] p_src_data_stream_1_V_dout;
input   p_src_data_stream_1_V_empty_n;
output   p_src_data_stream_1_V_read;
input  [7:0] p_src_data_stream_2_V_dout;
input   p_src_data_stream_2_V_empty_n;
output   p_src_data_stream_2_V_read;
output  [7:0] p_dst_data_stream_0_V_din;
input   p_dst_data_stream_0_V_full_n;
output   p_dst_data_stream_0_V_write;
output  [7:0] p_dst_data_stream_1_V_din;
input   p_dst_data_stream_1_V_full_n;
output   p_dst_data_stream_1_V_write;
output  [7:0] p_dst_data_stream_2_V_din;
input   p_dst_data_stream_2_V_full_n;
output   p_dst_data_stream_2_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_src_data_stream_0_V_read;
reg p_src_data_stream_1_V_read;
reg p_src_data_stream_2_V_read;
reg p_dst_data_stream_0_V_write;
reg p_dst_data_stream_1_V_write;
reg p_dst_data_stream_2_V_write;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    p_src_data_stream_0_V_blk_n;
reg    ap_enable_reg_pp0_iter2;
wire    ap_block_pp0_stage0;
reg   [0:0] exitcond389_i_reg_2684;
reg   [0:0] exitcond389_i_reg_2684_pp0_iter1_reg;
reg   [0:0] or_cond_i427_i_reg_2693;
reg   [0:0] or_cond_i427_i_reg_2693_pp0_iter1_reg;
reg   [0:0] icmp_reg_2617;
reg   [0:0] tmp_8_reg_2612;
reg    p_src_data_stream_1_V_blk_n;
reg    p_src_data_stream_2_V_blk_n;
reg    p_dst_data_stream_0_V_blk_n;
reg    ap_enable_reg_pp0_iter4;
reg   [0:0] or_cond_i_reg_2728;
reg   [0:0] or_cond_i_reg_2728_pp0_iter3_reg;
reg    p_dst_data_stream_1_V_blk_n;
reg    p_dst_data_stream_2_V_blk_n;
reg   [31:0] t_V_4_reg_608;
wire   [1:0] tmp_3_fu_619_p2;
wire    ap_CS_fsm_state2;
wire   [31:0] tmp_s_fu_631_p2;
wire   [0:0] tmp_4_fu_625_p2;
wire   [31:0] tmp_5_fu_636_p2;
wire   [31:0] p_neg394_i_fu_641_p2;
wire   [31:0] tmp_6_fu_646_p2;
wire   [31:0] tmp_7_fu_656_p2;
wire   [31:0] tmp_80_2_fu_667_p2;
wire   [31:0] i_V_fu_678_p2;
reg   [31:0] i_V_reg_2607;
wire    ap_CS_fsm_state3;
wire   [0:0] tmp_8_fu_684_p2;
wire   [0:0] exitcond390_i_fu_673_p2;
wire   [0:0] icmp_fu_699_p2;
wire   [0:0] tmp_1_fu_705_p2;
reg   [0:0] tmp_1_reg_2622;
wire   [0:0] tmp_128_0_1_fu_711_p2;
reg   [0:0] tmp_128_0_1_reg_2626;
wire   [0:0] tmp_10_fu_717_p2;
reg   [0:0] tmp_10_reg_2630;
wire   [31:0] y_1_fu_919_p3;
reg   [31:0] y_1_reg_2643;
wire   [31:0] y_1_0_1_fu_935_p3;
reg   [31:0] y_1_0_1_reg_2648;
wire   [31:0] y_1_0_2_fu_951_p3;
reg   [31:0] y_1_0_2_reg_2653;
wire   [0:0] tmp_84_0_0_not_fu_959_p2;
reg   [0:0] tmp_84_0_0_not_reg_2658;
wire    ap_CS_fsm_state4;
wire   [1:0] tmp_48_fu_968_p1;
reg   [1:0] tmp_48_reg_2663;
wire   [1:0] tmp_50_fu_976_p1;
reg   [1:0] tmp_50_reg_2670;
wire   [1:0] tmp_57_fu_984_p1;
reg   [1:0] tmp_57_reg_2677;
wire   [0:0] exitcond389_i_fu_988_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state5_pp0_stage0_iter0;
wire    ap_block_state6_pp0_stage0_iter1;
reg    ap_predicate_op228_read_state7;
reg    ap_predicate_op240_read_state7;
reg    ap_predicate_op270_read_state7;
reg    ap_predicate_op282_read_state7;
reg    ap_predicate_op309_read_state7;
reg    ap_predicate_op318_read_state7;
reg    ap_block_state7_pp0_stage0_iter2;
wire    ap_block_state8_pp0_stage0_iter3;
reg    ap_block_state9_pp0_stage0_iter4;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] exitcond389_i_reg_2684_pp0_iter2_reg;
wire   [31:0] j_V_fu_993_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] or_cond_i427_i_fu_1040_p2;
wire   [31:0] x_fu_1086_p3;
reg   [31:0] x_reg_2697;
wire   [0:0] brmerge_fu_1099_p2;
reg   [0:0] brmerge_reg_2702;
reg   [0:0] brmerge_reg_2702_pp0_iter1_reg;
wire   [1:0] tmp_62_fu_1104_p1;
reg   [1:0] tmp_62_reg_2715;
reg   [1:0] tmp_62_reg_2715_pp0_iter1_reg;
wire   [0:0] or_cond_i_fu_1108_p2;
reg   [0:0] or_cond_i_reg_2728_pp0_iter1_reg;
reg   [0:0] or_cond_i_reg_2728_pp0_iter2_reg;
reg   [10:0] k_buf_0_val_3_addr_reg_2732;
reg   [10:0] k_buf_0_val_4_addr_reg_2738;
reg   [10:0] k_buf_0_val_5_addr_reg_2744;
reg   [10:0] k_buf_1_val_3_addr_reg_2750;
reg   [10:0] k_buf_1_val_4_addr_reg_2756;
reg   [10:0] k_buf_1_val_5_addr_reg_2762;
reg   [10:0] k_buf_2_val_3_addr_reg_2768;
reg   [10:0] k_buf_2_val_4_addr_reg_2774;
reg   [10:0] k_buf_2_val_5_addr_reg_2780;
wire   [7:0] src_kernel_win_0_va_6_fu_1256_p3;
reg   [7:0] src_kernel_win_0_va_6_reg_2786;
wire   [7:0] src_kernel_win_0_va_7_fu_1274_p3;
reg   [7:0] src_kernel_win_0_va_7_reg_2793;
wire   [7:0] src_kernel_win_0_va_8_fu_1292_p3;
reg   [7:0] src_kernel_win_0_va_8_reg_2800;
wire   [7:0] src_kernel_win_1_va_6_fu_1421_p3;
reg   [7:0] src_kernel_win_1_va_6_reg_2806;
wire   [7:0] src_kernel_win_1_va_7_fu_1439_p3;
reg   [7:0] src_kernel_win_1_va_7_reg_2813;
wire   [7:0] src_kernel_win_1_va_8_fu_1457_p3;
reg   [7:0] src_kernel_win_1_va_8_reg_2820;
wire   [7:0] src_kernel_win_2_va_9_fu_1568_p3;
reg   [7:0] src_kernel_win_2_va_9_reg_2826;
wire   [7:0] src_kernel_win_2_va_10_fu_1586_p3;
reg   [7:0] src_kernel_win_2_va_10_reg_2833;
wire   [7:0] src_kernel_win_2_va_11_fu_1604_p3;
reg   [7:0] src_kernel_win_2_va_11_reg_2840;
reg   [0:0] isneg_reg_2846;
wire   [7:0] p_Val2_21_fu_1757_p2;
reg   [7:0] p_Val2_21_reg_2852;
wire   [0:0] not_i_i_i_fu_1773_p2;
reg   [0:0] not_i_i_i_reg_2857;
reg   [0:0] isneg_1_reg_2862;
wire   [7:0] p_Val2_24_fu_1925_p2;
reg   [7:0] p_Val2_24_reg_2868;
wire   [0:0] not_i_i_i1_fu_1941_p2;
reg   [0:0] not_i_i_i1_reg_2873;
reg   [0:0] isneg_2_reg_2878;
wire   [7:0] p_Val2_26_fu_2093_p2;
reg   [7:0] p_Val2_26_reg_2884;
wire   [0:0] not_i_i_i2_fu_2109_p2;
reg   [0:0] not_i_i_i2_reg_2889;
reg    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter3;
reg    ap_condition_pp0_exit_iter2_state7;
wire   [10:0] k_buf_0_val_3_address0;
reg    k_buf_0_val_3_ce0;
wire   [7:0] k_buf_0_val_3_q0;
reg    k_buf_0_val_3_ce1;
reg    k_buf_0_val_3_we1;
wire   [10:0] k_buf_0_val_4_address0;
reg    k_buf_0_val_4_ce0;
wire   [7:0] k_buf_0_val_4_q0;
reg    k_buf_0_val_4_ce1;
reg    k_buf_0_val_4_we1;
reg   [7:0] k_buf_0_val_4_d1;
wire   [10:0] k_buf_0_val_5_address0;
reg    k_buf_0_val_5_ce0;
wire   [7:0] k_buf_0_val_5_q0;
reg    k_buf_0_val_5_ce1;
reg    k_buf_0_val_5_we1;
reg   [7:0] k_buf_0_val_5_d1;
wire   [10:0] k_buf_1_val_3_address0;
reg    k_buf_1_val_3_ce0;
wire   [7:0] k_buf_1_val_3_q0;
reg    k_buf_1_val_3_ce1;
reg    k_buf_1_val_3_we1;
wire   [10:0] k_buf_1_val_4_address0;
reg    k_buf_1_val_4_ce0;
wire   [7:0] k_buf_1_val_4_q0;
reg    k_buf_1_val_4_ce1;
reg    k_buf_1_val_4_we1;
reg   [7:0] k_buf_1_val_4_d1;
wire   [10:0] k_buf_1_val_5_address0;
reg    k_buf_1_val_5_ce0;
wire   [7:0] k_buf_1_val_5_q0;
reg    k_buf_1_val_5_ce1;
reg    k_buf_1_val_5_we1;
reg   [7:0] k_buf_1_val_5_d1;
wire   [10:0] k_buf_2_val_3_address0;
reg    k_buf_2_val_3_ce0;
wire   [7:0] k_buf_2_val_3_q0;
reg    k_buf_2_val_3_ce1;
reg    k_buf_2_val_3_we1;
wire   [10:0] k_buf_2_val_4_address0;
reg    k_buf_2_val_4_ce0;
wire   [7:0] k_buf_2_val_4_q0;
reg    k_buf_2_val_4_ce1;
reg    k_buf_2_val_4_we1;
reg   [7:0] k_buf_2_val_4_d1;
wire   [10:0] k_buf_2_val_5_address0;
reg    k_buf_2_val_5_ce0;
wire   [7:0] k_buf_2_val_5_q0;
reg    k_buf_2_val_5_ce1;
reg    k_buf_2_val_5_we1;
reg   [7:0] k_buf_2_val_5_d1;
reg   [1:0] tmp_2_reg_586;
reg   [31:0] t_V_reg_597;
wire    ap_CS_fsm_state10;
wire   [63:0] tmp_17_fu_1113_p1;
reg    ap_block_pp0_stage0_01001;
reg   [7:0] src_kernel_win_0_va_fu_232;
reg   [7:0] src_kernel_win_0_va_1_fu_236;
reg   [7:0] src_kernel_win_0_va_2_fu_240;
reg   [7:0] src_kernel_win_0_va_3_fu_244;
reg   [7:0] src_kernel_win_0_va_4_fu_248;
reg   [7:0] src_kernel_win_0_va_5_fu_252;
reg   [7:0] src_kernel_win_1_va_fu_256;
reg   [7:0] src_kernel_win_1_va_1_fu_260;
reg   [7:0] src_kernel_win_1_va_2_fu_264;
reg   [7:0] src_kernel_win_1_va_3_fu_268;
reg   [7:0] src_kernel_win_1_va_4_fu_272;
reg   [7:0] src_kernel_win_1_va_5_fu_276;
reg   [7:0] src_kernel_win_2_va_fu_280;
reg   [7:0] src_kernel_win_2_va_1_fu_284;
reg   [7:0] src_kernel_win_2_va_2_fu_288;
reg   [7:0] src_kernel_win_2_va_3_fu_292;
reg   [7:0] src_kernel_win_2_va_4_fu_296;
reg   [7:0] src_kernel_win_2_va_5_fu_300;
reg   [7:0] right_border_buf_0_s_fu_304;
wire   [7:0] col_buf_0_val_0_0_fu_1163_p3;
reg   [7:0] right_border_buf_0_1_fu_308;
reg   [7:0] right_border_buf_2_s_fu_312;
reg   [7:0] right_border_buf_0_2_fu_316;
wire   [7:0] col_buf_0_val_1_0_fu_1181_p3;
reg   [7:0] right_border_buf_0_3_fu_320;
reg   [7:0] right_border_buf_2_1_fu_324;
wire   [7:0] col_buf_2_val_2_0_fu_1520_p3;
reg   [7:0] right_border_buf_0_4_fu_328;
wire   [7:0] col_buf_0_val_2_0_fu_1199_p3;
reg   [7:0] right_border_buf_0_5_fu_332;
reg   [7:0] right_border_buf_2_2_fu_336;
reg   [7:0] right_border_buf_1_s_fu_340;
wire   [7:0] col_buf_1_val_0_0_fu_1328_p3;
reg   [7:0] right_border_buf_1_1_fu_344;
reg   [7:0] right_border_buf_2_3_fu_348;
wire   [7:0] col_buf_2_val_1_0_fu_1502_p3;
reg   [7:0] right_border_buf_1_2_fu_352;
wire   [7:0] col_buf_1_val_1_0_fu_1346_p3;
reg   [7:0] right_border_buf_1_3_fu_356;
reg   [7:0] right_border_buf_2_4_fu_360;
reg   [7:0] right_border_buf_1_4_fu_364;
wire   [7:0] col_buf_1_val_2_0_fu_1364_p3;
reg   [7:0] right_border_buf_1_5_fu_368;
reg   [7:0] right_border_buf_2_5_fu_372;
wire   [7:0] col_buf_2_val_0_0_fu_1484_p3;
wire   [31:0] tmp_fu_651_p2;
wire   [31:0] tmp_33_fu_662_p2;
wire   [30:0] tmp_34_fu_689_p4;
wire   [31:0] tmp_11_fu_722_p2;
wire   [0:0] tmp_35_fu_728_p3;
wire   [0:0] tmp_12_fu_742_p2;
wire   [0:0] rev_fu_736_p2;
wire   [0:0] tmp_36_fu_753_p3;
wire   [31:0] p_assign_7_fu_761_p2;
wire   [31:0] p_p2_i_i_fu_767_p3;
wire   [31:0] p_assign_6_0_1_fu_785_p2;
wire   [0:0] tmp_38_fu_791_p3;
wire   [0:0] tmp_154_0_1_fu_805_p2;
wire   [0:0] rev1_fu_799_p2;
wire   [0:0] tmp_45_fu_816_p3;
wire   [31:0] p_assign_7_0_1_fu_824_p2;
wire   [31:0] p_p2_i_i_0_1_fu_830_p3;
wire   [31:0] p_assign_6_0_2_fu_848_p2;
wire   [0:0] tmp_46_fu_854_p3;
wire   [0:0] tmp_154_0_2_fu_868_p2;
wire   [0:0] rev2_fu_862_p2;
wire   [0:0] tmp_47_fu_879_p3;
wire   [31:0] p_assign_7_0_2_fu_887_p2;
wire   [31:0] p_p2_i_i_0_2_fu_893_p3;
wire   [0:0] tmp_14_fu_775_p2;
wire   [31:0] p_assign_8_fu_780_p2;
wire   [0:0] or_cond_i_i_fu_747_p2;
wire   [31:0] p_p2_i_i_0_p_assign_8_fu_911_p3;
wire   [0:0] tmp_164_0_1_fu_838_p2;
wire   [31:0] p_assign_8_0_1_fu_843_p2;
wire   [0:0] or_cond_i_i_0_1_fu_810_p2;
wire   [31:0] p_p2_i_i_0_1_p_assign_fu_927_p3;
wire   [0:0] tmp_164_0_2_fu_901_p2;
wire   [31:0] p_assign_8_0_2_fu_906_p2;
wire   [0:0] or_cond_i_i_0_2_fu_873_p2;
wire   [31:0] p_p2_i_i_0_2_p_assign_fu_943_p3;
wire   [31:0] row_assign_9_fu_964_p2;
wire   [31:0] row_assign_9_0_1_fu_972_p2;
wire   [31:0] row_assign_9_0_2_fu_980_p2;
wire   [30:0] tmp_58_fu_999_p4;
wire   [31:0] ImagLoc_x_fu_1015_p2;
wire   [0:0] tmp_59_fu_1021_p3;
wire   [0:0] tmp_15_fu_1035_p2;
wire   [0:0] rev3_fu_1029_p2;
wire   [0:0] tmp_60_fu_1046_p3;
wire   [31:0] p_assign_1_fu_1054_p2;
wire   [31:0] p_p2_i429_i_fu_1060_p3;
wire   [0:0] tmp_16_fu_1068_p2;
wire   [31:0] p_assign_2_fu_1073_p2;
wire   [31:0] p_p2_i429_i_p_assign_2_fu_1078_p3;
wire   [31:0] col_assign_2_fu_1094_p2;
wire   [0:0] icmp1_fu_1009_p2;
wire   [7:0] tmp_18_fu_1152_p5;
wire   [7:0] tmp_19_fu_1170_p5;
wire   [7:0] tmp_20_fu_1188_p5;
wire   [7:0] tmp_21_fu_1245_p5;
wire   [7:0] tmp_22_fu_1263_p5;
wire   [7:0] tmp_23_fu_1281_p5;
wire   [7:0] tmp_25_fu_1317_p5;
wire   [7:0] tmp_26_fu_1335_p5;
wire   [7:0] tmp_27_fu_1353_p5;
wire   [7:0] tmp_28_fu_1410_p5;
wire   [7:0] tmp_29_fu_1428_p5;
wire   [7:0] tmp_30_fu_1446_p5;
wire   [7:0] tmp_32_fu_1473_p5;
wire   [7:0] tmp_37_fu_1491_p5;
wire   [7:0] tmp_39_fu_1509_p5;
wire   [7:0] tmp_40_fu_1557_p5;
wire   [7:0] tmp_41_fu_1575_p5;
wire   [7:0] tmp_42_fu_1593_p5;
wire   [8:0] tmp_172_0_0_2_cast_fu_1624_p1;
wire   [8:0] OP1_V_0_0_cast_fu_1620_p1;
wire  signed [8:0] p_Val2_8_0_0_2_fu_1627_p2;
wire   [8:0] p_shl_fu_1637_p3;
wire   [9:0] p_shl_cast_fu_1645_p1;
wire  signed [9:0] r_V_2_0_1_fu_1649_p2;
wire   [8:0] r_V_2_0_1_2_fu_1667_p3;
wire   [8:0] OP1_V_0_2_cast_fu_1683_p1;
wire  signed [8:0] r_V_2_0_2_fu_1687_p2;
wire  signed [10:0] tmp_172_0_2_cast_fu_1693_p1;
wire  signed [10:0] tmp_172_0_1_cast_fu_1655_p1;
wire   [9:0] tmp_172_0_2_2_cast_c_fu_1701_p1;
wire  signed [9:0] p_Val2_8_0_0_2_cas_fu_1633_p1;
wire   [9:0] tmp23_fu_1710_p2;
wire   [10:0] tmp_172_0_1_cast_67_fu_1674_p1;
wire  signed [10:0] tmp23_cast_fu_1716_p1;
wire   [10:0] tmp21_fu_1704_p2;
wire   [10:0] tmp22_fu_1720_p2;
wire   [10:0] p_Val2_20_fu_1726_p2;
wire   [7:0] tmp_66_fu_1663_p1;
wire   [7:0] tmp_65_fu_1659_p1;
wire   [7:0] tmp_68_fu_1697_p1;
wire   [7:0] tmp_67_fu_1678_p2;
wire   [7:0] tmp26_fu_1746_p2;
wire   [7:0] tmp24_fu_1740_p2;
wire   [7:0] tmp25_fu_1751_p2;
wire   [2:0] tmp_24_fu_1763_p4;
wire   [8:0] tmp_172_1_0_2_cast_fu_1792_p1;
wire   [8:0] OP1_V_1_0_cast_fu_1788_p1;
wire  signed [8:0] p_Val2_8_1_0_2_fu_1795_p2;
wire   [8:0] p_shl1_fu_1805_p3;
wire   [9:0] p_shl1_cast_fu_1813_p1;
wire  signed [9:0] r_V_2_1_1_fu_1817_p2;
wire   [8:0] r_V_2_1_1_2_fu_1835_p3;
wire   [8:0] OP1_V_1_2_cast_fu_1851_p1;
wire  signed [8:0] r_V_2_1_2_fu_1855_p2;
wire  signed [10:0] tmp_172_1_2_cast_fu_1861_p1;
wire  signed [10:0] tmp_172_1_1_cast_fu_1823_p1;
wire   [9:0] tmp_172_1_2_2_cast_c_fu_1869_p1;
wire  signed [9:0] p_Val2_8_1_0_2_cas_fu_1801_p1;
wire   [9:0] tmp31_fu_1878_p2;
wire   [10:0] tmp_172_1_1_cast_68_fu_1842_p1;
wire  signed [10:0] tmp31_cast_fu_1884_p1;
wire   [10:0] tmp29_fu_1872_p2;
wire   [10:0] tmp30_fu_1888_p2;
wire   [10:0] p_Val2_23_fu_1894_p2;
wire   [7:0] tmp_74_fu_1831_p1;
wire   [7:0] tmp_73_fu_1827_p1;
wire   [7:0] tmp_76_fu_1865_p1;
wire   [7:0] tmp_75_fu_1846_p2;
wire   [7:0] tmp34_fu_1914_p2;
wire   [7:0] tmp32_fu_1908_p2;
wire   [7:0] tmp33_fu_1919_p2;
wire   [2:0] tmp_31_fu_1931_p4;
wire   [8:0] tmp_172_2_0_2_cast_fu_1960_p1;
wire   [8:0] OP1_V_2_0_cast_fu_1956_p1;
wire  signed [8:0] p_Val2_8_2_0_2_fu_1963_p2;
wire   [8:0] p_shl2_fu_1973_p3;
wire   [9:0] p_shl2_cast_fu_1981_p1;
wire  signed [9:0] r_V_2_2_1_fu_1985_p2;
wire   [8:0] r_V_2_2_1_2_fu_2003_p3;
wire   [8:0] OP1_V_2_2_cast_fu_2019_p1;
wire  signed [8:0] r_V_2_2_2_fu_2023_p2;
wire  signed [10:0] tmp_172_2_2_cast_fu_2029_p1;
wire  signed [10:0] tmp_172_2_1_cast_fu_1991_p1;
wire   [9:0] tmp_172_2_2_2_cast_c_fu_2037_p1;
wire  signed [9:0] p_Val2_8_2_0_2_cas_fu_1969_p1;
wire   [9:0] tmp39_fu_2046_p2;
wire   [10:0] tmp_172_2_1_cast_69_fu_2010_p1;
wire  signed [10:0] tmp39_cast_fu_2052_p1;
wire   [10:0] tmp37_fu_2040_p2;
wire   [10:0] tmp38_fu_2056_p2;
wire   [10:0] p_Val2_s_fu_2062_p2;
wire   [7:0] tmp_82_fu_1999_p1;
wire   [7:0] tmp_81_fu_1995_p1;
wire   [7:0] tmp_84_fu_2033_p1;
wire   [7:0] tmp_83_fu_2014_p2;
wire   [7:0] tmp42_fu_2082_p2;
wire   [7:0] tmp40_fu_2076_p2;
wire   [7:0] tmp41_fu_2087_p2;
wire   [2:0] tmp_43_fu_2099_p4;
wire   [0:0] tmp_8_i_i_fu_2223_p2;
wire   [0:0] overflow_fu_2228_p2;
wire   [0:0] tmp_i_i_fu_2241_p2;
wire   [7:0] p_mux_i_i_cast_fu_2233_p3;
wire   [0:0] tmp_8_i_i1_fu_2254_p2;
wire   [0:0] overflow_3_fu_2259_p2;
wire   [0:0] tmp_i_i2_fu_2272_p2;
wire   [7:0] p_mux_i_i30_cast_fu_2264_p3;
wire   [0:0] tmp_8_i_i2_fu_2285_p2;
wire   [0:0] overflow_4_fu_2290_p2;
wire   [0:0] tmp_i_i3_fu_2303_p2;
wire   [7:0] p_mux_i_i39_cast_fu_2295_p3;
reg   [5:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_602;
reg    ap_condition_596;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
end

Filter2D_k_buf_0_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_0_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_3_address0),
    .ce0(k_buf_0_val_3_ce0),
    .q0(k_buf_0_val_3_q0),
    .address1(k_buf_0_val_3_addr_reg_2732),
    .ce1(k_buf_0_val_3_ce1),
    .we1(k_buf_0_val_3_we1),
    .d1(p_src_data_stream_0_V_dout)
);

Filter2D_k_buf_0_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_0_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_4_address0),
    .ce0(k_buf_0_val_4_ce0),
    .q0(k_buf_0_val_4_q0),
    .address1(k_buf_0_val_4_addr_reg_2738),
    .ce1(k_buf_0_val_4_ce1),
    .we1(k_buf_0_val_4_we1),
    .d1(k_buf_0_val_4_d1)
);

Filter2D_k_buf_0_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_0_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_5_address0),
    .ce0(k_buf_0_val_5_ce0),
    .q0(k_buf_0_val_5_q0),
    .address1(k_buf_0_val_5_addr_reg_2744),
    .ce1(k_buf_0_val_5_ce1),
    .we1(k_buf_0_val_5_we1),
    .d1(k_buf_0_val_5_d1)
);

Filter2D_k_buf_0_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_1_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_1_val_3_address0),
    .ce0(k_buf_1_val_3_ce0),
    .q0(k_buf_1_val_3_q0),
    .address1(k_buf_1_val_3_addr_reg_2750),
    .ce1(k_buf_1_val_3_ce1),
    .we1(k_buf_1_val_3_we1),
    .d1(p_src_data_stream_1_V_dout)
);

Filter2D_k_buf_0_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_1_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_1_val_4_address0),
    .ce0(k_buf_1_val_4_ce0),
    .q0(k_buf_1_val_4_q0),
    .address1(k_buf_1_val_4_addr_reg_2756),
    .ce1(k_buf_1_val_4_ce1),
    .we1(k_buf_1_val_4_we1),
    .d1(k_buf_1_val_4_d1)
);

Filter2D_k_buf_0_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_1_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_1_val_5_address0),
    .ce0(k_buf_1_val_5_ce0),
    .q0(k_buf_1_val_5_q0),
    .address1(k_buf_1_val_5_addr_reg_2762),
    .ce1(k_buf_1_val_5_ce1),
    .we1(k_buf_1_val_5_we1),
    .d1(k_buf_1_val_5_d1)
);

Filter2D_k_buf_0_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_2_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_2_val_3_address0),
    .ce0(k_buf_2_val_3_ce0),
    .q0(k_buf_2_val_3_q0),
    .address1(k_buf_2_val_3_addr_reg_2768),
    .ce1(k_buf_2_val_3_ce1),
    .we1(k_buf_2_val_3_we1),
    .d1(p_src_data_stream_2_V_dout)
);

Filter2D_k_buf_0_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_2_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_2_val_4_address0),
    .ce0(k_buf_2_val_4_ce0),
    .q0(k_buf_2_val_4_q0),
    .address1(k_buf_2_val_4_addr_reg_2774),
    .ce1(k_buf_2_val_4_ce1),
    .we1(k_buf_2_val_4_we1),
    .d1(k_buf_2_val_4_d1)
);

Filter2D_k_buf_0_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_2_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_2_val_5_address0),
    .ce0(k_buf_2_val_5_ce0),
    .q0(k_buf_2_val_5_q0),
    .address1(k_buf_2_val_5_addr_reg_2780),
    .ce1(k_buf_2_val_5_ce1),
    .we1(k_buf_2_val_5_we1),
    .d1(k_buf_2_val_5_d1)
);

image_filter_mux_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_filter_mux_kbM_U13(
    .din0(right_border_buf_0_s_fu_304),
    .din1(right_border_buf_0_1_fu_308),
    .din2(8'd0),
    .din3(tmp_62_reg_2715_pp0_iter1_reg),
    .dout(tmp_18_fu_1152_p5)
);

image_filter_mux_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_filter_mux_kbM_U14(
    .din0(right_border_buf_0_2_fu_316),
    .din1(right_border_buf_0_3_fu_320),
    .din2(8'd0),
    .din3(tmp_62_reg_2715_pp0_iter1_reg),
    .dout(tmp_19_fu_1170_p5)
);

image_filter_mux_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_filter_mux_kbM_U15(
    .din0(right_border_buf_0_4_fu_328),
    .din1(right_border_buf_0_5_fu_332),
    .din2(8'd0),
    .din3(tmp_62_reg_2715_pp0_iter1_reg),
    .dout(tmp_20_fu_1188_p5)
);

image_filter_mux_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_filter_mux_kbM_U16(
    .din0(col_buf_0_val_0_0_fu_1163_p3),
    .din1(col_buf_0_val_1_0_fu_1181_p3),
    .din2(col_buf_0_val_2_0_fu_1199_p3),
    .din3(tmp_48_reg_2663),
    .dout(tmp_21_fu_1245_p5)
);

image_filter_mux_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_filter_mux_kbM_U17(
    .din0(col_buf_0_val_0_0_fu_1163_p3),
    .din1(col_buf_0_val_1_0_fu_1181_p3),
    .din2(col_buf_0_val_2_0_fu_1199_p3),
    .din3(tmp_50_reg_2670),
    .dout(tmp_22_fu_1263_p5)
);

image_filter_mux_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_filter_mux_kbM_U18(
    .din0(col_buf_0_val_0_0_fu_1163_p3),
    .din1(col_buf_0_val_1_0_fu_1181_p3),
    .din2(col_buf_0_val_2_0_fu_1199_p3),
    .din3(tmp_57_reg_2677),
    .dout(tmp_23_fu_1281_p5)
);

image_filter_mux_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_filter_mux_kbM_U19(
    .din0(right_border_buf_1_s_fu_340),
    .din1(right_border_buf_1_1_fu_344),
    .din2(8'd0),
    .din3(tmp_62_reg_2715_pp0_iter1_reg),
    .dout(tmp_25_fu_1317_p5)
);

image_filter_mux_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_filter_mux_kbM_U20(
    .din0(right_border_buf_1_2_fu_352),
    .din1(right_border_buf_1_3_fu_356),
    .din2(8'd0),
    .din3(tmp_62_reg_2715_pp0_iter1_reg),
    .dout(tmp_26_fu_1335_p5)
);

image_filter_mux_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_filter_mux_kbM_U21(
    .din0(right_border_buf_1_4_fu_364),
    .din1(right_border_buf_1_5_fu_368),
    .din2(8'd0),
    .din3(tmp_62_reg_2715_pp0_iter1_reg),
    .dout(tmp_27_fu_1353_p5)
);

image_filter_mux_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_filter_mux_kbM_U22(
    .din0(col_buf_1_val_0_0_fu_1328_p3),
    .din1(col_buf_1_val_1_0_fu_1346_p3),
    .din2(col_buf_1_val_2_0_fu_1364_p3),
    .din3(tmp_48_reg_2663),
    .dout(tmp_28_fu_1410_p5)
);

image_filter_mux_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_filter_mux_kbM_U23(
    .din0(col_buf_1_val_0_0_fu_1328_p3),
    .din1(col_buf_1_val_1_0_fu_1346_p3),
    .din2(col_buf_1_val_2_0_fu_1364_p3),
    .din3(tmp_50_reg_2670),
    .dout(tmp_29_fu_1428_p5)
);

image_filter_mux_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_filter_mux_kbM_U24(
    .din0(col_buf_1_val_0_0_fu_1328_p3),
    .din1(col_buf_1_val_1_0_fu_1346_p3),
    .din2(col_buf_1_val_2_0_fu_1364_p3),
    .din3(tmp_57_reg_2677),
    .dout(tmp_30_fu_1446_p5)
);

image_filter_mux_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_filter_mux_kbM_U25(
    .din0(right_border_buf_2_5_fu_372),
    .din1(right_border_buf_2_4_fu_360),
    .din2(8'd0),
    .din3(tmp_62_reg_2715_pp0_iter1_reg),
    .dout(tmp_32_fu_1473_p5)
);

image_filter_mux_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_filter_mux_kbM_U26(
    .din0(right_border_buf_2_3_fu_348),
    .din1(right_border_buf_2_2_fu_336),
    .din2(8'd0),
    .din3(tmp_62_reg_2715_pp0_iter1_reg),
    .dout(tmp_37_fu_1491_p5)
);

image_filter_mux_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_filter_mux_kbM_U27(
    .din0(right_border_buf_2_1_fu_324),
    .din1(right_border_buf_2_s_fu_312),
    .din2(8'd0),
    .din3(tmp_62_reg_2715_pp0_iter1_reg),
    .dout(tmp_39_fu_1509_p5)
);

image_filter_mux_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_filter_mux_kbM_U28(
    .din0(col_buf_2_val_0_0_fu_1484_p3),
    .din1(col_buf_2_val_1_0_fu_1502_p3),
    .din2(col_buf_2_val_2_0_fu_1520_p3),
    .din3(tmp_48_reg_2663),
    .dout(tmp_40_fu_1557_p5)
);

image_filter_mux_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_filter_mux_kbM_U29(
    .din0(col_buf_2_val_0_0_fu_1484_p3),
    .din1(col_buf_2_val_1_0_fu_1502_p3),
    .din2(col_buf_2_val_2_0_fu_1520_p3),
    .din3(tmp_50_reg_2670),
    .dout(tmp_41_fu_1575_p5)
);

image_filter_mux_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_filter_mux_kbM_U30(
    .din0(col_buf_2_val_0_0_fu_1484_p3),
    .din1(col_buf_2_val_1_0_fu_1502_p3),
    .din2(col_buf_2_val_2_0_fu_1520_p3),
    .din3(tmp_57_reg_2677),
    .dout(tmp_42_fu_1593_p5)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((exitcond389_i_fu_988_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter2_state7)) begin
                ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter1;
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond389_i_fu_988_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        t_V_4_reg_608 <= j_V_fu_993_p2;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        t_V_4_reg_608 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        t_V_reg_597 <= i_V_reg_2607;
    end else if (((tmp_4_fu_625_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        t_V_reg_597 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        tmp_2_reg_586 <= 2'd0;
    end else if (((tmp_4_fu_625_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        tmp_2_reg_586 <= tmp_3_fu_619_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond389_i_fu_988_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        brmerge_reg_2702 <= brmerge_fu_1099_p2;
        or_cond_i427_i_reg_2693 <= or_cond_i427_i_fu_1040_p2;
        or_cond_i_reg_2728 <= or_cond_i_fu_1108_p2;
        tmp_62_reg_2715 <= tmp_62_fu_1104_p1;
        x_reg_2697 <= x_fu_1086_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        brmerge_reg_2702_pp0_iter1_reg <= brmerge_reg_2702;
        exitcond389_i_reg_2684 <= exitcond389_i_fu_988_p2;
        exitcond389_i_reg_2684_pp0_iter1_reg <= exitcond389_i_reg_2684;
        or_cond_i427_i_reg_2693_pp0_iter1_reg <= or_cond_i427_i_reg_2693;
        or_cond_i_reg_2728_pp0_iter1_reg <= or_cond_i_reg_2728;
        tmp_62_reg_2715_pp0_iter1_reg <= tmp_62_reg_2715;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        exitcond389_i_reg_2684_pp0_iter2_reg <= exitcond389_i_reg_2684_pp0_iter1_reg;
        or_cond_i_reg_2728_pp0_iter2_reg <= or_cond_i_reg_2728_pp0_iter1_reg;
        or_cond_i_reg_2728_pp0_iter3_reg <= or_cond_i_reg_2728_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        i_V_reg_2607 <= i_V_fu_678_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond390_i_fu_673_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        icmp_reg_2617 <= icmp_fu_699_p2;
        tmp_10_reg_2630 <= tmp_10_fu_717_p2;
        tmp_128_0_1_reg_2626 <= tmp_128_0_1_fu_711_p2;
        tmp_1_reg_2622 <= tmp_1_fu_705_p2;
        tmp_8_reg_2612 <= tmp_8_fu_684_p2;
        y_1_0_1_reg_2648 <= y_1_0_1_fu_935_p3;
        y_1_0_2_reg_2653 <= y_1_0_2_fu_951_p3;
        y_1_reg_2643 <= y_1_fu_919_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_reg_2728_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        isneg_1_reg_2862 <= p_Val2_23_fu_1894_p2[32'd10];
        isneg_2_reg_2878 <= p_Val2_s_fu_2062_p2[32'd10];
        isneg_reg_2846 <= p_Val2_20_fu_1726_p2[32'd10];
        not_i_i_i1_reg_2873 <= not_i_i_i1_fu_1941_p2;
        not_i_i_i2_reg_2889 <= not_i_i_i2_fu_2109_p2;
        not_i_i_i_reg_2857 <= not_i_i_i_fu_1773_p2;
        p_Val2_21_reg_2852 <= p_Val2_21_fu_1757_p2;
        p_Val2_24_reg_2868 <= p_Val2_24_fu_1925_p2;
        p_Val2_26_reg_2884 <= p_Val2_26_fu_2093_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond389_i_reg_2684 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_buf_0_val_3_addr_reg_2732 <= tmp_17_fu_1113_p1;
        k_buf_0_val_4_addr_reg_2738 <= tmp_17_fu_1113_p1;
        k_buf_0_val_5_addr_reg_2744 <= tmp_17_fu_1113_p1;
        k_buf_1_val_3_addr_reg_2750 <= tmp_17_fu_1113_p1;
        k_buf_1_val_4_addr_reg_2756 <= tmp_17_fu_1113_p1;
        k_buf_1_val_5_addr_reg_2762 <= tmp_17_fu_1113_p1;
        k_buf_2_val_3_addr_reg_2768 <= tmp_17_fu_1113_p1;
        k_buf_2_val_4_addr_reg_2774 <= tmp_17_fu_1113_p1;
        k_buf_2_val_5_addr_reg_2780 <= tmp_17_fu_1113_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op240_read_state7 == 1'b1))) begin
        right_border_buf_0_1_fu_308 <= right_border_buf_0_s_fu_304;
        right_border_buf_0_2_fu_316 <= col_buf_0_val_1_0_fu_1181_p3;
        right_border_buf_0_3_fu_320 <= right_border_buf_0_2_fu_316;
        right_border_buf_0_4_fu_328 <= col_buf_0_val_2_0_fu_1199_p3;
        right_border_buf_0_5_fu_332 <= right_border_buf_0_4_fu_328;
        right_border_buf_0_s_fu_304 <= col_buf_0_val_0_0_fu_1163_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op282_read_state7 == 1'b1))) begin
        right_border_buf_1_1_fu_344 <= right_border_buf_1_s_fu_340;
        right_border_buf_1_2_fu_352 <= col_buf_1_val_1_0_fu_1346_p3;
        right_border_buf_1_3_fu_356 <= right_border_buf_1_2_fu_352;
        right_border_buf_1_4_fu_364 <= col_buf_1_val_2_0_fu_1364_p3;
        right_border_buf_1_5_fu_368 <= right_border_buf_1_4_fu_364;
        right_border_buf_1_s_fu_340 <= col_buf_1_val_0_0_fu_1328_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op318_read_state7 == 1'b1))) begin
        right_border_buf_2_1_fu_324 <= col_buf_2_val_2_0_fu_1520_p3;
        right_border_buf_2_2_fu_336 <= right_border_buf_2_3_fu_348;
        right_border_buf_2_3_fu_348 <= col_buf_2_val_1_0_fu_1502_p3;
        right_border_buf_2_4_fu_360 <= right_border_buf_2_5_fu_372;
        right_border_buf_2_5_fu_372 <= col_buf_2_val_0_0_fu_1484_p3;
        right_border_buf_2_s_fu_312 <= right_border_buf_2_1_fu_324;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond389_i_reg_2684_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        src_kernel_win_0_va_1_fu_236 <= src_kernel_win_0_va_fu_232;
        src_kernel_win_0_va_2_fu_240 <= src_kernel_win_0_va_7_reg_2793;
        src_kernel_win_0_va_3_fu_244 <= src_kernel_win_0_va_2_fu_240;
        src_kernel_win_0_va_4_fu_248 <= src_kernel_win_0_va_8_reg_2800;
        src_kernel_win_0_va_5_fu_252 <= src_kernel_win_0_va_4_fu_248;
        src_kernel_win_0_va_fu_232 <= src_kernel_win_0_va_6_reg_2786;
        src_kernel_win_1_va_1_fu_260 <= src_kernel_win_1_va_fu_256;
        src_kernel_win_1_va_2_fu_264 <= src_kernel_win_1_va_7_reg_2813;
        src_kernel_win_1_va_3_fu_268 <= src_kernel_win_1_va_2_fu_264;
        src_kernel_win_1_va_4_fu_272 <= src_kernel_win_1_va_8_reg_2820;
        src_kernel_win_1_va_5_fu_276 <= src_kernel_win_1_va_4_fu_272;
        src_kernel_win_1_va_fu_256 <= src_kernel_win_1_va_6_reg_2806;
        src_kernel_win_2_va_1_fu_284 <= src_kernel_win_2_va_fu_280;
        src_kernel_win_2_va_2_fu_288 <= src_kernel_win_2_va_10_reg_2833;
        src_kernel_win_2_va_3_fu_292 <= src_kernel_win_2_va_2_fu_288;
        src_kernel_win_2_va_4_fu_296 <= src_kernel_win_2_va_11_reg_2840;
        src_kernel_win_2_va_5_fu_300 <= src_kernel_win_2_va_4_fu_296;
        src_kernel_win_2_va_fu_280 <= src_kernel_win_2_va_9_reg_2826;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond389_i_reg_2684_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_kernel_win_0_va_6_reg_2786 <= src_kernel_win_0_va_6_fu_1256_p3;
        src_kernel_win_0_va_7_reg_2793 <= src_kernel_win_0_va_7_fu_1274_p3;
        src_kernel_win_0_va_8_reg_2800 <= src_kernel_win_0_va_8_fu_1292_p3;
        src_kernel_win_1_va_6_reg_2806 <= src_kernel_win_1_va_6_fu_1421_p3;
        src_kernel_win_1_va_7_reg_2813 <= src_kernel_win_1_va_7_fu_1439_p3;
        src_kernel_win_1_va_8_reg_2820 <= src_kernel_win_1_va_8_fu_1457_p3;
        src_kernel_win_2_va_10_reg_2833 <= src_kernel_win_2_va_10_fu_1586_p3;
        src_kernel_win_2_va_11_reg_2840 <= src_kernel_win_2_va_11_fu_1604_p3;
        src_kernel_win_2_va_9_reg_2826 <= src_kernel_win_2_va_9_fu_1568_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        tmp_48_reg_2663 <= tmp_48_fu_968_p1;
        tmp_50_reg_2670 <= tmp_50_fu_976_p1;
        tmp_57_reg_2677 <= tmp_57_fu_984_p1;
        tmp_84_0_0_not_reg_2658 <= tmp_84_0_0_not_fu_959_p2;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_condition_pp0_exit_iter2_state7 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter2_state7 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((exitcond390_i_fu_673_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond390_i_fu_673_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_buf_0_val_3_ce0 = 1'b1;
    end else begin
        k_buf_0_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_1_reg_2622 == 1'd1) & (or_cond_i427_i_reg_2693_pp0_iter1_reg == 1'd1) & (icmp_reg_2617 == 1'd0) & (exitcond389_i_reg_2684_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op240_read_state7 == 1'b1)))) begin
        k_buf_0_val_3_ce1 = 1'b1;
    end else begin
        k_buf_0_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_1_reg_2622 == 1'd1) & (or_cond_i427_i_reg_2693_pp0_iter1_reg == 1'd1) & (icmp_reg_2617 == 1'd0) & (exitcond389_i_reg_2684_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op240_read_state7 == 1'b1)))) begin
        k_buf_0_val_3_we1 = 1'b1;
    end else begin
        k_buf_0_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_buf_0_val_4_ce0 = 1'b1;
    end else begin
        k_buf_0_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_128_0_1_reg_2626 == 1'd1) & (or_cond_i427_i_reg_2693_pp0_iter1_reg == 1'd1) & (icmp_reg_2617 == 1'd0) & (exitcond389_i_reg_2684_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op240_read_state7 == 1'b1)))) begin
        k_buf_0_val_4_ce1 = 1'b1;
    end else begin
        k_buf_0_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((ap_predicate_op240_read_state7 == 1'b1)) begin
            k_buf_0_val_4_d1 = k_buf_0_val_3_q0;
        end else if ((1'b1 == ap_condition_602)) begin
            k_buf_0_val_4_d1 = p_src_data_stream_0_V_dout;
        end else begin
            k_buf_0_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_128_0_1_reg_2626 == 1'd1) & (or_cond_i427_i_reg_2693_pp0_iter1_reg == 1'd1) & (icmp_reg_2617 == 1'd0) & (exitcond389_i_reg_2684_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op240_read_state7 == 1'b1)))) begin
        k_buf_0_val_4_we1 = 1'b1;
    end else begin
        k_buf_0_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_buf_0_val_5_ce0 = 1'b1;
    end else begin
        k_buf_0_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_1_reg_2622 == 1'd1) & (or_cond_i427_i_reg_2693_pp0_iter1_reg == 1'd1) & (icmp_reg_2617 == 1'd0) & (exitcond389_i_reg_2684_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op240_read_state7 == 1'b1)))) begin
        k_buf_0_val_5_ce1 = 1'b1;
    end else begin
        k_buf_0_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((ap_predicate_op240_read_state7 == 1'b1)) begin
            k_buf_0_val_5_d1 = k_buf_0_val_4_q0;
        end else if ((1'b1 == ap_condition_596)) begin
            k_buf_0_val_5_d1 = p_src_data_stream_0_V_dout;
        end else begin
            k_buf_0_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_1_reg_2622 == 1'd1) & (or_cond_i427_i_reg_2693_pp0_iter1_reg == 1'd1) & (icmp_reg_2617 == 1'd0) & (exitcond389_i_reg_2684_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op240_read_state7 == 1'b1)))) begin
        k_buf_0_val_5_we1 = 1'b1;
    end else begin
        k_buf_0_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_buf_1_val_3_ce0 = 1'b1;
    end else begin
        k_buf_1_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_1_reg_2622 == 1'd1) & (or_cond_i427_i_reg_2693_pp0_iter1_reg == 1'd1) & (icmp_reg_2617 == 1'd0) & (exitcond389_i_reg_2684_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op282_read_state7 == 1'b1)))) begin
        k_buf_1_val_3_ce1 = 1'b1;
    end else begin
        k_buf_1_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_1_reg_2622 == 1'd1) & (or_cond_i427_i_reg_2693_pp0_iter1_reg == 1'd1) & (icmp_reg_2617 == 1'd0) & (exitcond389_i_reg_2684_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op282_read_state7 == 1'b1)))) begin
        k_buf_1_val_3_we1 = 1'b1;
    end else begin
        k_buf_1_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_buf_1_val_4_ce0 = 1'b1;
    end else begin
        k_buf_1_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_128_0_1_reg_2626 == 1'd1) & (or_cond_i427_i_reg_2693_pp0_iter1_reg == 1'd1) & (icmp_reg_2617 == 1'd0) & (exitcond389_i_reg_2684_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op282_read_state7 == 1'b1)))) begin
        k_buf_1_val_4_ce1 = 1'b1;
    end else begin
        k_buf_1_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((ap_predicate_op282_read_state7 == 1'b1)) begin
            k_buf_1_val_4_d1 = k_buf_1_val_3_q0;
        end else if ((1'b1 == ap_condition_602)) begin
            k_buf_1_val_4_d1 = p_src_data_stream_1_V_dout;
        end else begin
            k_buf_1_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_1_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_128_0_1_reg_2626 == 1'd1) & (or_cond_i427_i_reg_2693_pp0_iter1_reg == 1'd1) & (icmp_reg_2617 == 1'd0) & (exitcond389_i_reg_2684_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op282_read_state7 == 1'b1)))) begin
        k_buf_1_val_4_we1 = 1'b1;
    end else begin
        k_buf_1_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_buf_1_val_5_ce0 = 1'b1;
    end else begin
        k_buf_1_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_1_reg_2622 == 1'd1) & (or_cond_i427_i_reg_2693_pp0_iter1_reg == 1'd1) & (icmp_reg_2617 == 1'd0) & (exitcond389_i_reg_2684_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op282_read_state7 == 1'b1)))) begin
        k_buf_1_val_5_ce1 = 1'b1;
    end else begin
        k_buf_1_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((ap_predicate_op282_read_state7 == 1'b1)) begin
            k_buf_1_val_5_d1 = k_buf_1_val_4_q0;
        end else if ((1'b1 == ap_condition_596)) begin
            k_buf_1_val_5_d1 = p_src_data_stream_1_V_dout;
        end else begin
            k_buf_1_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_1_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_1_reg_2622 == 1'd1) & (or_cond_i427_i_reg_2693_pp0_iter1_reg == 1'd1) & (icmp_reg_2617 == 1'd0) & (exitcond389_i_reg_2684_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op282_read_state7 == 1'b1)))) begin
        k_buf_1_val_5_we1 = 1'b1;
    end else begin
        k_buf_1_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_buf_2_val_3_ce0 = 1'b1;
    end else begin
        k_buf_2_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_1_reg_2622 == 1'd1) & (or_cond_i427_i_reg_2693_pp0_iter1_reg == 1'd1) & (icmp_reg_2617 == 1'd0) & (exitcond389_i_reg_2684_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op318_read_state7 == 1'b1)))) begin
        k_buf_2_val_3_ce1 = 1'b1;
    end else begin
        k_buf_2_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_1_reg_2622 == 1'd1) & (or_cond_i427_i_reg_2693_pp0_iter1_reg == 1'd1) & (icmp_reg_2617 == 1'd0) & (exitcond389_i_reg_2684_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op318_read_state7 == 1'b1)))) begin
        k_buf_2_val_3_we1 = 1'b1;
    end else begin
        k_buf_2_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_buf_2_val_4_ce0 = 1'b1;
    end else begin
        k_buf_2_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_128_0_1_reg_2626 == 1'd1) & (or_cond_i427_i_reg_2693_pp0_iter1_reg == 1'd1) & (icmp_reg_2617 == 1'd0) & (exitcond389_i_reg_2684_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op318_read_state7 == 1'b1)))) begin
        k_buf_2_val_4_ce1 = 1'b1;
    end else begin
        k_buf_2_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((ap_predicate_op318_read_state7 == 1'b1)) begin
            k_buf_2_val_4_d1 = k_buf_2_val_3_q0;
        end else if ((1'b1 == ap_condition_602)) begin
            k_buf_2_val_4_d1 = p_src_data_stream_2_V_dout;
        end else begin
            k_buf_2_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_2_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_128_0_1_reg_2626 == 1'd1) & (or_cond_i427_i_reg_2693_pp0_iter1_reg == 1'd1) & (icmp_reg_2617 == 1'd0) & (exitcond389_i_reg_2684_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op318_read_state7 == 1'b1)))) begin
        k_buf_2_val_4_we1 = 1'b1;
    end else begin
        k_buf_2_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_buf_2_val_5_ce0 = 1'b1;
    end else begin
        k_buf_2_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_1_reg_2622 == 1'd1) & (or_cond_i427_i_reg_2693_pp0_iter1_reg == 1'd1) & (icmp_reg_2617 == 1'd0) & (exitcond389_i_reg_2684_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op318_read_state7 == 1'b1)))) begin
        k_buf_2_val_5_ce1 = 1'b1;
    end else begin
        k_buf_2_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((ap_predicate_op318_read_state7 == 1'b1)) begin
            k_buf_2_val_5_d1 = k_buf_2_val_4_q0;
        end else if ((1'b1 == ap_condition_596)) begin
            k_buf_2_val_5_d1 = p_src_data_stream_2_V_dout;
        end else begin
            k_buf_2_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_2_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_1_reg_2622 == 1'd1) & (or_cond_i427_i_reg_2693_pp0_iter1_reg == 1'd1) & (icmp_reg_2617 == 1'd0) & (exitcond389_i_reg_2684_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op318_read_state7 == 1'b1)))) begin
        k_buf_2_val_5_we1 = 1'b1;
    end else begin
        k_buf_2_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2728_pp0_iter3_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        p_dst_data_stream_0_V_blk_n = p_dst_data_stream_0_V_full_n;
    end else begin
        p_dst_data_stream_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2728_pp0_iter3_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        p_dst_data_stream_0_V_write = 1'b1;
    end else begin
        p_dst_data_stream_0_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2728_pp0_iter3_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        p_dst_data_stream_1_V_blk_n = p_dst_data_stream_1_V_full_n;
    end else begin
        p_dst_data_stream_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2728_pp0_iter3_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        p_dst_data_stream_1_V_write = 1'b1;
    end else begin
        p_dst_data_stream_1_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2728_pp0_iter3_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        p_dst_data_stream_2_V_blk_n = p_dst_data_stream_2_V_full_n;
    end else begin
        p_dst_data_stream_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2728_pp0_iter3_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        p_dst_data_stream_2_V_write = 1'b1;
    end else begin
        p_dst_data_stream_2_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i427_i_reg_2693_pp0_iter1_reg == 1'd1) & (icmp_reg_2617 == 1'd0) & (exitcond389_i_reg_2684_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((tmp_8_reg_2612 == 1'd1) & (icmp_reg_2617 == 1'd1) & (or_cond_i427_i_reg_2693_pp0_iter1_reg == 1'd1) & (exitcond389_i_reg_2684_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        p_src_data_stream_0_V_blk_n = p_src_data_stream_0_V_empty_n;
    end else begin
        p_src_data_stream_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op240_read_state7 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op228_read_state7 == 1'b1)))) begin
        p_src_data_stream_0_V_read = 1'b1;
    end else begin
        p_src_data_stream_0_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i427_i_reg_2693_pp0_iter1_reg == 1'd1) & (icmp_reg_2617 == 1'd0) & (exitcond389_i_reg_2684_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((tmp_8_reg_2612 == 1'd1) & (icmp_reg_2617 == 1'd1) & (or_cond_i427_i_reg_2693_pp0_iter1_reg == 1'd1) & (exitcond389_i_reg_2684_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        p_src_data_stream_1_V_blk_n = p_src_data_stream_1_V_empty_n;
    end else begin
        p_src_data_stream_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op282_read_state7 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op270_read_state7 == 1'b1)))) begin
        p_src_data_stream_1_V_read = 1'b1;
    end else begin
        p_src_data_stream_1_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i427_i_reg_2693_pp0_iter1_reg == 1'd1) & (icmp_reg_2617 == 1'd0) & (exitcond389_i_reg_2684_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((tmp_8_reg_2612 == 1'd1) & (icmp_reg_2617 == 1'd1) & (or_cond_i427_i_reg_2693_pp0_iter1_reg == 1'd1) & (exitcond389_i_reg_2684_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        p_src_data_stream_2_V_blk_n = p_src_data_stream_2_V_empty_n;
    end else begin
        p_src_data_stream_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op318_read_state7 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op309_read_state7 == 1'b1)))) begin
        p_src_data_stream_2_V_read = 1'b1;
    end else begin
        p_src_data_stream_2_V_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((tmp_4_fu_625_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((exitcond390_i_fu_673_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1)) & ~((ap_enable_reg_pp0_iter3 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter3 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ImagLoc_x_fu_1015_p2 = ($signed(32'd4294967295) + $signed(t_V_4_reg_608));

assign OP1_V_0_0_cast_fu_1620_p1 = src_kernel_win_0_va_5_fu_252;

assign OP1_V_0_2_cast_fu_1683_p1 = src_kernel_win_0_va_1_fu_236;

assign OP1_V_1_0_cast_fu_1788_p1 = src_kernel_win_1_va_5_fu_276;

assign OP1_V_1_2_cast_fu_1851_p1 = src_kernel_win_1_va_1_fu_260;

assign OP1_V_2_0_cast_fu_1956_p1 = src_kernel_win_2_va_5_fu_300;

assign OP1_V_2_2_cast_fu_2019_p1 = src_kernel_win_2_va_1_fu_284;

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter4 == 1'b1) & (((or_cond_i_reg_2728_pp0_iter3_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((or_cond_i_reg_2728_pp0_iter3_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((or_cond_i_reg_2728_pp0_iter3_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)))) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op318_read_state7 == 1'b1)) | ((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op309_read_state7 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op282_read_state7 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op270_read_state7 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op240_read_state7 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op228_read_state7 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter4 == 1'b1) & (((or_cond_i_reg_2728_pp0_iter3_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((or_cond_i_reg_2728_pp0_iter3_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((or_cond_i_reg_2728_pp0_iter3_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)))) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op318_read_state7 == 1'b1)) | ((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op309_read_state7 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op282_read_state7 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op270_read_state7 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op240_read_state7 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op228_read_state7 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter4 == 1'b1) & (((or_cond_i_reg_2728_pp0_iter3_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((or_cond_i_reg_2728_pp0_iter3_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((or_cond_i_reg_2728_pp0_iter3_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)))) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op318_read_state7 == 1'b1)) | ((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op309_read_state7 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op282_read_state7 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op270_read_state7 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op240_read_state7 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op228_read_state7 == 1'b1)))));
end

assign ap_block_state5_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state7_pp0_stage0_iter2 = (((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op318_read_state7 == 1'b1)) | ((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op309_read_state7 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op282_read_state7 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op270_read_state7 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op240_read_state7 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op228_read_state7 == 1'b1)));
end

assign ap_block_state8_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state9_pp0_stage0_iter4 = (((or_cond_i_reg_2728_pp0_iter3_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((or_cond_i_reg_2728_pp0_iter3_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((or_cond_i_reg_2728_pp0_iter3_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)));
end

always @ (*) begin
    ap_condition_596 = ((tmp_1_reg_2622 == 1'd1) & (or_cond_i427_i_reg_2693_pp0_iter1_reg == 1'd1) & (icmp_reg_2617 == 1'd0) & (exitcond389_i_reg_2684_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_condition_602 = ((tmp_128_0_1_reg_2626 == 1'd1) & (or_cond_i427_i_reg_2693_pp0_iter1_reg == 1'd1) & (icmp_reg_2617 == 1'd0) & (exitcond389_i_reg_2684_pp0_iter1_reg == 1'd0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_predicate_op228_read_state7 = ((or_cond_i427_i_reg_2693_pp0_iter1_reg == 1'd1) & (icmp_reg_2617 == 1'd0) & (exitcond389_i_reg_2684_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op240_read_state7 = ((tmp_8_reg_2612 == 1'd1) & (icmp_reg_2617 == 1'd1) & (or_cond_i427_i_reg_2693_pp0_iter1_reg == 1'd1) & (exitcond389_i_reg_2684_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op270_read_state7 = ((or_cond_i427_i_reg_2693_pp0_iter1_reg == 1'd1) & (icmp_reg_2617 == 1'd0) & (exitcond389_i_reg_2684_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op282_read_state7 = ((tmp_8_reg_2612 == 1'd1) & (icmp_reg_2617 == 1'd1) & (or_cond_i427_i_reg_2693_pp0_iter1_reg == 1'd1) & (exitcond389_i_reg_2684_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op309_read_state7 = ((or_cond_i427_i_reg_2693_pp0_iter1_reg == 1'd1) & (icmp_reg_2617 == 1'd0) & (exitcond389_i_reg_2684_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op318_read_state7 = ((tmp_8_reg_2612 == 1'd1) & (icmp_reg_2617 == 1'd1) & (or_cond_i427_i_reg_2693_pp0_iter1_reg == 1'd1) & (exitcond389_i_reg_2684_pp0_iter1_reg == 1'd0));
end

assign brmerge_fu_1099_p2 = (tmp_84_0_0_not_reg_2658 | tmp_15_fu_1035_p2);

assign col_assign_2_fu_1094_p2 = (tmp_6_fu_646_p2 - x_fu_1086_p3);

assign col_buf_0_val_0_0_fu_1163_p3 = ((brmerge_reg_2702_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_0_val_3_q0 : tmp_18_fu_1152_p5);

assign col_buf_0_val_1_0_fu_1181_p3 = ((brmerge_reg_2702_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_0_val_4_q0 : tmp_19_fu_1170_p5);

assign col_buf_0_val_2_0_fu_1199_p3 = ((brmerge_reg_2702_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_0_val_5_q0 : tmp_20_fu_1188_p5);

assign col_buf_1_val_0_0_fu_1328_p3 = ((brmerge_reg_2702_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_1_val_3_q0 : tmp_25_fu_1317_p5);

assign col_buf_1_val_1_0_fu_1346_p3 = ((brmerge_reg_2702_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_1_val_4_q0 : tmp_26_fu_1335_p5);

assign col_buf_1_val_2_0_fu_1364_p3 = ((brmerge_reg_2702_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_1_val_5_q0 : tmp_27_fu_1353_p5);

assign col_buf_2_val_0_0_fu_1484_p3 = ((brmerge_reg_2702_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_2_val_3_q0 : tmp_32_fu_1473_p5);

assign col_buf_2_val_1_0_fu_1502_p3 = ((brmerge_reg_2702_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_2_val_4_q0 : tmp_37_fu_1491_p5);

assign col_buf_2_val_2_0_fu_1520_p3 = ((brmerge_reg_2702_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_2_val_5_q0 : tmp_39_fu_1509_p5);

assign exitcond389_i_fu_988_p2 = ((t_V_4_reg_608 == tmp_s_fu_631_p2) ? 1'b1 : 1'b0);

assign exitcond390_i_fu_673_p2 = ((t_V_reg_597 == tmp_5_fu_636_p2) ? 1'b1 : 1'b0);

assign i_V_fu_678_p2 = (t_V_reg_597 + 32'd1);

assign icmp1_fu_1009_p2 = ((tmp_58_fu_999_p4 != 31'd0) ? 1'b1 : 1'b0);

assign icmp_fu_699_p2 = ((tmp_34_fu_689_p4 != 31'd0) ? 1'b1 : 1'b0);

assign j_V_fu_993_p2 = (t_V_4_reg_608 + 32'd1);

assign k_buf_0_val_3_address0 = tmp_17_fu_1113_p1;

assign k_buf_0_val_4_address0 = tmp_17_fu_1113_p1;

assign k_buf_0_val_5_address0 = tmp_17_fu_1113_p1;

assign k_buf_1_val_3_address0 = tmp_17_fu_1113_p1;

assign k_buf_1_val_4_address0 = tmp_17_fu_1113_p1;

assign k_buf_1_val_5_address0 = tmp_17_fu_1113_p1;

assign k_buf_2_val_3_address0 = tmp_17_fu_1113_p1;

assign k_buf_2_val_4_address0 = tmp_17_fu_1113_p1;

assign k_buf_2_val_5_address0 = tmp_17_fu_1113_p1;

assign not_i_i_i1_fu_1941_p2 = ((tmp_31_fu_1931_p4 != 3'd0) ? 1'b1 : 1'b0);

assign not_i_i_i2_fu_2109_p2 = ((tmp_43_fu_2099_p4 != 3'd0) ? 1'b1 : 1'b0);

assign not_i_i_i_fu_1773_p2 = ((tmp_24_fu_1763_p4 != 3'd0) ? 1'b1 : 1'b0);

assign or_cond_i427_i_fu_1040_p2 = (tmp_15_fu_1035_p2 & rev3_fu_1029_p2);

assign or_cond_i_fu_1108_p2 = (icmp_reg_2617 & icmp1_fu_1009_p2);

assign or_cond_i_i_0_1_fu_810_p2 = (tmp_154_0_1_fu_805_p2 & rev1_fu_799_p2);

assign or_cond_i_i_0_2_fu_873_p2 = (tmp_154_0_2_fu_868_p2 & rev2_fu_862_p2);

assign or_cond_i_i_fu_747_p2 = (tmp_12_fu_742_p2 & rev_fu_736_p2);

assign overflow_3_fu_2259_p2 = (tmp_8_i_i1_fu_2254_p2 & not_i_i_i1_reg_2873);

assign overflow_4_fu_2290_p2 = (tmp_8_i_i2_fu_2285_p2 & not_i_i_i2_reg_2889);

assign overflow_fu_2228_p2 = (tmp_8_i_i_fu_2223_p2 & not_i_i_i_reg_2857);

assign p_Val2_20_fu_1726_p2 = (tmp21_fu_1704_p2 + tmp22_fu_1720_p2);

assign p_Val2_21_fu_1757_p2 = (tmp24_fu_1740_p2 + tmp25_fu_1751_p2);

assign p_Val2_23_fu_1894_p2 = (tmp29_fu_1872_p2 + tmp30_fu_1888_p2);

assign p_Val2_24_fu_1925_p2 = (tmp32_fu_1908_p2 + tmp33_fu_1919_p2);

assign p_Val2_26_fu_2093_p2 = (tmp40_fu_2076_p2 + tmp41_fu_2087_p2);

assign p_Val2_8_0_0_2_cas_fu_1633_p1 = p_Val2_8_0_0_2_fu_1627_p2;

assign p_Val2_8_0_0_2_fu_1627_p2 = (tmp_172_0_0_2_cast_fu_1624_p1 - OP1_V_0_0_cast_fu_1620_p1);

assign p_Val2_8_1_0_2_cas_fu_1801_p1 = p_Val2_8_1_0_2_fu_1795_p2;

assign p_Val2_8_1_0_2_fu_1795_p2 = (tmp_172_1_0_2_cast_fu_1792_p1 - OP1_V_1_0_cast_fu_1788_p1);

assign p_Val2_8_2_0_2_cas_fu_1969_p1 = p_Val2_8_2_0_2_fu_1963_p2;

assign p_Val2_8_2_0_2_fu_1963_p2 = (tmp_172_2_0_2_cast_fu_1960_p1 - OP1_V_2_0_cast_fu_1956_p1);

assign p_Val2_s_fu_2062_p2 = (tmp37_fu_2040_p2 + tmp38_fu_2056_p2);

assign p_assign_1_fu_1054_p2 = (32'd1 - t_V_4_reg_608);

assign p_assign_2_fu_1073_p2 = (tmp_80_2_fu_667_p2 - p_p2_i429_i_fu_1060_p3);

assign p_assign_6_0_1_fu_785_p2 = ($signed(32'd4294967294) + $signed(t_V_reg_597));

assign p_assign_6_0_2_fu_848_p2 = ($signed(32'd4294967293) + $signed(t_V_reg_597));

assign p_assign_7_0_1_fu_824_p2 = (32'd2 - t_V_reg_597);

assign p_assign_7_0_2_fu_887_p2 = (32'd3 - t_V_reg_597);

assign p_assign_7_fu_761_p2 = (32'd1 - t_V_reg_597);

assign p_assign_8_0_1_fu_843_p2 = (tmp_7_fu_656_p2 - p_p2_i_i_0_1_fu_830_p3);

assign p_assign_8_0_2_fu_906_p2 = (tmp_7_fu_656_p2 - p_p2_i_i_0_2_fu_893_p3);

assign p_assign_8_fu_780_p2 = (tmp_7_fu_656_p2 - p_p2_i_i_fu_767_p3);

assign p_dst_data_stream_0_V_din = ((tmp_i_i_fu_2241_p2[0:0] === 1'b1) ? p_mux_i_i_cast_fu_2233_p3 : p_Val2_21_reg_2852);

assign p_dst_data_stream_1_V_din = ((tmp_i_i2_fu_2272_p2[0:0] === 1'b1) ? p_mux_i_i30_cast_fu_2264_p3 : p_Val2_24_reg_2868);

assign p_dst_data_stream_2_V_din = ((tmp_i_i3_fu_2303_p2[0:0] === 1'b1) ? p_mux_i_i39_cast_fu_2295_p3 : p_Val2_26_reg_2884);

assign p_mux_i_i30_cast_fu_2264_p3 = ((tmp_8_i_i1_fu_2254_p2[0:0] === 1'b1) ? 8'd255 : 8'd0);

assign p_mux_i_i39_cast_fu_2295_p3 = ((tmp_8_i_i2_fu_2285_p2[0:0] === 1'b1) ? 8'd255 : 8'd0);

assign p_mux_i_i_cast_fu_2233_p3 = ((tmp_8_i_i_fu_2223_p2[0:0] === 1'b1) ? 8'd255 : 8'd0);

assign p_neg394_i_fu_641_p2 = ($signed(32'd4294967295) + $signed(p_src_rows_V_read));

assign p_p2_i429_i_fu_1060_p3 = ((tmp_60_fu_1046_p3[0:0] === 1'b1) ? p_assign_1_fu_1054_p2 : ImagLoc_x_fu_1015_p2);

assign p_p2_i429_i_p_assign_2_fu_1078_p3 = ((tmp_16_fu_1068_p2[0:0] === 1'b1) ? p_p2_i429_i_fu_1060_p3 : p_assign_2_fu_1073_p2);

assign p_p2_i_i_0_1_fu_830_p3 = ((tmp_45_fu_816_p3[0:0] === 1'b1) ? p_assign_7_0_1_fu_824_p2 : p_assign_6_0_1_fu_785_p2);

assign p_p2_i_i_0_1_p_assign_fu_927_p3 = ((tmp_164_0_1_fu_838_p2[0:0] === 1'b1) ? p_p2_i_i_0_1_fu_830_p3 : p_assign_8_0_1_fu_843_p2);

assign p_p2_i_i_0_2_fu_893_p3 = ((tmp_47_fu_879_p3[0:0] === 1'b1) ? p_assign_7_0_2_fu_887_p2 : p_assign_6_0_2_fu_848_p2);

assign p_p2_i_i_0_2_p_assign_fu_943_p3 = ((tmp_164_0_2_fu_901_p2[0:0] === 1'b1) ? p_p2_i_i_0_2_fu_893_p3 : p_assign_8_0_2_fu_906_p2);

assign p_p2_i_i_0_p_assign_8_fu_911_p3 = ((tmp_14_fu_775_p2[0:0] === 1'b1) ? p_p2_i_i_fu_767_p3 : p_assign_8_fu_780_p2);

assign p_p2_i_i_fu_767_p3 = ((tmp_36_fu_753_p3[0:0] === 1'b1) ? p_assign_7_fu_761_p2 : tmp_11_fu_722_p2);

assign p_shl1_cast_fu_1813_p1 = p_shl1_fu_1805_p3;

assign p_shl1_fu_1805_p3 = {{src_kernel_win_1_va_3_fu_268}, {1'd0}};

assign p_shl2_cast_fu_1981_p1 = p_shl2_fu_1973_p3;

assign p_shl2_fu_1973_p3 = {{src_kernel_win_2_va_3_fu_292}, {1'd0}};

assign p_shl_cast_fu_1645_p1 = p_shl_fu_1637_p3;

assign p_shl_fu_1637_p3 = {{src_kernel_win_0_va_3_fu_244}, {1'd0}};

assign r_V_2_0_1_2_fu_1667_p3 = {{src_kernel_win_0_va_7_reg_2793}, {1'd0}};

assign r_V_2_0_1_fu_1649_p2 = (10'd0 - p_shl_cast_fu_1645_p1);

assign r_V_2_0_2_fu_1687_p2 = (9'd0 - OP1_V_0_2_cast_fu_1683_p1);

assign r_V_2_1_1_2_fu_1835_p3 = {{src_kernel_win_1_va_7_reg_2813}, {1'd0}};

assign r_V_2_1_1_fu_1817_p2 = (10'd0 - p_shl1_cast_fu_1813_p1);

assign r_V_2_1_2_fu_1855_p2 = (9'd0 - OP1_V_1_2_cast_fu_1851_p1);

assign r_V_2_2_1_2_fu_2003_p3 = {{src_kernel_win_2_va_10_reg_2833}, {1'd0}};

assign r_V_2_2_1_fu_1985_p2 = (10'd0 - p_shl2_cast_fu_1981_p1);

assign r_V_2_2_2_fu_2023_p2 = (9'd0 - OP1_V_2_2_cast_fu_2019_p1);

assign rev1_fu_799_p2 = (tmp_38_fu_791_p3 ^ 1'd1);

assign rev2_fu_862_p2 = (tmp_46_fu_854_p3 ^ 1'd1);

assign rev3_fu_1029_p2 = (tmp_59_fu_1021_p3 ^ 1'd1);

assign rev_fu_736_p2 = (tmp_35_fu_728_p3 ^ 1'd1);

assign row_assign_9_0_1_fu_972_p2 = (p_neg394_i_fu_641_p2 - y_1_0_1_reg_2648);

assign row_assign_9_0_2_fu_980_p2 = (p_neg394_i_fu_641_p2 - y_1_0_2_reg_2653);

assign row_assign_9_fu_964_p2 = (p_neg394_i_fu_641_p2 - y_1_reg_2643);

assign src_kernel_win_0_va_6_fu_1256_p3 = ((tmp_10_reg_2630[0:0] === 1'b1) ? tmp_21_fu_1245_p5 : col_buf_0_val_0_0_fu_1163_p3);

assign src_kernel_win_0_va_7_fu_1274_p3 = ((tmp_10_reg_2630[0:0] === 1'b1) ? tmp_22_fu_1263_p5 : col_buf_0_val_1_0_fu_1181_p3);

assign src_kernel_win_0_va_8_fu_1292_p3 = ((tmp_10_reg_2630[0:0] === 1'b1) ? tmp_23_fu_1281_p5 : col_buf_0_val_2_0_fu_1199_p3);

assign src_kernel_win_1_va_6_fu_1421_p3 = ((tmp_10_reg_2630[0:0] === 1'b1) ? tmp_28_fu_1410_p5 : col_buf_1_val_0_0_fu_1328_p3);

assign src_kernel_win_1_va_7_fu_1439_p3 = ((tmp_10_reg_2630[0:0] === 1'b1) ? tmp_29_fu_1428_p5 : col_buf_1_val_1_0_fu_1346_p3);

assign src_kernel_win_1_va_8_fu_1457_p3 = ((tmp_10_reg_2630[0:0] === 1'b1) ? tmp_30_fu_1446_p5 : col_buf_1_val_2_0_fu_1364_p3);

assign src_kernel_win_2_va_10_fu_1586_p3 = ((tmp_10_reg_2630[0:0] === 1'b1) ? tmp_41_fu_1575_p5 : col_buf_2_val_1_0_fu_1502_p3);

assign src_kernel_win_2_va_11_fu_1604_p3 = ((tmp_10_reg_2630[0:0] === 1'b1) ? tmp_42_fu_1593_p5 : col_buf_2_val_2_0_fu_1520_p3);

assign src_kernel_win_2_va_9_fu_1568_p3 = ((tmp_10_reg_2630[0:0] === 1'b1) ? tmp_40_fu_1557_p5 : col_buf_2_val_0_0_fu_1484_p3);

assign tmp21_fu_1704_p2 = ($signed(tmp_172_0_2_cast_fu_1693_p1) + $signed(tmp_172_0_1_cast_fu_1655_p1));

assign tmp22_fu_1720_p2 = ($signed(tmp_172_0_1_cast_67_fu_1674_p1) + $signed(tmp23_cast_fu_1716_p1));

assign tmp23_cast_fu_1716_p1 = $signed(tmp23_fu_1710_p2);

assign tmp23_fu_1710_p2 = ($signed(tmp_172_0_2_2_cast_c_fu_1701_p1) + $signed(p_Val2_8_0_0_2_cas_fu_1633_p1));

assign tmp24_fu_1740_p2 = (tmp_66_fu_1663_p1 + tmp_65_fu_1659_p1);

assign tmp25_fu_1751_p2 = (tmp_67_fu_1678_p2 + tmp26_fu_1746_p2);

assign tmp26_fu_1746_p2 = (src_kernel_win_0_va_6_reg_2786 + tmp_68_fu_1697_p1);

assign tmp29_fu_1872_p2 = ($signed(tmp_172_1_2_cast_fu_1861_p1) + $signed(tmp_172_1_1_cast_fu_1823_p1));

assign tmp30_fu_1888_p2 = ($signed(tmp_172_1_1_cast_68_fu_1842_p1) + $signed(tmp31_cast_fu_1884_p1));

assign tmp31_cast_fu_1884_p1 = $signed(tmp31_fu_1878_p2);

assign tmp31_fu_1878_p2 = ($signed(tmp_172_1_2_2_cast_c_fu_1869_p1) + $signed(p_Val2_8_1_0_2_cas_fu_1801_p1));

assign tmp32_fu_1908_p2 = (tmp_74_fu_1831_p1 + tmp_73_fu_1827_p1);

assign tmp33_fu_1919_p2 = (tmp_75_fu_1846_p2 + tmp34_fu_1914_p2);

assign tmp34_fu_1914_p2 = (src_kernel_win_1_va_6_reg_2806 + tmp_76_fu_1865_p1);

assign tmp37_fu_2040_p2 = ($signed(tmp_172_2_2_cast_fu_2029_p1) + $signed(tmp_172_2_1_cast_fu_1991_p1));

assign tmp38_fu_2056_p2 = ($signed(tmp_172_2_1_cast_69_fu_2010_p1) + $signed(tmp39_cast_fu_2052_p1));

assign tmp39_cast_fu_2052_p1 = $signed(tmp39_fu_2046_p2);

assign tmp39_fu_2046_p2 = ($signed(tmp_172_2_2_2_cast_c_fu_2037_p1) + $signed(p_Val2_8_2_0_2_cas_fu_1969_p1));

assign tmp40_fu_2076_p2 = (tmp_82_fu_1999_p1 + tmp_81_fu_1995_p1);

assign tmp41_fu_2087_p2 = (tmp_83_fu_2014_p2 + tmp42_fu_2082_p2);

assign tmp42_fu_2082_p2 = (src_kernel_win_2_va_9_reg_2826 + tmp_84_fu_2033_p1);

assign tmp_10_fu_717_p2 = ((t_V_reg_597 > p_src_rows_V_read) ? 1'b1 : 1'b0);

assign tmp_11_fu_722_p2 = ($signed(32'd4294967295) + $signed(t_V_reg_597));

assign tmp_128_0_1_fu_711_p2 = ((t_V_reg_597 == 32'd0) ? 1'b1 : 1'b0);

assign tmp_12_fu_742_p2 = (($signed(tmp_11_fu_722_p2) < $signed(p_src_rows_V_read)) ? 1'b1 : 1'b0);

assign tmp_14_fu_775_p2 = (($signed(p_p2_i_i_fu_767_p3) < $signed(p_src_rows_V_read)) ? 1'b1 : 1'b0);

assign tmp_154_0_1_fu_805_p2 = (($signed(p_assign_6_0_1_fu_785_p2) < $signed(p_src_rows_V_read)) ? 1'b1 : 1'b0);

assign tmp_154_0_2_fu_868_p2 = (($signed(p_assign_6_0_2_fu_848_p2) < $signed(p_src_rows_V_read)) ? 1'b1 : 1'b0);

assign tmp_15_fu_1035_p2 = (($signed(ImagLoc_x_fu_1015_p2) < $signed(p_src_cols_V_read)) ? 1'b1 : 1'b0);

assign tmp_164_0_1_fu_838_p2 = (($signed(p_p2_i_i_0_1_fu_830_p3) < $signed(p_src_rows_V_read)) ? 1'b1 : 1'b0);

assign tmp_164_0_2_fu_901_p2 = (($signed(p_p2_i_i_0_2_fu_893_p3) < $signed(p_src_rows_V_read)) ? 1'b1 : 1'b0);

assign tmp_16_fu_1068_p2 = (($signed(p_p2_i429_i_fu_1060_p3) < $signed(p_src_cols_V_read)) ? 1'b1 : 1'b0);

assign tmp_172_0_0_2_cast_fu_1624_p1 = src_kernel_win_0_va_8_reg_2800;

assign tmp_172_0_1_cast_67_fu_1674_p1 = r_V_2_0_1_2_fu_1667_p3;

assign tmp_172_0_1_cast_fu_1655_p1 = r_V_2_0_1_fu_1649_p2;

assign tmp_172_0_2_2_cast_c_fu_1701_p1 = src_kernel_win_0_va_6_reg_2786;

assign tmp_172_0_2_cast_fu_1693_p1 = r_V_2_0_2_fu_1687_p2;

assign tmp_172_1_0_2_cast_fu_1792_p1 = src_kernel_win_1_va_8_reg_2820;

assign tmp_172_1_1_cast_68_fu_1842_p1 = r_V_2_1_1_2_fu_1835_p3;

assign tmp_172_1_1_cast_fu_1823_p1 = r_V_2_1_1_fu_1817_p2;

assign tmp_172_1_2_2_cast_c_fu_1869_p1 = src_kernel_win_1_va_6_reg_2806;

assign tmp_172_1_2_cast_fu_1861_p1 = r_V_2_1_2_fu_1855_p2;

assign tmp_172_2_0_2_cast_fu_1960_p1 = src_kernel_win_2_va_11_reg_2840;

assign tmp_172_2_1_cast_69_fu_2010_p1 = r_V_2_2_1_2_fu_2003_p3;

assign tmp_172_2_1_cast_fu_1991_p1 = r_V_2_2_1_fu_1985_p2;

assign tmp_172_2_2_2_cast_c_fu_2037_p1 = src_kernel_win_2_va_9_reg_2826;

assign tmp_172_2_2_cast_fu_2029_p1 = r_V_2_2_2_fu_2023_p2;

assign tmp_17_fu_1113_p1 = x_reg_2697;

assign tmp_1_fu_705_p2 = ((t_V_reg_597 == 32'd1) ? 1'b1 : 1'b0);

assign tmp_24_fu_1763_p4 = {{p_Val2_20_fu_1726_p2[10:8]}};

assign tmp_31_fu_1931_p4 = {{p_Val2_23_fu_1894_p2[10:8]}};

assign tmp_33_fu_662_p2 = p_src_cols_V_read << 32'd1;

assign tmp_34_fu_689_p4 = {{t_V_reg_597[31:1]}};

assign tmp_35_fu_728_p3 = tmp_11_fu_722_p2[32'd31];

assign tmp_36_fu_753_p3 = tmp_11_fu_722_p2[32'd31];

assign tmp_38_fu_791_p3 = p_assign_6_0_1_fu_785_p2[32'd31];

assign tmp_3_fu_619_p2 = (tmp_2_reg_586 + 2'd1);

assign tmp_43_fu_2099_p4 = {{p_Val2_s_fu_2062_p2[10:8]}};

assign tmp_45_fu_816_p3 = p_assign_6_0_1_fu_785_p2[32'd31];

assign tmp_46_fu_854_p3 = p_assign_6_0_2_fu_848_p2[32'd31];

assign tmp_47_fu_879_p3 = p_assign_6_0_2_fu_848_p2[32'd31];

assign tmp_48_fu_968_p1 = row_assign_9_fu_964_p2[1:0];

assign tmp_4_fu_625_p2 = ((tmp_2_reg_586 == 2'd2) ? 1'b1 : 1'b0);

assign tmp_50_fu_976_p1 = row_assign_9_0_1_fu_972_p2[1:0];

assign tmp_57_fu_984_p1 = row_assign_9_0_2_fu_980_p2[1:0];

assign tmp_58_fu_999_p4 = {{t_V_4_reg_608[31:1]}};

assign tmp_59_fu_1021_p3 = ImagLoc_x_fu_1015_p2[32'd31];

assign tmp_5_fu_636_p2 = (32'd2 + p_src_rows_V_read);

assign tmp_60_fu_1046_p3 = ImagLoc_x_fu_1015_p2[32'd31];

assign tmp_62_fu_1104_p1 = col_assign_2_fu_1094_p2[1:0];

assign tmp_65_fu_1659_p1 = p_Val2_8_0_0_2_fu_1627_p2[7:0];

assign tmp_66_fu_1663_p1 = r_V_2_0_1_fu_1649_p2[7:0];

assign tmp_67_fu_1678_p2 = src_kernel_win_0_va_7_reg_2793 << 8'd1;

assign tmp_68_fu_1697_p1 = r_V_2_0_2_fu_1687_p2[7:0];

assign tmp_6_fu_646_p2 = (32'd3 + p_src_cols_V_read);

assign tmp_73_fu_1827_p1 = p_Val2_8_1_0_2_fu_1795_p2[7:0];

assign tmp_74_fu_1831_p1 = r_V_2_1_1_fu_1817_p2[7:0];

assign tmp_75_fu_1846_p2 = src_kernel_win_1_va_7_reg_2813 << 8'd1;

assign tmp_76_fu_1865_p1 = r_V_2_1_2_fu_1855_p2[7:0];

assign tmp_7_fu_656_p2 = (32'd2 + tmp_fu_651_p2);

assign tmp_80_2_fu_667_p2 = ($signed(32'd4294967294) + $signed(tmp_33_fu_662_p2));

assign tmp_81_fu_1995_p1 = p_Val2_8_2_0_2_fu_1963_p2[7:0];

assign tmp_82_fu_1999_p1 = r_V_2_2_1_fu_1985_p2[7:0];

assign tmp_83_fu_2014_p2 = src_kernel_win_2_va_10_reg_2833 << 8'd1;

assign tmp_84_0_0_not_fu_959_p2 = (tmp_8_reg_2612 ^ 1'd1);

assign tmp_84_fu_2033_p1 = r_V_2_2_2_fu_2023_p2[7:0];

assign tmp_8_fu_684_p2 = ((t_V_reg_597 < p_src_rows_V_read) ? 1'b1 : 1'b0);

assign tmp_8_i_i1_fu_2254_p2 = (isneg_1_reg_2862 ^ 1'd1);

assign tmp_8_i_i2_fu_2285_p2 = (isneg_2_reg_2878 ^ 1'd1);

assign tmp_8_i_i_fu_2223_p2 = (isneg_reg_2846 ^ 1'd1);

assign tmp_fu_651_p2 = p_src_rows_V_read << 32'd1;

assign tmp_i_i2_fu_2272_p2 = (overflow_3_fu_2259_p2 | isneg_1_reg_2862);

assign tmp_i_i3_fu_2303_p2 = (overflow_4_fu_2290_p2 | isneg_2_reg_2878);

assign tmp_i_i_fu_2241_p2 = (overflow_fu_2228_p2 | isneg_reg_2846);

assign tmp_s_fu_631_p2 = (32'd2 + p_src_cols_V_read);

assign x_fu_1086_p3 = ((or_cond_i427_i_fu_1040_p2[0:0] === 1'b1) ? ImagLoc_x_fu_1015_p2 : p_p2_i429_i_p_assign_2_fu_1078_p3);

assign y_1_0_1_fu_935_p3 = ((or_cond_i_i_0_1_fu_810_p2[0:0] === 1'b1) ? p_assign_6_0_1_fu_785_p2 : p_p2_i_i_0_1_p_assign_fu_927_p3);

assign y_1_0_2_fu_951_p3 = ((or_cond_i_i_0_2_fu_873_p2[0:0] === 1'b1) ? p_assign_6_0_2_fu_848_p2 : p_p2_i_i_0_2_p_assign_fu_943_p3);

assign y_1_fu_919_p3 = ((or_cond_i_i_fu_747_p2[0:0] === 1'b1) ? tmp_11_fu_722_p2 : p_p2_i_i_0_p_assign_8_fu_911_p3);

endmodule //Filter2D
