// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "AddWeighted.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic AddWeighted::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic AddWeighted::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> AddWeighted::ap_ST_fsm_state1 = "1";
const sc_lv<4> AddWeighted::ap_ST_fsm_state2 = "10";
const sc_lv<4> AddWeighted::ap_ST_fsm_pp0_stage0 = "100";
const sc_lv<4> AddWeighted::ap_ST_fsm_state16 = "1000";
const bool AddWeighted::ap_const_boolean_1 = true;
const sc_lv<32> AddWeighted::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> AddWeighted::ap_const_lv32_2 = "10";
const bool AddWeighted::ap_const_boolean_0 = false;
const sc_lv<1> AddWeighted::ap_const_lv1_0 = "0";
const sc_lv<32> AddWeighted::ap_const_lv32_1 = "1";
const sc_lv<1> AddWeighted::ap_const_lv1_1 = "1";
const sc_lv<32> AddWeighted::ap_const_lv32_3 = "11";
const sc_lv<64> AddWeighted::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";

AddWeighted::AddWeighted(sc_module_name name) : sc_module(name), mVcdFile(0) {
    array_mul_dadd_64cud_U25 = new array_mul_dadd_64cud<1,5,64,64,64>("array_mul_dadd_64cud_U25");
    array_mul_dadd_64cud_U25->clk(ap_clk);
    array_mul_dadd_64cud_U25->reset(ap_rst);
    array_mul_dadd_64cud_U25->din0(tmp_14_reg_172);
    array_mul_dadd_64cud_U25->din1(tmp_15_reg_177);
    array_mul_dadd_64cud_U25->ce(grp_fu_113_ce);
    array_mul_dadd_64cud_U25->dout(grp_fu_113_p2);
    array_mul_dadd_64cud_U26 = new array_mul_dadd_64cud<1,5,64,64,64>("array_mul_dadd_64cud_U26");
    array_mul_dadd_64cud_U26->clk(ap_clk);
    array_mul_dadd_64cud_U26->reset(ap_rst);
    array_mul_dadd_64cud_U26->din0(tmp_i_112_reg_182);
    array_mul_dadd_64cud_U26->din1(ap_var_for_const0);
    array_mul_dadd_64cud_U26->ce(grp_fu_117_ce);
    array_mul_dadd_64cud_U26->dout(grp_fu_117_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_01001);
    sensitive << ( src1_data_stream_V_empty_n );
    sensitive << ( src2_data_stream_V_empty_n );
    sensitive << ( dst_data_stream_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( exitcond_i_reg_163 );
    sensitive << ( ap_enable_reg_pp0_iter12 );
    sensitive << ( exitcond_i_reg_163_pp0_iter11_reg );

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( src1_data_stream_V_empty_n );
    sensitive << ( src2_data_stream_V_empty_n );
    sensitive << ( dst_data_stream_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( exitcond_i_reg_163 );
    sensitive << ( ap_enable_reg_pp0_iter12 );
    sensitive << ( exitcond_i_reg_163_pp0_iter11_reg );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( src1_data_stream_V_empty_n );
    sensitive << ( src2_data_stream_V_empty_n );
    sensitive << ( dst_data_stream_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( exitcond_i_reg_163 );
    sensitive << ( ap_enable_reg_pp0_iter12 );
    sensitive << ( exitcond_i_reg_163_pp0_iter11_reg );

    SC_METHOD(thread_ap_block_state10_pp0_stage0_iter7);

    SC_METHOD(thread_ap_block_state11_pp0_stage0_iter8);

    SC_METHOD(thread_ap_block_state12_pp0_stage0_iter9);

    SC_METHOD(thread_ap_block_state13_pp0_stage0_iter10);

    SC_METHOD(thread_ap_block_state14_pp0_stage0_iter11);

    SC_METHOD(thread_ap_block_state15_pp0_stage0_iter12);
    sensitive << ( dst_data_stream_V_full_n );
    sensitive << ( exitcond_i_reg_163_pp0_iter11_reg );

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter1);
    sensitive << ( src1_data_stream_V_empty_n );
    sensitive << ( src2_data_stream_V_empty_n );
    sensitive << ( exitcond_i_reg_163 );

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state6_pp0_stage0_iter3);

    SC_METHOD(thread_ap_block_state7_pp0_stage0_iter4);

    SC_METHOD(thread_ap_block_state8_pp0_stage0_iter5);

    SC_METHOD(thread_ap_block_state9_pp0_stage0_iter6);

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state3);
    sensitive << ( exitcond_i_fu_133_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( exitcond2_i_fu_122_p2 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter12 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( ap_enable_reg_pp0_iter8 );
    sensitive << ( ap_enable_reg_pp0_iter9 );
    sensitive << ( ap_enable_reg_pp0_iter10 );
    sensitive << ( ap_enable_reg_pp0_iter11 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( exitcond2_i_fu_122_p2 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_dst_data_stream_V_blk_n);
    sensitive << ( dst_data_stream_V_full_n );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter12 );
    sensitive << ( exitcond_i_reg_163_pp0_iter11_reg );

    SC_METHOD(thread_dst_data_stream_V_din);
    sensitive << ( ap_enable_reg_pp0_iter12 );
    sensitive << ( exitcond_i_reg_163_pp0_iter11_reg );
    sensitive << ( sum_reg_187 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_dst_data_stream_V_write);
    sensitive << ( ap_enable_reg_pp0_iter12 );
    sensitive << ( exitcond_i_reg_163_pp0_iter11_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_exitcond2_i_fu_122_p2);
    sensitive << ( src1_rows_V_read );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( t_V_reg_91 );

    SC_METHOD(thread_exitcond_i_fu_133_p2);
    sensitive << ( src1_cols_V_read );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( t_V_4_reg_102 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_grp_fu_113_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_grp_fu_117_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_i_V_fu_127_p2);
    sensitive << ( t_V_reg_91 );

    SC_METHOD(thread_j_V_fu_138_p2);
    sensitive << ( t_V_4_reg_102 );

    SC_METHOD(thread_src1_data_stream_V_blk_n);
    sensitive << ( src1_data_stream_V_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( exitcond_i_reg_163 );

    SC_METHOD(thread_src1_data_stream_V_read);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( exitcond_i_reg_163 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_src2_data_stream_V_blk_n);
    sensitive << ( src2_data_stream_V_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( exitcond_i_reg_163 );

    SC_METHOD(thread_src2_data_stream_V_read);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( exitcond_i_reg_163 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter12 );
    sensitive << ( exitcond2_i_fu_122_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_i_fu_133_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_enable_reg_pp0_iter11 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "0001";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter12 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter4 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter5 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter6 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter7 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter8 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter9 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter10 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter11 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "AddWeighted_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, src1_rows_V_read, "(port)src1_rows_V_read");
    sc_trace(mVcdFile, src1_cols_V_read, "(port)src1_cols_V_read");
    sc_trace(mVcdFile, src1_data_stream_V_dout, "(port)src1_data_stream_V_dout");
    sc_trace(mVcdFile, src1_data_stream_V_empty_n, "(port)src1_data_stream_V_empty_n");
    sc_trace(mVcdFile, src1_data_stream_V_read, "(port)src1_data_stream_V_read");
    sc_trace(mVcdFile, src2_data_stream_V_dout, "(port)src2_data_stream_V_dout");
    sc_trace(mVcdFile, src2_data_stream_V_empty_n, "(port)src2_data_stream_V_empty_n");
    sc_trace(mVcdFile, src2_data_stream_V_read, "(port)src2_data_stream_V_read");
    sc_trace(mVcdFile, dst_data_stream_V_din, "(port)dst_data_stream_V_din");
    sc_trace(mVcdFile, dst_data_stream_V_full_n, "(port)dst_data_stream_V_full_n");
    sc_trace(mVcdFile, dst_data_stream_V_write, "(port)dst_data_stream_V_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, src1_data_stream_V_blk_n, "src1_data_stream_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, exitcond_i_reg_163, "exitcond_i_reg_163");
    sc_trace(mVcdFile, src2_data_stream_V_blk_n, "src2_data_stream_V_blk_n");
    sc_trace(mVcdFile, dst_data_stream_V_blk_n, "dst_data_stream_V_blk_n");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter12, "ap_enable_reg_pp0_iter12");
    sc_trace(mVcdFile, exitcond_i_reg_163_pp0_iter11_reg, "exitcond_i_reg_163_pp0_iter11_reg");
    sc_trace(mVcdFile, t_V_4_reg_102, "t_V_4_reg_102");
    sc_trace(mVcdFile, exitcond2_i_fu_122_p2, "exitcond2_i_fu_122_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, i_V_fu_127_p2, "i_V_fu_127_p2");
    sc_trace(mVcdFile, i_V_reg_158, "i_V_reg_158");
    sc_trace(mVcdFile, exitcond_i_fu_133_p2, "exitcond_i_fu_133_p2");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter0, "ap_block_state3_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter1, "ap_block_state4_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter2, "ap_block_state5_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage0_iter3, "ap_block_state6_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_state7_pp0_stage0_iter4, "ap_block_state7_pp0_stage0_iter4");
    sc_trace(mVcdFile, ap_block_state8_pp0_stage0_iter5, "ap_block_state8_pp0_stage0_iter5");
    sc_trace(mVcdFile, ap_block_state9_pp0_stage0_iter6, "ap_block_state9_pp0_stage0_iter6");
    sc_trace(mVcdFile, ap_block_state10_pp0_stage0_iter7, "ap_block_state10_pp0_stage0_iter7");
    sc_trace(mVcdFile, ap_block_state11_pp0_stage0_iter8, "ap_block_state11_pp0_stage0_iter8");
    sc_trace(mVcdFile, ap_block_state12_pp0_stage0_iter9, "ap_block_state12_pp0_stage0_iter9");
    sc_trace(mVcdFile, ap_block_state13_pp0_stage0_iter10, "ap_block_state13_pp0_stage0_iter10");
    sc_trace(mVcdFile, ap_block_state14_pp0_stage0_iter11, "ap_block_state14_pp0_stage0_iter11");
    sc_trace(mVcdFile, ap_block_state15_pp0_stage0_iter12, "ap_block_state15_pp0_stage0_iter12");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, exitcond_i_reg_163_pp0_iter1_reg, "exitcond_i_reg_163_pp0_iter1_reg");
    sc_trace(mVcdFile, exitcond_i_reg_163_pp0_iter2_reg, "exitcond_i_reg_163_pp0_iter2_reg");
    sc_trace(mVcdFile, exitcond_i_reg_163_pp0_iter3_reg, "exitcond_i_reg_163_pp0_iter3_reg");
    sc_trace(mVcdFile, exitcond_i_reg_163_pp0_iter4_reg, "exitcond_i_reg_163_pp0_iter4_reg");
    sc_trace(mVcdFile, exitcond_i_reg_163_pp0_iter5_reg, "exitcond_i_reg_163_pp0_iter5_reg");
    sc_trace(mVcdFile, exitcond_i_reg_163_pp0_iter6_reg, "exitcond_i_reg_163_pp0_iter6_reg");
    sc_trace(mVcdFile, exitcond_i_reg_163_pp0_iter7_reg, "exitcond_i_reg_163_pp0_iter7_reg");
    sc_trace(mVcdFile, exitcond_i_reg_163_pp0_iter8_reg, "exitcond_i_reg_163_pp0_iter8_reg");
    sc_trace(mVcdFile, exitcond_i_reg_163_pp0_iter9_reg, "exitcond_i_reg_163_pp0_iter9_reg");
    sc_trace(mVcdFile, exitcond_i_reg_163_pp0_iter10_reg, "exitcond_i_reg_163_pp0_iter10_reg");
    sc_trace(mVcdFile, j_V_fu_138_p2, "j_V_fu_138_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, tmp_14_reg_172, "tmp_14_reg_172");
    sc_trace(mVcdFile, tmp_15_reg_177, "tmp_15_reg_177");
    sc_trace(mVcdFile, grp_fu_113_p2, "grp_fu_113_p2");
    sc_trace(mVcdFile, tmp_i_112_reg_182, "tmp_i_112_reg_182");
    sc_trace(mVcdFile, grp_fu_117_p2, "grp_fu_117_p2");
    sc_trace(mVcdFile, sum_reg_187, "sum_reg_187");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state3, "ap_condition_pp0_exit_iter0_state3");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter4, "ap_enable_reg_pp0_iter4");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter5, "ap_enable_reg_pp0_iter5");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter6, "ap_enable_reg_pp0_iter6");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter7, "ap_enable_reg_pp0_iter7");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter8, "ap_enable_reg_pp0_iter8");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter9, "ap_enable_reg_pp0_iter9");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter10, "ap_enable_reg_pp0_iter10");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter11, "ap_enable_reg_pp0_iter11");
    sc_trace(mVcdFile, t_V_reg_91, "t_V_reg_91");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, ap_block_pp0_stage0_01001, "ap_block_pp0_stage0_01001");
    sc_trace(mVcdFile, grp_fu_113_ce, "grp_fu_113_ce");
    sc_trace(mVcdFile, grp_fu_117_ce, "grp_fu_117_ce");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

AddWeighted::~AddWeighted() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete array_mul_dadd_64cud_U25;
    delete array_mul_dadd_64cud_U26;
}

void AddWeighted::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_lv64_0;
}

void AddWeighted::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state3.read()) && 
             esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(exitcond2_i_fu_122_p2.read(), ap_const_lv1_0) && 
                    esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state3.read())) {
                ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state3.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter10 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            ap_enable_reg_pp0_iter10 = ap_enable_reg_pp0_iter9.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter11 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            ap_enable_reg_pp0_iter11 = ap_enable_reg_pp0_iter10.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter12 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            ap_enable_reg_pp0_iter12 = ap_enable_reg_pp0_iter11.read();
        } else if ((esl_seteq<1,1,1>(exitcond2_i_fu_122_p2.read(), ap_const_lv1_0) && 
                    esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
            ap_enable_reg_pp0_iter12 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter4 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            ap_enable_reg_pp0_iter4 = ap_enable_reg_pp0_iter3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter5 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            ap_enable_reg_pp0_iter5 = ap_enable_reg_pp0_iter4.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter6 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            ap_enable_reg_pp0_iter6 = ap_enable_reg_pp0_iter5.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter7 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            ap_enable_reg_pp0_iter7 = ap_enable_reg_pp0_iter6.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter8 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            ap_enable_reg_pp0_iter8 = ap_enable_reg_pp0_iter7.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter9 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            ap_enable_reg_pp0_iter9 = ap_enable_reg_pp0_iter8.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_fu_133_p2.read()))) {
        t_V_4_reg_102 = j_V_fu_138_p2.read();
    } else if ((esl_seteq<1,1,1>(exitcond2_i_fu_122_p2.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        t_V_4_reg_102 = ap_const_lv32_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        t_V_reg_91 = i_V_reg_158.read();
    } else if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        t_V_reg_91 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        exitcond_i_reg_163 = exitcond_i_fu_133_p2.read();
        exitcond_i_reg_163_pp0_iter1_reg = exitcond_i_reg_163.read();
    }
    if (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) {
        exitcond_i_reg_163_pp0_iter10_reg = exitcond_i_reg_163_pp0_iter9_reg.read();
        exitcond_i_reg_163_pp0_iter11_reg = exitcond_i_reg_163_pp0_iter10_reg.read();
        exitcond_i_reg_163_pp0_iter2_reg = exitcond_i_reg_163_pp0_iter1_reg.read();
        exitcond_i_reg_163_pp0_iter3_reg = exitcond_i_reg_163_pp0_iter2_reg.read();
        exitcond_i_reg_163_pp0_iter4_reg = exitcond_i_reg_163_pp0_iter3_reg.read();
        exitcond_i_reg_163_pp0_iter5_reg = exitcond_i_reg_163_pp0_iter4_reg.read();
        exitcond_i_reg_163_pp0_iter6_reg = exitcond_i_reg_163_pp0_iter5_reg.read();
        exitcond_i_reg_163_pp0_iter7_reg = exitcond_i_reg_163_pp0_iter6_reg.read();
        exitcond_i_reg_163_pp0_iter8_reg = exitcond_i_reg_163_pp0_iter7_reg.read();
        exitcond_i_reg_163_pp0_iter9_reg = exitcond_i_reg_163_pp0_iter8_reg.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_V_reg_158 = i_V_fu_127_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_reg_163_pp0_iter10_reg.read()))) {
        sum_reg_187 = grp_fu_117_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(exitcond_i_reg_163.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        tmp_14_reg_172 = src1_data_stream_V_dout.read();
        tmp_15_reg_177 = src2_data_stream_V_dout.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_reg_163_pp0_iter5_reg.read()))) {
        tmp_i_112_reg_182 = grp_fu_113_p2.read();
    }
}

void AddWeighted::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[2];
}

void AddWeighted::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void AddWeighted::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read()[3];
}

void AddWeighted::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void AddWeighted::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void AddWeighted::thread_ap_block_pp0_stage0_01001() {
    ap_block_pp0_stage0_01001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  ((esl_seteq<1,1,1>(exitcond_i_reg_163.read(), ap_const_lv1_0) && 
    esl_seteq<1,1,1>(ap_const_logic_0, src1_data_stream_V_empty_n.read())) || 
   (esl_seteq<1,1,1>(exitcond_i_reg_163.read(), ap_const_lv1_0) && 
    esl_seteq<1,1,1>(ap_const_logic_0, src2_data_stream_V_empty_n.read())))) || (esl_seteq<1,1,1>(ap_enable_reg_pp0_iter12.read(), ap_const_logic_1) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_reg_163_pp0_iter11_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, dst_data_stream_V_full_n.read())));
}

void AddWeighted::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  ((esl_seteq<1,1,1>(exitcond_i_reg_163.read(), ap_const_lv1_0) && 
    esl_seteq<1,1,1>(ap_const_logic_0, src1_data_stream_V_empty_n.read())) || 
   (esl_seteq<1,1,1>(exitcond_i_reg_163.read(), ap_const_lv1_0) && 
    esl_seteq<1,1,1>(ap_const_logic_0, src2_data_stream_V_empty_n.read())))) || (esl_seteq<1,1,1>(ap_enable_reg_pp0_iter12.read(), ap_const_logic_1) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_reg_163_pp0_iter11_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, dst_data_stream_V_full_n.read())));
}

void AddWeighted::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  ((esl_seteq<1,1,1>(exitcond_i_reg_163.read(), ap_const_lv1_0) && 
    esl_seteq<1,1,1>(ap_const_logic_0, src1_data_stream_V_empty_n.read())) || 
   (esl_seteq<1,1,1>(exitcond_i_reg_163.read(), ap_const_lv1_0) && 
    esl_seteq<1,1,1>(ap_const_logic_0, src2_data_stream_V_empty_n.read())))) || (esl_seteq<1,1,1>(ap_enable_reg_pp0_iter12.read(), ap_const_logic_1) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_reg_163_pp0_iter11_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, dst_data_stream_V_full_n.read())));
}

void AddWeighted::thread_ap_block_state10_pp0_stage0_iter7() {
    ap_block_state10_pp0_stage0_iter7 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void AddWeighted::thread_ap_block_state11_pp0_stage0_iter8() {
    ap_block_state11_pp0_stage0_iter8 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void AddWeighted::thread_ap_block_state12_pp0_stage0_iter9() {
    ap_block_state12_pp0_stage0_iter9 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void AddWeighted::thread_ap_block_state13_pp0_stage0_iter10() {
    ap_block_state13_pp0_stage0_iter10 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void AddWeighted::thread_ap_block_state14_pp0_stage0_iter11() {
    ap_block_state14_pp0_stage0_iter11 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void AddWeighted::thread_ap_block_state15_pp0_stage0_iter12() {
    ap_block_state15_pp0_stage0_iter12 = (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_reg_163_pp0_iter11_reg.read()) && esl_seteq<1,1,1>(ap_const_logic_0, dst_data_stream_V_full_n.read()));
}

void AddWeighted::thread_ap_block_state3_pp0_stage0_iter0() {
    ap_block_state3_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void AddWeighted::thread_ap_block_state4_pp0_stage0_iter1() {
    ap_block_state4_pp0_stage0_iter1 = ((esl_seteq<1,1,1>(exitcond_i_reg_163.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, src1_data_stream_V_empty_n.read())) || (esl_seteq<1,1,1>(exitcond_i_reg_163.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, src2_data_stream_V_empty_n.read())));
}

void AddWeighted::thread_ap_block_state5_pp0_stage0_iter2() {
    ap_block_state5_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void AddWeighted::thread_ap_block_state6_pp0_stage0_iter3() {
    ap_block_state6_pp0_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void AddWeighted::thread_ap_block_state7_pp0_stage0_iter4() {
    ap_block_state7_pp0_stage0_iter4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void AddWeighted::thread_ap_block_state8_pp0_stage0_iter5() {
    ap_block_state8_pp0_stage0_iter5 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void AddWeighted::thread_ap_block_state9_pp0_stage0_iter6() {
    ap_block_state9_pp0_stage0_iter6 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void AddWeighted::thread_ap_condition_pp0_exit_iter0_state3() {
    if (esl_seteq<1,1,1>(exitcond_i_fu_133_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state3 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state3 = ap_const_logic_0;
    }
}

void AddWeighted::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(exitcond2_i_fu_122_p2.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void AddWeighted::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void AddWeighted::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void AddWeighted::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter5.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter6.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter7.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter8.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter9.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter10.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter11.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter12.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void AddWeighted::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(exitcond2_i_fu_122_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void AddWeighted::thread_dst_data_stream_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter12.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_reg_163_pp0_iter11_reg.read()))) {
        dst_data_stream_V_blk_n = dst_data_stream_V_full_n.read();
    } else {
        dst_data_stream_V_blk_n = ap_const_logic_1;
    }
}

void AddWeighted::thread_dst_data_stream_V_din() {
    dst_data_stream_V_din = sum_reg_187.read();
}

void AddWeighted::thread_dst_data_stream_V_write() {
    if ((esl_seteq<1,1,1>(ap_enable_reg_pp0_iter12.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_reg_163_pp0_iter11_reg.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        dst_data_stream_V_write = ap_const_logic_1;
    } else {
        dst_data_stream_V_write = ap_const_logic_0;
    }
}

void AddWeighted::thread_exitcond2_i_fu_122_p2() {
    exitcond2_i_fu_122_p2 = (!t_V_reg_91.read().is_01() || !src1_rows_V_read.read().is_01())? sc_lv<1>(): sc_lv<1>(t_V_reg_91.read() == src1_rows_V_read.read());
}

void AddWeighted::thread_exitcond_i_fu_133_p2() {
    exitcond_i_fu_133_p2 = (!t_V_4_reg_102.read().is_01() || !src1_cols_V_read.read().is_01())? sc_lv<1>(): sc_lv<1>(t_V_4_reg_102.read() == src1_cols_V_read.read());
}

void AddWeighted::thread_grp_fu_113_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        grp_fu_113_ce = ap_const_logic_1;
    } else {
        grp_fu_113_ce = ap_const_logic_0;
    }
}

void AddWeighted::thread_grp_fu_117_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        grp_fu_117_ce = ap_const_logic_1;
    } else {
        grp_fu_117_ce = ap_const_logic_0;
    }
}

void AddWeighted::thread_i_V_fu_127_p2() {
    i_V_fu_127_p2 = (!t_V_reg_91.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(t_V_reg_91.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void AddWeighted::thread_j_V_fu_138_p2() {
    j_V_fu_138_p2 = (!t_V_4_reg_102.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(t_V_4_reg_102.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void AddWeighted::thread_src1_data_stream_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(exitcond_i_reg_163.read(), ap_const_lv1_0))) {
        src1_data_stream_V_blk_n = src1_data_stream_V_empty_n.read();
    } else {
        src1_data_stream_V_blk_n = ap_const_logic_1;
    }
}

void AddWeighted::thread_src1_data_stream_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(exitcond_i_reg_163.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        src1_data_stream_V_read = ap_const_logic_1;
    } else {
        src1_data_stream_V_read = ap_const_logic_0;
    }
}

void AddWeighted::thread_src2_data_stream_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(exitcond_i_reg_163.read(), ap_const_lv1_0))) {
        src2_data_stream_V_blk_n = src2_data_stream_V_empty_n.read();
    } else {
        src2_data_stream_V_blk_n = ap_const_logic_1;
    }
}

void AddWeighted::thread_src2_data_stream_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(exitcond_i_reg_163.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        src2_data_stream_V_read = ap_const_logic_1;
    } else {
        src2_data_stream_V_read = ap_const_logic_0;
    }
}

void AddWeighted::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(exitcond2_i_fu_122_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            if ((!(esl_seteq<1,1,1>(exitcond_i_fu_133_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) && !(esl_seteq<1,1,1>(ap_enable_reg_pp0_iter12.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter11.read(), ap_const_logic_0) && esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if (((esl_seteq<1,1,1>(ap_enable_reg_pp0_iter12.read(), ap_const_logic_1) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter11.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) || (esl_seteq<1,1,1>(exitcond_i_fu_133_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && 
  esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())))) {
                ap_NS_fsm = ap_ST_fsm_state16;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        default : 
            ap_NS_fsm = "XXXX";
            break;
    }
}

}

