// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _AXIvideo2Mat_HH_
#define _AXIvideo2Mat_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct AXIvideo2Mat : public sc_module {
    // Port declarations 35
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<128> > AXI_video_strm_V_data_V_dout;
    sc_in< sc_logic > AXI_video_strm_V_data_V_empty_n;
    sc_out< sc_logic > AXI_video_strm_V_data_V_read;
    sc_in< sc_lv<16> > AXI_video_strm_V_keep_V_dout;
    sc_in< sc_logic > AXI_video_strm_V_keep_V_empty_n;
    sc_out< sc_logic > AXI_video_strm_V_keep_V_read;
    sc_in< sc_lv<16> > AXI_video_strm_V_strb_V_dout;
    sc_in< sc_logic > AXI_video_strm_V_strb_V_empty_n;
    sc_out< sc_logic > AXI_video_strm_V_strb_V_read;
    sc_in< sc_lv<1> > AXI_video_strm_V_user_V_dout;
    sc_in< sc_logic > AXI_video_strm_V_user_V_empty_n;
    sc_out< sc_logic > AXI_video_strm_V_user_V_read;
    sc_in< sc_lv<1> > AXI_video_strm_V_last_V_dout;
    sc_in< sc_logic > AXI_video_strm_V_last_V_empty_n;
    sc_out< sc_logic > AXI_video_strm_V_last_V_read;
    sc_in< sc_lv<1> > AXI_video_strm_V_id_V_dout;
    sc_in< sc_logic > AXI_video_strm_V_id_V_empty_n;
    sc_out< sc_logic > AXI_video_strm_V_id_V_read;
    sc_in< sc_lv<1> > AXI_video_strm_V_dest_V_dout;
    sc_in< sc_logic > AXI_video_strm_V_dest_V_empty_n;
    sc_out< sc_logic > AXI_video_strm_V_dest_V_read;
    sc_in< sc_lv<32> > img_rows_V_read;
    sc_in< sc_lv<32> > img_cols_V_read;
    sc_out< sc_lv<64> > img_data_stream_0_V_din;
    sc_in< sc_logic > img_data_stream_0_V_full_n;
    sc_out< sc_logic > img_data_stream_0_V_write;
    sc_out< sc_lv<64> > img_data_stream_1_V_din;
    sc_in< sc_logic > img_data_stream_1_V_full_n;
    sc_out< sc_logic > img_data_stream_1_V_write;


    // Module declarations
    AXIvideo2Mat(sc_module_name name);
    SC_HAS_PROCESS(AXIvideo2Mat);

    ~AXIvideo2Mat();

    sc_trace_file* mVcdFile;

    sc_signal< sc_lv<8> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > AXI_video_strm_V_data_V_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_logic > ap_CS_fsm_pp1_stage0;
    sc_signal< sc_logic > ap_enable_reg_pp1_iter1;
    sc_signal< bool > ap_block_pp1_stage0;
    sc_signal< sc_lv<1> > exitcond_reg_379;
    sc_signal< sc_lv<1> > brmerge_fu_307_p2;
    sc_signal< sc_logic > ap_CS_fsm_state9;
    sc_signal< sc_lv<1> > ap_phi_mux_eol_2_phi_fu_256_p4;
    sc_signal< sc_logic > AXI_video_strm_V_keep_V_blk_n;
    sc_signal< sc_logic > AXI_video_strm_V_strb_V_blk_n;
    sc_signal< sc_logic > AXI_video_strm_V_user_V_blk_n;
    sc_signal< sc_logic > AXI_video_strm_V_last_V_blk_n;
    sc_signal< sc_logic > AXI_video_strm_V_id_V_blk_n;
    sc_signal< sc_logic > AXI_video_strm_V_dest_V_blk_n;
    sc_signal< sc_logic > img_data_stream_0_V_blk_n;
    sc_signal< sc_logic > ap_enable_reg_pp1_iter2;
    sc_signal< sc_lv<1> > exitcond_reg_379_pp1_iter1_reg;
    sc_signal< sc_logic > img_data_stream_1_V_blk_n;
    sc_signal< sc_lv<32> > t_V_6_reg_159;
    sc_signal< sc_lv<1> > eol_1_reg_170;
    sc_signal< sc_lv<128> > axi_data_V_1_reg_181;
    sc_signal< sc_lv<1> > eol_reg_192;
    sc_signal< sc_lv<1> > axi_last_V_2_reg_204;
    sc_signal< sc_lv<128> > p_Val2_s_reg_217;
    sc_signal< sc_lv<128> > tmp_data_V_reg_350;
    sc_signal< sc_logic > AXI_video_strm_V_id_V0_status;
    sc_signal< sc_lv<1> > tmp_last_V_reg_358;
    sc_signal< sc_lv<1> > exitcond6_fu_282_p2;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<32> > i_V_fu_287_p2;
    sc_signal< sc_lv<32> > i_V_reg_374;
    sc_signal< sc_lv<1> > exitcond_fu_293_p2;
    sc_signal< bool > ap_block_state5_pp1_stage0_iter0;
    sc_signal< bool > ap_predicate_op58_read_state6;
    sc_signal< bool > ap_block_state6_pp1_stage0_iter1;
    sc_signal< bool > ap_block_state7_pp1_stage0_iter2;
    sc_signal< bool > ap_block_pp1_stage0_11001;
    sc_signal< sc_lv<32> > j_V_fu_298_p2;
    sc_signal< sc_logic > ap_enable_reg_pp1_iter0;
    sc_signal< sc_lv<64> > p_Result_s_fu_313_p1;
    sc_signal< sc_lv<64> > p_Result_s_reg_392;
    sc_signal< sc_lv<64> > p_Result_1_reg_397;
    sc_signal< bool > ap_block_state9;
    sc_signal< bool > ap_block_pp1_stage0_subdone;
    sc_signal< sc_logic > ap_condition_pp1_exit_iter1_state6;
    sc_signal< sc_lv<1> > axi_last_V_3_reg_229;
    sc_signal< sc_lv<1> > axi_last_V1_reg_128;
    sc_signal< sc_logic > ap_CS_fsm_state10;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<128> > axi_data_V_3_reg_241;
    sc_signal< sc_lv<128> > axi_data_V1_reg_138;
    sc_signal< sc_lv<32> > t_V_reg_148;
    sc_signal< sc_lv<1> > ap_phi_mux_eol_1_phi_fu_173_p4;
    sc_signal< sc_lv<128> > ap_phi_mux_axi_data_V_1_phi_fu_184_p4;
    sc_signal< sc_lv<1> > ap_phi_mux_eol_phi_fu_196_p4;
    sc_signal< sc_lv<1> > ap_phi_reg_pp1_iter1_axi_last_V_2_reg_204;
    sc_signal< sc_lv<128> > ap_phi_mux_p_Val2_s_phi_fu_221_p4;
    sc_signal< sc_lv<128> > ap_phi_reg_pp1_iter1_p_Val2_s_reg_217;
    sc_signal< sc_logic > ap_CS_fsm_state8;
    sc_signal< sc_lv<1> > eol_2_reg_253;
    sc_signal< sc_logic > AXI_video_strm_V_id_V0_update;
    sc_signal< bool > ap_block_pp1_stage0_01001;
    sc_signal< sc_lv<1> > sof_1_fu_80;
    sc_signal< sc_lv<1> > tmp_user_V_fu_273_p1;
    sc_signal< sc_lv<8> > ap_NS_fsm;
    sc_signal< sc_logic > ap_idle_pp1;
    sc_signal< sc_logic > ap_enable_pp1;
    sc_signal< bool > ap_condition_274;
    sc_signal< bool > ap_condition_234;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<8> ap_ST_fsm_state1;
    static const sc_lv<8> ap_ST_fsm_state2;
    static const sc_lv<8> ap_ST_fsm_state3;
    static const sc_lv<8> ap_ST_fsm_state4;
    static const sc_lv<8> ap_ST_fsm_pp1_stage0;
    static const sc_lv<8> ap_ST_fsm_state8;
    static const sc_lv<8> ap_ST_fsm_state9;
    static const sc_lv<8> ap_ST_fsm_state10;
    static const bool ap_const_boolean_1;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_4;
    static const bool ap_const_boolean_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_40;
    static const sc_lv<32> ap_const_lv32_7F;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_AXI_video_strm_V_data_V_blk_n();
    void thread_AXI_video_strm_V_data_V_read();
    void thread_AXI_video_strm_V_dest_V_blk_n();
    void thread_AXI_video_strm_V_dest_V_read();
    void thread_AXI_video_strm_V_id_V0_status();
    void thread_AXI_video_strm_V_id_V0_update();
    void thread_AXI_video_strm_V_id_V_blk_n();
    void thread_AXI_video_strm_V_id_V_read();
    void thread_AXI_video_strm_V_keep_V_blk_n();
    void thread_AXI_video_strm_V_keep_V_read();
    void thread_AXI_video_strm_V_last_V_blk_n();
    void thread_AXI_video_strm_V_last_V_read();
    void thread_AXI_video_strm_V_strb_V_blk_n();
    void thread_AXI_video_strm_V_strb_V_read();
    void thread_AXI_video_strm_V_user_V_blk_n();
    void thread_AXI_video_strm_V_user_V_read();
    void thread_ap_CS_fsm_pp1_stage0();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state8();
    void thread_ap_CS_fsm_state9();
    void thread_ap_block_pp1_stage0();
    void thread_ap_block_pp1_stage0_01001();
    void thread_ap_block_pp1_stage0_11001();
    void thread_ap_block_pp1_stage0_subdone();
    void thread_ap_block_state5_pp1_stage0_iter0();
    void thread_ap_block_state6_pp1_stage0_iter1();
    void thread_ap_block_state7_pp1_stage0_iter2();
    void thread_ap_block_state9();
    void thread_ap_condition_234();
    void thread_ap_condition_274();
    void thread_ap_condition_pp1_exit_iter1_state6();
    void thread_ap_done();
    void thread_ap_enable_pp1();
    void thread_ap_idle();
    void thread_ap_idle_pp1();
    void thread_ap_phi_mux_axi_data_V_1_phi_fu_184_p4();
    void thread_ap_phi_mux_eol_1_phi_fu_173_p4();
    void thread_ap_phi_mux_eol_2_phi_fu_256_p4();
    void thread_ap_phi_mux_eol_phi_fu_196_p4();
    void thread_ap_phi_mux_p_Val2_s_phi_fu_221_p4();
    void thread_ap_phi_reg_pp1_iter1_axi_last_V_2_reg_204();
    void thread_ap_phi_reg_pp1_iter1_p_Val2_s_reg_217();
    void thread_ap_predicate_op58_read_state6();
    void thread_ap_ready();
    void thread_brmerge_fu_307_p2();
    void thread_exitcond6_fu_282_p2();
    void thread_exitcond_fu_293_p2();
    void thread_i_V_fu_287_p2();
    void thread_img_data_stream_0_V_blk_n();
    void thread_img_data_stream_0_V_din();
    void thread_img_data_stream_0_V_write();
    void thread_img_data_stream_1_V_blk_n();
    void thread_img_data_stream_1_V_din();
    void thread_img_data_stream_1_V_write();
    void thread_j_V_fu_298_p2();
    void thread_p_Result_s_fu_313_p1();
    void thread_tmp_user_V_fu_273_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
