// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _Scale_HH_
#define _Scale_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "arithm_pro.h"

namespace ap_rtl {

struct Scale : public sc_module {
    // Port declarations 27
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<32> > src_rows_V;
    sc_in< sc_lv<32> > src_cols_V;
    sc_in< sc_lv<8> > src_data_stream_0_V_dout;
    sc_in< sc_logic > src_data_stream_0_V_empty_n;
    sc_out< sc_logic > src_data_stream_0_V_read;
    sc_in< sc_lv<8> > src_data_stream_1_V_dout;
    sc_in< sc_logic > src_data_stream_1_V_empty_n;
    sc_out< sc_logic > src_data_stream_1_V_read;
    sc_in< sc_lv<8> > src_data_stream_2_V_dout;
    sc_in< sc_logic > src_data_stream_2_V_empty_n;
    sc_out< sc_logic > src_data_stream_2_V_read;
    sc_out< sc_lv<8> > dst_data_stream_0_V_din;
    sc_in< sc_logic > dst_data_stream_0_V_full_n;
    sc_out< sc_logic > dst_data_stream_0_V_write;
    sc_out< sc_lv<8> > dst_data_stream_1_V_din;
    sc_in< sc_logic > dst_data_stream_1_V_full_n;
    sc_out< sc_logic > dst_data_stream_1_V_write;
    sc_out< sc_lv<8> > dst_data_stream_2_V_din;
    sc_in< sc_logic > dst_data_stream_2_V_full_n;
    sc_out< sc_logic > dst_data_stream_2_V_write;


    // Module declarations
    Scale(sc_module_name name);
    SC_HAS_PROCESS(Scale);

    ~Scale();

    sc_trace_file* mVcdFile;

    arithm_pro* grp_arithm_pro_fu_150;
    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<2> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< bool > ap_block_state1;
    sc_signal< sc_logic > grp_arithm_pro_fu_150_ap_start;
    sc_signal< sc_logic > grp_arithm_pro_fu_150_ap_done;
    sc_signal< sc_logic > grp_arithm_pro_fu_150_ap_idle;
    sc_signal< sc_logic > grp_arithm_pro_fu_150_ap_ready;
    sc_signal< sc_logic > grp_arithm_pro_fu_150_src_data_stream_0_V_read;
    sc_signal< sc_logic > grp_arithm_pro_fu_150_src_data_stream_1_V_read;
    sc_signal< sc_logic > grp_arithm_pro_fu_150_src_data_stream_2_V_read;
    sc_signal< sc_lv<8> > grp_arithm_pro_fu_150_dst_data_stream_0_V_din;
    sc_signal< sc_logic > grp_arithm_pro_fu_150_dst_data_stream_0_V_write;
    sc_signal< sc_lv<8> > grp_arithm_pro_fu_150_dst_data_stream_1_V_din;
    sc_signal< sc_logic > grp_arithm_pro_fu_150_dst_data_stream_1_V_write;
    sc_signal< sc_lv<8> > grp_arithm_pro_fu_150_dst_data_stream_2_V_din;
    sc_signal< sc_logic > grp_arithm_pro_fu_150_dst_data_stream_2_V_write;
    sc_signal< sc_logic > grp_arithm_pro_fu_150_ap_start_reg;
    sc_signal< bool > ap_block_state1_ignore_call12;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<2> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<2> ap_ST_fsm_state1;
    static const sc_lv<2> ap_ST_fsm_state2;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_block_state1();
    void thread_ap_block_state1_ignore_call12();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_dst_data_stream_0_V_din();
    void thread_dst_data_stream_0_V_write();
    void thread_dst_data_stream_1_V_din();
    void thread_dst_data_stream_1_V_write();
    void thread_dst_data_stream_2_V_din();
    void thread_dst_data_stream_2_V_write();
    void thread_grp_arithm_pro_fu_150_ap_start();
    void thread_src_data_stream_0_V_read();
    void thread_src_data_stream_1_V_read();
    void thread_src_data_stream_2_V_read();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
